"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Testimonial={id:string;author_name:string;author_location:string|null;author_role:string|null;quote:string;rating:number|null;status:string;featured:boolean;consent_to_publish:boolean};
const empty={authorName:"",authorLocation:"",authorRole:"",quote:"",rating:5,status:"pending",featured:false,consentToPublish:false};
const label=(s:string)=>({approved:"Approuvé",pending:"En attente",rejected:"Rejeté"}[s]??s);

export default function TestimonialsAdmin(){
 const [items,setItems]=useState<Testimonial[]>([]);const [selected,setSelected]=useState<Testimonial|null>(null);const [form,setForm]=useState(empty);const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/testimonials",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();setItems(d.testimonials??[])}
 useEffect(()=>{void load()},[]);
 function edit(x:Testimonial){setSelected(x);setForm({authorName:x.author_name,authorLocation:x.author_location??"",authorRole:x.author_role??"",quote:x.quote,rating:x.rating??5,status:x.status,featured:x.featured,consentToPublish:x.consent_to_publish});setMessage("");}
 function create(){setSelected(null);setForm(empty);setMessage("");}
 async function save(e:FormEvent){e.preventDefault();setMessage("Enregistrement…");const r=await fetch("/api/admin/testimonials",{method:selected?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:selected?.id})});const d=await r.json();if(!r.ok){setMessage(d.error??"Erreur");return;}setMessage("Enregistré.");await load();if(d.testimonial)edit(d.testimonial)}
 async function quick(id:string,patch:Record<string,unknown>){await fetch("/api/admin/testimonials",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})});await load();}
 async function remove(){if(!selected||!confirm("Supprimer ce témoignage ?"))return;const r=await fetch(`/api/admin/testimonials?id=${selected.id}`,{method:"DELETE"});if(r.ok){create();await load()}}
 const stats=useMemo(()=>({all:items.length,approved:items.filter(x=>x.status==="approved").length,pending:items.filter(x=>x.status==="pending").length,featured:items.filter(x=>x.featured).length}),[items]);
 return <AdminWorkspace active="Témoignages" title="Témoignages" subtitle="Modérez, validez et mettez en avant les retours de la communauté MOONY." actions={<button onClick={create} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">+ Ajouter un témoignage</button>}>
 <div className="grid gap-4 sm:grid-cols-4">{[["Tous",stats.all],["Approuvés",stats.approved],["En attente",stats.pending],["Mis en avant",stats.featured]].map(([l,v])=><div key={String(l)} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/45">{l}</p><p className="moony-serif mt-2 text-4xl">{v}</p></div>)}</div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><AdminCard title="Témoignages clients"><div className="space-y-3">{items.map(x=><div key={x.id} onClick={()=>edit(x)} className={`cursor-pointer rounded-xl border p-4 ${selected?.id===x.id?"border-[#d08a66] bg-[#fbf0e8]":"border-[#5b2f22]/8 bg-white"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="block text-sm">{x.author_name}</strong><span className="text-xs text-[#5b2f22]/45">{[x.author_role,x.author_location].filter(Boolean).join(" · ")}</span></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1 text-xs ${x.status==="approved"?"bg-emerald-100 text-emerald-800":x.status==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-800"}`}>{label(x.status)}</span>{x.featured?<span className="rounded-full bg-[#f8e6dc] px-3 py-1 text-xs text-[#8d3b19]">Mis en avant</span>:null}</div></div><div className="mt-2 text-amber-500">{"★".repeat(x.rating??5)}<span className="text-zinc-200">{"★".repeat(Math.max(0,5-(x.rating??5)))}</span></div><p className="mt-2 text-sm leading-6 text-[#5b2f22]/70">« {x.quote} »</p><div className="mt-3 flex flex-wrap gap-2" onClick={e=>e.stopPropagation()}>{x.status!=="approved"?<button onClick={()=>quick(x.id,{status:"approved"})} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-xs text-emerald-800">Approuver</button>:null}{x.status!=="rejected"?<button onClick={()=>quick(x.id,{status:"rejected"})} className="rounded-lg bg-red-50 px-3 py-1.5 text-xs text-red-700">Rejeter</button>:null}<button onClick={()=>quick(x.id,{featured:!x.featured})} className="rounded-lg border border-[#5b2f22]/10 px-3 py-1.5 text-xs">{x.featured?"Retirer de la une":"Mettre en avant"}</button></div></div>)}</div></AdminCard>
 <AdminCard title={selected?"Modifier le témoignage":"Ajouter un témoignage"}><form onSubmit={save} className="space-y-3 text-sm"><label className="block">Nom<input required value={form.authorName} onChange={e=>setForm({...form,authorName:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label><div className="grid gap-3 sm:grid-cols-2"><label>Localisation<input value={form.authorLocation} onChange={e=>setForm({...form,authorLocation:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label><label>Rôle / profil<input value={form.authorRole} onChange={e=>setForm({...form,authorRole:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label></div><label className="block">Témoignage<textarea required rows={6} value={form.quote} onChange={e=>setForm({...form,quote:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label><div className="grid gap-3 sm:grid-cols-2"><label>Note<select value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"><option value="pending">En attente</option><option value="approved">Approuvé</option><option value="rejected">Rejeté</option></select></label></div><label className="flex items-center gap-2"><input type="checkbox" checked={form.consentToPublish} onChange={e=>setForm({...form,consentToPublish:e.target.checked})}/> Consentement de publication obtenu</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Mettre en avant sur le site</label><div className="flex gap-2"><button className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-white">Enregistrer</button>{selected?<button type="button" onClick={remove} className="rounded-lg border border-red-200 px-4 py-2.5 text-red-700">Supprimer</button>:null}</div><p className="text-xs text-[#5b2f22]/50">{message}</p></form></AdminCard></div>
 </AdminWorkspace>;
}
