import { NextResponse } from "next/server";
import { asText, requireAdmin, writeAuditLog } from "@/lib/admin-api";
import { buildPortfolioActions, computePortfolioPriority, monthlyEffort, weeklyEffort } from "@/lib/crm-executive-portfolio";

function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
function relation(value:any){return Array.isArray(value)?value[0]??null:value??null}
async function bodyOf(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function actor(session:any){return session.name||session.email||"MOONY Admin"}
function nullable(value:unknown,max=8000){const text=asText(value,max);return text||null}
function isoOrNull(value:unknown){const text=asText(value,80);if(!text)return null;const date=new Date(text);return Number.isNaN(date.getTime())?null:date.toISOString()}
function daysUntil(value:string|null|undefined){if(!value)return null;const time=new Date(value).getTime();if(Number.isNaN(time))return null;return Math.ceil((time-Date.now())/86400000)}

async function loadPortfolio(supabase:any){
 const profilesCheck=await supabase.from("website_crm_csm_capacity_profiles").select("id").limit(1);if(profilesCheck.error&&missing(profilesCheck.error))return{available:false,accounts:[],capacity:[],actions:[],metrics:{active:0,strategic:0,attention:0,renewals60:0,unassigned:0,openActions:0}};if(profilesCheck.error)throw new Error(profilesCheck.error.message);
 const [accountsResult,plansResult,objectivesResult,retentionResult,profilesResult,statesResult]=await Promise.all([
  supabase.from("website_crm_client_accounts").select("id,lead_id,account_name,status,owner,commercial_owner,activated_at,renewal_date,next_success_review_at,health_score,health_status,health_summary,governance_score,governance_status,governance_summary,portfolio_tier,service_effort_hours_monthly,portfolio_notes,website_leads(first_name,last_name,email,company,country),website_crm_opportunities(name,amount,currency)").eq("status","active").order("account_name",{ascending:true}).limit(1000),
  supabase.from("website_crm_success_plans").select("id,client_id,title,status,overall_progress,next_review_at,last_review_at").in("status",["draft","active","paused"]).limit(1000),
  supabase.from("website_crm_success_objectives").select("id,plan_id,title,status,progress,due_date").limit(5000),
  supabase.from("website_crm_retention_cases").select("id,client_id,title,status,priority,owner,due_at,opened_at").in("status",["open","in_progress"]).limit(2000),
  supabase.from("website_crm_csm_capacity_profiles").select("*").order("owner_name",{ascending:true}),
  supabase.from("website_crm_portfolio_action_states").select("*").limit(5000),
 ]);
 if(accountsResult.error)throw new Error(accountsResult.error.message);for(const result of [plansResult,objectivesResult,retentionResult,profilesResult,statesResult])if(result.error&&!missing(result.error))throw new Error(result.error.message);
 const plansByClient:Record<string,any>={};for(const row of plansResult.data??[]){if(!plansByClient[String(row.client_id)]||row.status==="active")plansByClient[String(row.client_id)]=row}
 const objectivesByPlan:Record<string,any[]>={};for(const row of objectivesResult.data??[])(objectivesByPlan[String(row.plan_id)]??=[]).push(row);
 const retentionByClient:Record<string,any[]>={};for(const row of retentionResult.data??[])(retentionByClient[String(row.client_id)]??=[]).push(row);
 const stateMap=new Map<string,any>();for(const row of statesResult.data??[])stateMap.set(`${row.client_id}:${row.action_key}`,row);
 const now=Date.now();const actions:any[]=[];
 const accounts=(accountsResult.data??[]).map((raw:any)=>{const account={...raw,website_leads:relation(raw.website_leads),website_crm_opportunities:relation(raw.website_crm_opportunities)};const plan=plansByClient[String(account.id)]??null;const objectives=plan?objectivesByPlan[String(plan.id)]??[]:[];const retentionCases=retentionByClient[String(account.id)]??[];const priority=computePortfolioPriority({account,plan,objectives,retentionCases,now});const generated=buildPortfolioActions({account,plan,objectives,retentionCases,now});for(const item of generated){const state=stateMap.get(`${account.id}:${item.key}`);if(state?.status==="done"||state?.status==="dismissed")continue;if(state?.status==="snoozed"&&state.snoozed_until&&new Date(state.snoozed_until).getTime()>now)continue;actions.push({...item,state:state?.status||"open"})}return{...account,plan,objectivesAtRisk:objectives.filter((row:any)=>["blocked","at_risk"].includes(row.status)).length,retentionOpen:retentionCases.length,priority,monthlyEffort:monthlyEffort(account),weeklyEffort:weeklyEffort(account),openActions:generated.filter((item:any)=>{const state=stateMap.get(`${account.id}:${item.key}`);return !(state?.status==="done"||state?.status==="dismissed"||(state?.status==="snoozed"&&state.snoozed_until&&new Date(state.snoozed_until).getTime()>now))}).length}});
 actions.sort((a,b)=>b.score-a.score||new Date(a.dueAt||"2999-01-01").getTime()-new Date(b.dueAt||"2999-01-01").getTime());
 const profiles=profilesResult.data??[];const owners=new Map<string,any>();for(const account of accounts){const owner=account.owner||account.commercial_owner||"Non assigné";const current=owners.get(owner)||{ownerName:owner,accounts:0,strategic:0,atRisk:0,weeklyLoad:0,configuredCapacity:null};current.accounts+=1;current.strategic+=account.portfolio_tier==="strategic"?1:0;current.atRisk+=["at_risk","critical"].includes(account.health_status)||["at_risk","critical"].includes(account.governance_status)?1:0;current.weeklyLoad+=account.weeklyEffort;owners.set(owner,current)}
 for(const profile of profiles){const current=owners.get(profile.owner_name)||{ownerName:profile.owner_name,accounts:0,strategic:0,atRisk:0,weeklyLoad:0,configuredCapacity:null};current.configuredCapacity=profile.active?Number(profile.weekly_capacity_hours):null;current.profileId=profile.id;current.notes=profile.notes;current.active=profile.active;owners.set(profile.owner_name,current)}
 const capacity=[...owners.values()].map((row:any)=>({...row,weeklyLoad:Math.round(row.weeklyLoad*10)/10,utilization:row.configuredCapacity?Math.round(row.weeklyLoad/row.configuredCapacity*100):null})).sort((a:any,b:any)=>(b.utilization??-1)-(a.utilization??-1)||b.atRisk-a.atRisk);
 const metrics={active:accounts.length,strategic:accounts.filter((row:any)=>row.portfolio_tier==="strategic").length,attention:accounts.filter((row:any)=>["at_risk","critical"].includes(row.health_status)||["at_risk","critical"].includes(row.governance_status)).length,renewals60:accounts.filter((row:any)=>{const days=daysUntil(row.renewal_date);return days!=null&&days<=60}).length,unassigned:accounts.filter((row:any)=>!row.owner).length,openActions:actions.length};
 return{available:true,accounts,capacity,actions,metrics,effortDefaults:{strategic:6,growth:4,standard:2,light_touch:1}};
}

export async function GET(request:Request){const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;try{return NextResponse.json(await loadPortfolio(supabase))}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Erreur portefeuille Customer Success."},{status:500})}}

export async function POST(request:Request){
 const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;const body=await bodyOf(request);if(!body)return NextResponse.json({error:"Requête invalide."},{status:400});const action=asText(body.action,50),who=actor(session),now=new Date().toISOString();
 if(action==="account_profile"){
  const clientId=asText(body.clientId,80),tier=asText(body.portfolioTier,30)||"standard";if(!clientId||!["strategic","growth","standard","light_touch"].includes(tier))return NextResponse.json({error:"Compte ou niveau de portefeuille invalide."},{status:422});const effort=body.serviceEffortHoursMonthly===""||body.serviceEffortHoursMonthly==null?null:Number(body.serviceEffortHoursMonthly);if(effort!=null&&(!Number.isFinite(effort)||effort<0||effort>500))return NextResponse.json({error:"Charge mensuelle invalide."},{status:422});const update=await supabase.from("website_crm_client_accounts").update({portfolio_tier:tier,service_effort_hours_monthly:effort,portfolio_notes:nullable(body.portfolioNotes),portfolio_updated_at:now,portfolio_updated_by:who,updated_at:now}).eq("id",clientId).select("id,account_name").single();if(update.error)return NextResponse.json({error:update.error.message},{status:500});await writeAuditLog(supabase,session,"crm.portfolio_account_updated","crm_client_account",clientId,`${update.data.account_name} · ${tier}`,{serviceEffortHoursMonthly:effort});return NextResponse.json({ok:true});
 }
 if(action==="capacity_profile"){
  const ownerName=asText(body.ownerName,240),capacity=Number(body.weeklyCapacityHours);if(!ownerName||!Number.isFinite(capacity)||capacity<=0||capacity>168)return NextResponse.json({error:"Responsable et capacité hebdomadaire valide obligatoires."},{status:422});const saved=await supabase.from("website_crm_csm_capacity_profiles").upsert({owner_name:ownerName,weekly_capacity_hours:capacity,active:body.active!==false,notes:nullable(body.notes),created_by:who,updated_by:who,updated_at:now},{onConflict:"owner_name"}).select("*").single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});await writeAuditLog(supabase,session,"crm.portfolio_capacity_saved","crm_csm_capacity",saved.data.id,`${ownerName} · ${capacity} h/semaine`,{});return NextResponse.json({profile:saved.data});
 }
 if(action==="capacity_delete"){
  const ownerName=asText(body.ownerName,240);if(!ownerName)return NextResponse.json({error:"Responsable obligatoire."},{status:422});const removed=await supabase.from("website_crm_csm_capacity_profiles").delete().eq("owner_name",ownerName);if(removed.error)return NextResponse.json({error:removed.error.message},{status:500});await writeAuditLog(supabase,session,"crm.portfolio_capacity_deleted","crm_csm_capacity",ownerName,`Capacité supprimée · ${ownerName}`,{});return NextResponse.json({ok:true});
 }
 if(action==="action_state"){
  const clientId=asText(body.clientId,80),actionKey=asText(body.actionKey,500),status=asText(body.status,30);if(!clientId||!actionKey||!["open","done","snoozed","dismissed"].includes(status))return NextResponse.json({error:"Action portefeuille invalide."},{status:422});const snoozedUntil=status==="snoozed"?(isoOrNull(body.snoozedUntil)||new Date(Date.now()+7*86400000).toISOString()):null;const saved=await supabase.from("website_crm_portfolio_action_states").upsert({client_id:clientId,action_key:actionKey,status,snoozed_until:snoozedUntil,note:nullable(body.note,2000),updated_by:who,updated_at:now},{onConflict:"client_id,action_key"}).select("id").single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});await writeAuditLog(supabase,session,"crm.portfolio_action_state","crm_portfolio_action",saved.data.id,`${actionKey} · ${status}`,{clientId,snoozedUntil});return NextResponse.json({ok:true});
 }
 if(action==="create_task"){
  const clientId=asText(body.clientId,80),actionKey=asText(body.actionKey,500),title=asText(body.title,320),priority=asText(body.priority,30);if(!clientId||!actionKey||!title||!["urgent","high","medium","normal"].includes(priority))return NextResponse.json({error:"Action portefeuille invalide."},{status:422});const account=await supabase.from("website_crm_client_accounts").select("id,lead_id,account_name,owner,commercial_owner").eq("id",clientId).maybeSingle();if(account.error||!account.data)return NextResponse.json({error:"Compte client introuvable."},{status:404});const dueAt=isoOrNull(body.dueAt)||new Date(Date.now()+3*86400000).toISOString();const taskPriority=priority==="urgent"?"urgent":priority==="high"?"high":"normal";const task=await supabase.from("website_crm_tasks").insert({lead_id:account.data.lead_id,title,due_at:dueAt,status:"todo",priority:taskPriority,assigned_to:account.data.owner||account.data.commercial_owner||"Customer Success",notes:nullable(body.reason,4000)||"Action recommandée depuis le portefeuille Customer Success.",metadata:{source:"crm-executive-portfolio",client_id:clientId,action_key:actionKey}}).select("id").single();if(task.error)return NextResponse.json({error:task.error.message},{status:500});await supabase.from("website_crm_portfolio_action_states").upsert({client_id:clientId,action_key:actionKey,status:"done",note:`Tâche CRM créée: ${task.data.id}`,updated_by:who,updated_at:now},{onConflict:"client_id,action_key"});await writeAuditLog(supabase,session,"crm.portfolio_task_created","crm_task",task.data.id,`${account.data.account_name} · ${title}`,{clientId,actionKey,dueAt});return NextResponse.json({taskId:task.data.id});
 }
 return NextResponse.json({error:"Action non prise en charge."},{status:422});
}
