"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Item={name:string;value:number};
type Data={rangeDays:number;metrics:{pageViews:number;appClicks:number;ctaClicks:number;leads:number;newsletterSignups:number;conversionRate:number};daily:{date:string;views:number}[];topPages:Item[];countries:Item[];cities:Item[];devices:Item[];sources:Item[]};
const empty:Data={rangeDays:30,metrics:{pageViews:0,appClicks:0,ctaClicks:0,leads:0,newsletterSignups:0,conversionRate:0},daily:[],topPages:[],countries:[],cities:[],devices:[],sources:[]};

function Bars({items,total}:{items:Item[];total:number}){return <div className="space-y-3 text-sm">{items.length?items.map(item=><div key={item.name}><div className="flex justify-between gap-3"><span className="truncate">{item.name}</span><strong>{item.value}</strong></div><div className="mt-1 h-2 rounded-full bg-[#f2e6de]"><div className="h-2 rounded-full bg-[#9d4c27]" style={{width:`${total?Math.max(4,(item.value/total)*100):0}%`}}/></div></div>):<p className="py-6 text-center text-xs text-[#5b2f22]/45">Pas encore assez de données.</p>}</div>}

export default function AnalyticsPage(){
 const [days,setDays]=useState(30);const [data,setData]=useState<Data>(empty);const [loading,setLoading]=useState(true);
 async function load(next=days){setLoading(true);const r=await fetch(`/api/admin/analytics?days=${next}`,{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();if(r.ok)setData(d);setLoading(false)}
 useEffect(()=>{void load(days)},[days]);
 const points=useMemo(()=>{if(!data.daily.length)return"";const max=Math.max(1,...data.daily.map(x=>x.views));return data.daily.map((x,i)=>`${(i/Math.max(1,data.daily.length-1))*800},${230-(x.views/max)*190}`).join(" ")},[data.daily]);
 const views=data.metrics.pageViews;
 return <AdminWorkspace active="Analytique" title="Performance & Système" subtitle="Mesurez les performances du site avec des données first-party agrégées, sans profiler les visiteuses." actions={<select value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><option value={7}>7 derniers jours</option><option value={30}>30 derniers jours</option><option value={90}>90 derniers jours</option><option value={365}>12 derniers mois</option></select>}>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Pages vues",data.metrics.pageViews],["Clics application",data.metrics.appClicks],["Leads",data.metrics.leads],["Abonnements newsletter",data.metrics.newsletterSignups],["Taux de conversion",`${data.metrics.conversionRate}%`]].map(([l,v])=><div key={String(l)} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/45">{l}</p><p className="moony-serif mt-2 text-4xl">{loading?"…":v}</p></div>)}</div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><AdminCard title="Évolution des pages vues"><div className="h-72 rounded-lg border border-[#5b2f22]/8 bg-white p-4"><svg viewBox="0 0 800 260" className="h-full w-full" preserveAspectRatio="none">{[40,80,120,160,200].map(y=><line key={y} x1="0" x2="800" y1={y} y2={y} stroke="#eadfd8"/>)}<polyline fill="none" stroke="#8a3d20" strokeWidth="4" vectorEffect="non-scaling-stroke" points={points}/></svg><div className="mt-1 flex justify-between text-[10px] text-[#5b2f22]/40"><span>{data.daily[0]?.date??""}</span><span>{data.daily.at(-1)?.date??""}</span></div></div></AdminCard><AdminCard title="Sources de trafic"><Bars items={data.sources} total={views}/></AdminCard></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-4"><AdminCard title="Pages les plus vues"><Bars items={data.topPages} total={views}/></AdminCard><AdminCard title="Pays"><Bars items={data.countries} total={views}/><p className="mt-4 text-[10px] leading-4 text-[#5b2f22]/40">La localisation n’est renseignée que lorsque l’hébergeur fournit une donnée géographique approximative.</p></AdminCard><AdminCard title="Appareils"><Bars items={data.devices} total={views}/></AdminCard><AdminCard title="Conversions"><div className="space-y-4 text-sm"><div className="flex justify-between"><span>Clics CTA</span><strong>{data.metrics.ctaClicks}</strong></div><div className="flex justify-between"><span>Clics application</span><strong>{data.metrics.appClicks}</strong></div><div className="flex justify-between"><span>Leads commerciaux</span><strong>{data.metrics.leads}</strong></div><div className="flex justify-between"><span>Newsletters</span><strong>{data.metrics.newsletterSignups}</strong></div><div className="border-t border-[#5b2f22]/10 pt-4"><span className="text-xs text-[#5b2f22]/45">Conversion globale</span><p className="moony-serif mt-1 text-4xl">{data.metrics.conversionRate}%</p></div></div></AdminCard></div>
 </AdminWorkspace>;
}
