"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Clock3 } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";

type Status="new"|"to_contact"|"contacted"|"appointment"|"proposal"|"negotiation"|"won"|"lost";
type Lead={id:string;first_name:string;last_name:string;email:string;company:string|null;status:Status;deal_value:number|null;country:string|null;need:string;assigned_to:string|null};
type TaskLead={first_name:string;last_name:string;company:string|null};
type Task={id:string;lead_id:string;title:string;due_at:string|null;status:"todo"|"in_progress";priority:"low"|"normal"|"high"|"urgent";assigned_to:string|null;website_leads?:TaskLead|TaskLead[]|null};
type Dashboard={metrics:{pageViews:number;appClicks:number;leads30d:number;appointments30d:number;conversionRate:number};daily:{date:string;views:number}[];countries:{name:string;value:number}[];leads:Lead[];upcomingAppointments:{id:string;starts_at:string|null;status:string;provider:string|null;notes:string|null;lead_id:string|null}[];tasks:Task[];tasksAvailable:boolean;tickets:{id:string;requester_name:string|null;requester_email:string;type:string;subject:string;priority:string;status:string}[];campaigns:{id:string;name:string;subject:string;status:string;stats:Record<string,unknown>}[];partners:{id:string;name:string;status:string;featured:boolean}[];testimonials:{id:string;author_name:string;status:string;featured:boolean}[]};
const empty:Dashboard={metrics:{pageViews:0,appClicks:0,leads30d:0,appointments30d:0,conversionRate:0},daily:[],countries:[],leads:[],upcomingAppointments:[],tasks:[],tasksAvailable:true,tickets:[],campaigns:[],partners:[],testimonials:[]};
const stages:[Status,string][]=[["new","Nouveau"],["to_contact","À contacter"],["contacted","Contacté"],["appointment","RDV planifié"],["proposal","Proposition envoyée"],["negotiation","Négociation"],["won","Signé"],["lost","Perdu"]];
function money(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value)}
function taskLead(task:Task){const relation=task.website_leads;return Array.isArray(relation)?relation[0]:relation??null}
function taskDate(value:string|null){if(!value)return"Sans échéance";return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}

export default function AdminDashboard(){
 const [data,setData]=useState<Dashboard>(empty);const [loading,setLoading]=useState(true);
 useEffect(()=>{void (async()=>{const r=await fetch("/api/admin/dashboard",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();if(r.ok)setData({...empty,...d,tasks:d.tasks??[],tasksAvailable:d.tasksAvailable??true});setLoading(false)})()},[]);
 const points=useMemo(()=>{if(!data.daily.length)return"";const max=Math.max(1,...data.daily.map(x=>x.views));return data.daily.map((x,i)=>`${(i/Math.max(1,data.daily.length-1))*800},${225-(x.views/max)*185}`).join(" ")},[data.daily]);
 const countryTotal=data.countries.reduce((s,x)=>s+x.value,0);
 const overdue=data.tasks.filter(task=>task.due_at&&new Date(task.due_at).getTime()<Date.now());
 return <AdminShell active="Dashboard"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="moony-serif text-4xl tracking-[-.035em] text-[#5b2f22]">Bonjour Aïssata ☀</h1><p className="mt-1 text-sm text-[#5b2f22]/50">Voici ce qui se passe réellement sur le site et dans votre activité commerciale.</p></div><div className="flex gap-2"><Link href="/admin/analytics" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Voir l’analytique</Link><Link href="/admin/crm" className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm font-medium text-white">+ Ajouter un lead</Link></div></div>

 <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Pages vues",data.metrics.pageViews],["Clics application",data.metrics.appClicks],["Leads générés",data.metrics.leads30d],["RDV créés",data.metrics.appointments30d],["Taux de conversion",`${data.metrics.conversionRate}%`]].map(([label,value])=><article key={String(label)} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/52">{label}</p><strong className="moony-serif mt-3 block text-3xl font-normal">{loading?"…":value}</strong><p className="mt-1 text-[10px] text-[#5b2f22]/36">30 derniers jours</p></article>)}</div>

 <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.75fr]"><article className="admin-card admin-shadow p-5"><div className="flex items-center justify-between"><div><h2 className="moony-serif text-2xl">Performance du site</h2><p className="text-xs text-[#5b2f22]/45">Pages vues · 30 jours</p></div><Link href="/admin/analytics" className="text-xs text-[#8d3b19]">Voir les détails →</Link></div><div className="mt-5 h-64 rounded-lg border border-[#5b2f22]/8 bg-[#fffdf9] p-4"><svg viewBox="0 0 800 250" className="h-full w-full" preserveAspectRatio="none">{[40,80,120,160,200].map(y=><line key={y} x1="0" x2="800" y1={y} y2={y} stroke="#eadfd8"/>)}<polyline fill="none" stroke="#8a3d20" strokeWidth="4" vectorEffect="non-scaling-stroke" points={points}/></svg></div></article><article className="admin-card admin-shadow p-5"><div className="flex items-center justify-between"><h2 className="moony-serif text-2xl">Audience par pays</h2><Link href="/admin/analytics" className="text-xs text-[#8d3b19]">Voir tout</Link></div><div className="mt-5 space-y-3">{data.countries.length?data.countries.map(item=><div key={item.name}><div className="flex justify-between text-xs"><span>{item.name}</span><strong>{countryTotal?Math.round(item.value/countryTotal*100):0}%</strong></div><div className="mt-1 h-2 rounded-full bg-[#f2e6de]"><div className="h-2 rounded-full bg-[#9d4c27]" style={{width:`${countryTotal?item.value/countryTotal*100:0}%`}}/></div></div>):<p className="py-12 text-center text-xs text-[#5b2f22]/42">Les pays apparaîtront dès que des visites seront enregistrées.</p>}</div></article></div>

 <div className="mt-4 grid gap-4 2xl:grid-cols-[1.45fr_.55fr]">
  <article className="admin-card admin-shadow p-4"><div className="mb-3 flex items-center justify-between"><h2 className="moony-serif text-2xl">Pipeline commercial</h2><Link href="/admin/crm" className="text-xs text-[#8d3b19]">Ouvrir le CRM →</Link></div><div className="flex gap-2 overflow-x-auto pb-2">{stages.map(([status,label],index)=>{const rows=data.leads.filter(x=>x.status===status);const total=rows.reduce((s,x)=>s+Number(x.deal_value||0),0);return <div key={status} className={`min-w-[180px] flex-1 rounded-xl p-3 ${index===6?"bg-[#e4f3e8]":index===7?"bg-[#f8e4e2]":index>=3?"bg-[#fbf0dd]":"bg-[#f7eee8]"}`}><p className="text-xs font-semibold">{label} <span className="font-normal text-[#5b2f22]/40">({rows.length})</span></p><strong className="moony-serif mt-1 block text-xl font-normal">{money(total)}</strong><div className="mt-3 space-y-2">{rows.slice(0,3).map(lead=><Link href={`/admin/crm?lead=${lead.id}`} key={lead.id} className="block rounded-lg bg-white px-3 py-2 text-[11px] shadow-sm transition hover:-translate-y-[1px]"><strong className="block truncate">{lead.company||`${lead.first_name} ${lead.last_name}`}</strong><span className="text-[#5b2f22]/45">{lead.country||"Pays non renseigné"}</span></Link>)}</div></div>})}</div></article>

  <article className="admin-card admin-shadow p-4"><div className="flex items-center justify-between"><div><h2 className="moony-serif text-2xl">Relances commerciales</h2><p className="mt-0.5 text-[10px] text-[#5b2f22]/42">{overdue.length} en retard</p></div><Link href="/admin/crm" className="text-xs text-[#8d3b19]">CRM →</Link></div>{!data.tasksAvailable?<div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[11px] leading-5 text-amber-800">Appliquez la dernière migration Supabase pour activer les tâches commerciales.</div>:null}<div className="mt-4 space-y-2">{data.tasks.length?data.tasks.slice(0,6).map(task=>{const lead=taskLead(task);const late=Boolean(task.due_at&&new Date(task.due_at).getTime()<Date.now());return <Link key={task.id} href={`/admin/crm?lead=${task.lead_id}`} className={`block rounded-xl border p-3 transition hover:bg-[#fffaf6] ${late?"border-red-200 bg-red-50/45":"border-[#5b2f22]/9 bg-white"}`}><div className="flex items-start gap-2">{late?<AlertCircle size={14} className="mt-0.5 shrink-0 text-red-500"/>:<Clock3 size={14} className="mt-0.5 shrink-0 text-[#9d4c27]"/>}<div className="min-w-0"><strong className="block truncate text-xs">{task.title}</strong><span className={`mt-1 block text-[10px] ${late?"text-red-600":"text-[#5b2f22]/42"}`}>{taskDate(task.due_at)}</span><span className="mt-1 block truncate text-[10px] text-[#5b2f22]/42">{lead?.company||lead?`${lead.first_name} ${lead.last_name}`:"Prospect"}{task.assigned_to?` · ${task.assigned_to}`:""}</span></div></div></Link>}):<div className="py-8 text-center"><CheckCircle2 size={28} className="mx-auto text-emerald-500/60"/><p className="mt-2 text-xs text-[#5b2f22]/42">Aucune relance commerciale ouverte.</p></div>}</div></article>
 </div>

 <div className="mt-4 grid gap-4 xl:grid-cols-4"><article className="admin-card admin-shadow p-4"><div className="flex items-center justify-between"><h3 className="moony-serif text-xl">Prochains rendez-vous</h3><Link href="/admin/rendez-vous" className="text-[10px] text-[#8d3b19]">Voir tous</Link></div><div className="mt-3 space-y-2">{data.upcomingAppointments.length?data.upcomingAppointments.slice(0,4).map(x=><Link href={x.lead_id?`/admin/crm?lead=${x.lead_id}`:"/admin/rendez-vous"} key={x.id} className="block border-b border-[#5b2f22]/8 pb-2 text-[11px]"><strong className="block">{x.starts_at?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x.starts_at)):"Date à préciser"}</strong><span className="text-[#5b2f22]/45">{x.provider||x.notes||"Rendez-vous commercial"}</span></Link>):<p className="py-6 text-xs text-[#5b2f22]/40">Aucun rendez-vous à venir.</p>}</div></article>
 <article className="admin-card admin-shadow p-4"><div className="flex items-center justify-between"><h3 className="moony-serif text-xl">Service client</h3><Link href="/admin/service-client" className="text-[10px] text-[#8d3b19]">Ouvrir</Link></div><div className="mt-3 space-y-2">{data.tickets.slice(0,4).map(x=><Link href={`/admin/service-client?ticket=${x.id}`} key={x.id} className="block border-b border-[#5b2f22]/8 pb-2 text-[11px]"><strong className="block truncate">{x.subject}</strong><span className="text-[#5b2f22]/45">{x.requester_name||x.requester_email} · {x.status}</span></Link>)}</div></article>
 <article className="admin-card admin-shadow p-4"><div className="flex items-center justify-between"><h3 className="moony-serif text-xl">Newsletters</h3><Link href="/admin/newsletters" className="text-[10px] text-[#8d3b19]">Voir toutes</Link></div><div className="mt-3 space-y-2">{data.campaigns.slice(0,4).map(x=><Link href="/admin/newsletters" key={x.id} className="block border-b border-[#5b2f22]/8 pb-2 text-[11px]"><strong className="block truncate">{x.name}</strong><span className="text-[#5b2f22]/45">{x.status}</span></Link>)}{!data.campaigns.length?<p className="py-6 text-xs text-[#5b2f22]/40">Aucune campagne.</p>:null}</div></article>
 <article className="admin-card admin-shadow p-4"><div className="flex items-center justify-between"><h3 className="moony-serif text-xl">Marque & confiance</h3><Link href="/admin/partenaires" className="text-[10px] text-[#8d3b19]">Gérer</Link></div><div className="mt-4 grid grid-cols-2 gap-3 text-center"><div className="rounded-lg bg-[#f7eee8] p-3"><strong className="moony-serif block text-3xl font-normal">{data.partners.filter(x=>x.status==="published").length}</strong><span className="text-[10px] text-[#5b2f22]/45">partenaires publiés</span></div><div className="rounded-lg bg-[#f7eee8] p-3"><strong className="moony-serif block text-3xl font-normal">{data.testimonials.filter(x=>x.status==="approved").length}</strong><span className="text-[10px] text-[#5b2f22]/45">avis approuvés</span></div></div><Link href="/avis" target="_blank" className="mt-3 block text-center text-[10px] text-[#8d3b19]">Ouvrir le formulaire d’avis ↗</Link></article></div>
 </AdminShell>;
}
