"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, Globe2, SearchCheck, TriangleAlert } from "lucide-react";
import { AdminMediaPicker } from "@/components/admin-media-picker";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type PageMetadata={canonicalUrl?:string;noIndex?:boolean;ogImageUrl?:string;ogTitle?:string;ogDescription?:string};
type Page={id:string;title:string;slug:string;status:string;seo_title:string|null;seo_description:string|null;metadata?:PageMetadata;updated_at?:string};
type SeoSettings={siteTitle:string;titleTemplate:string;defaultDescription:string;defaultOgImage:string;defaultLocale:string;allowIndexing:boolean;organizationName:string};
type GeneralSettings={publicUrl:string};

const defaultSeo:SeoSettings={siteTitle:"MOONY Africa — Pour la santé des femmes, à chaque étape de leur vie",titleTemplate:"%s | MOONY Africa",defaultDescription:"MOONY Africa accompagne la santé des femmes avec une approche humaine, scientifique, accessible et ancrée dans les réalités du continent africain.",defaultOgImage:"",defaultLocale:"fr_FR",allowIndexing:true,organizationName:"MOONY Africa"};

function audit(page:Page){
 const title=(page.seo_title??"").trim();const description=(page.seo_description??"").trim();const metadata=page.metadata??{};
 const checks=[
  {label:"Meta title",ok:title.length>=30&&title.length<=65,weight:22,detail:title?`${title.length} caractères`:"Manquant"},
  {label:"Meta description",ok:description.length>=110&&description.length<=170,weight:22,detail:description?`${description.length} caractères`:"Manquante"},
  {label:"URL propre",ok:page.slug==="/"||(/^\/[a-z0-9-]+(?:\/[a-z0-9-]+)*$/.test(page.slug)),weight:14,detail:page.slug},
  {label:"Image sociale",ok:Boolean(metadata.ogImageUrl),weight:14,detail:metadata.ogImageUrl?"Personnalisée":"Utilise le défaut global"},
  {label:"Canonique",ok:Boolean(metadata.canonicalUrl||page.slug),weight:12,detail:metadata.canonicalUrl||page.slug},
  {label:"Page publiée",ok:page.status==="published",weight:16,detail:page.status==="published"?"Publiée":"Non publiée"},
 ];
 const score=Math.min(100,checks.reduce((sum,item)=>sum+(item.ok?item.weight:0),0));
 return{score,checks};
}
function scoreTone(score:number){return score>=85?"bg-emerald-100 text-emerald-800":score>=70?"bg-amber-100 text-amber-800":"bg-red-100 text-red-700"}

export default function SeoPage(){
 const [pages,setPages]=useState<Page[]>([]);const [selected,setSelected]=useState<Page|null>(null);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [metadata,setMetadata]=useState<PageMetadata>({});const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [seo,setSeo]=useState<SeoSettings>(defaultSeo);const [general,setGeneral]=useState<GeneralSettings>({publicUrl:"https://www.moonyafrica.com"});
 async function load(){setLoading(true);const [pagesResponse,settingsResponse]=await Promise.all([fetch("/api/admin/pages",{cache:"no-store"}),fetch("/api/admin/settings",{cache:"no-store"})]);if(pagesResponse.status===401||settingsResponse.status===401){location.href="/admin/login";return;}const [pageData,settingsData]=await Promise.all([pagesResponse.json(),settingsResponse.json()]);const list=(pageData.pages??[]) as Page[];setPages(list);setSeo({...defaultSeo,...(settingsData.settings?.seo??{})});setGeneral({publicUrl:settingsData.settings?.general?.publicUrl||"https://www.moonyafrica.com"});const target=(selected?list.find(item=>item.id===selected.id):null)??list[0]??null;if(target)choose(target);setLoading(false)}
 useEffect(()=>{void load()},[]);
 function choose(page:Page){setSelected(page);setTitle(page.seo_title??"");setDescription(page.seo_description??"");setMetadata(page.metadata??{});setMessage("");}
 async function save(){if(!selected)return;setMessage("Enregistrement…");const r=await fetch("/api/admin/pages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,seoTitle:title,seoDescription:description,metadata})});const d=await r.json();if(!r.ok){setMessage(d.error??"Erreur");return;}setMessage("SEO enregistré.");await load();if(d.page)choose(d.page)}
 const average=useMemo(()=>pages.length?Math.round(pages.reduce((sum,p)=>sum+audit(p).score,0)/pages.length):0,[pages]);
 const alerts=useMemo(()=>pages.filter(p=>audit(p).score<70).length,[pages]);
 const selectedAudit=selected?audit({...selected,seo_title:title,seo_description:description,metadata}):null;
 const canonicalPreview=metadata.canonicalUrl?.trim()||selected?.slug||"/";
 const socialTitle=metadata.ogTitle?.trim()||title||selected?.title||seo.siteTitle;
 const socialDescription=metadata.ogDescription?.trim()||description||seo.defaultDescription;
 const socialImage=metadata.ogImageUrl?.trim()||seo.defaultOgImage;
 const base=general.publicUrl.replace(/\/$/,"");

 return <AdminWorkspace active="SEO" title="SEO" subtitle="Pilotez le référencement naturel, les aperçus Google et sociaux, les canonicals et l’indexation de chaque page." actions={<><button onClick={()=>void load()} className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Analyser le site</button><Link href="/admin/parametres#seo" className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Réglages SEO globaux</Link></>}>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Score SEO moyen",`${average}/100`],["Pages publiées",String(pages.filter(p=>p.status==="published").length)],["Alertes prioritaires",String(alerts)],["Indexation globale",seo.allowIndexing?"Active":"Désactivée"]].map(([l,v])=><div key={l} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/45">{l}</p><p className="moony-serif mt-2 text-4xl">{loading?"…":v}</p></div>)}</div>

  <div className="mt-4 grid gap-4 xl:grid-cols-3"><AdminCard title="Santé technique"><div className="space-y-3 text-sm"><div className="flex items-center gap-3 rounded-xl bg-[#eef6ef] p-3"><CheckCircle2 size={17} className="text-emerald-700"/><div><strong className="block text-xs">Sitemap dynamique</strong><span className="text-[11px] text-[#5b2f22]/50">{base}/sitemap.xml</span></div></div><div className="flex items-center gap-3 rounded-xl bg-[#eef6ef] p-3"><CheckCircle2 size={17} className="text-emerald-700"/><div><strong className="block text-xs">robots.txt configurable</strong><span className="text-[11px] text-[#5b2f22]/50">Admin et API exclus de l’indexation.</span></div></div><div className={`flex items-center gap-3 rounded-xl p-3 ${seo.defaultOgImage?"bg-[#eef6ef]":"bg-amber-50"}`}>{seo.defaultOgImage?<CheckCircle2 size={17} className="text-emerald-700"/>:<TriangleAlert size={17} className="text-amber-700"/>}<div><strong className="block text-xs">Image sociale par défaut</strong><span className="text-[11px] text-[#5b2f22]/50">{seo.defaultOgImage?"Configurée":"À ajouter dans Paramètres"}</span></div></div></div></AdminCard><div className="xl:col-span-2"><AdminCard title="Référencement global"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-[#f8eee7] p-4"><Globe2 size={18}/><p className="mt-3 text-xs text-[#5b2f22]/45">Domaine public</p><strong className="mt-1 block text-sm break-all">{base}</strong></div><div className="rounded-xl bg-[#f8eee7] p-4"><SearchCheck size={18}/><p className="mt-3 text-xs text-[#5b2f22]/45">Template des titres</p><strong className="mt-1 block text-sm">{seo.titleTemplate}</strong></div><div className="rounded-xl bg-[#f8eee7] p-4"><ExternalLink size={18}/><p className="mt-3 text-xs text-[#5b2f22]/45">Locale Open Graph</p><strong className="mt-1 block text-sm">{seo.defaultLocale}</strong></div></div></AdminCard></div></div>

  <div className="mt-4 grid gap-4 2xl:grid-cols-[1.05fr_.95fr]"><AdminCard title="Pages"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-[#5b2f22]/45"><tr><th className="pb-3">Page</th><th>URL</th><th>Score</th><th>Indexation</th><th>Meta title</th></tr></thead><tbody>{pages.map(p=>{const result=audit(p);return <tr key={p.id} onClick={()=>choose(p)} className={`cursor-pointer border-t border-[#5b2f22]/8 hover:bg-[#fbf2eb] ${selected?.id===p.id?"bg-[#f7e7dc]":""}`}><td className="py-3 font-medium">{p.title}</td><td>{p.slug}</td><td><span className={`rounded-full px-2 py-1 ${scoreTone(result.score)}`}>{result.score}</span></td><td>{p.status!=="published"?"Non publiée":p.metadata?.noIndex?"Noindex":"Indexable"}</td><td className="max-w-[220px] truncate">{p.seo_title||"—"}</td></tr>})}</tbody></table></div></AdminCard>

  <div className="space-y-4"><AdminCard title="Métadonnées de la page" action={selectedAudit?<span className={`rounded-full px-3 py-1 text-xs ${scoreTone(selectedAudit.score)}`}>{selectedAudit.score}/100</span>:null}>{selected?<div className="space-y-4 text-sm"><div className="rounded-lg bg-[#f8eee7] p-3 text-xs"><strong>{selected.title}</strong><p className="mt-1 text-[#5b2f22]/50">{selected.slug}</p></div><label className="block"><span className="mb-1 flex justify-between text-xs text-[#5b2f22]/45"><span>Meta title</span><span>{title.length}/65</span></span><input className="w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80}/></label><label className="block"><span className="mb-1 flex justify-between text-xs text-[#5b2f22]/45"><span>Meta description</span><span>{description.length}/170</span></span><textarea className="min-h-28 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3" value={description} onChange={e=>setDescription(e.target.value)} maxLength={220}/></label><label className="block"><span className="mb-1 block text-xs text-[#5b2f22]/45">URL canonique</span><input value={metadata.canonicalUrl??""} onChange={e=>setMetadata({...metadata,canonicalUrl:e.target.value})} placeholder={selected.slug} className="w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/><span className="mt-1 block text-[10px] text-[#5b2f22]/40">Laissez vide pour utiliser automatiquement l’URL de la page.</span></label><label className="flex items-start gap-3 rounded-xl border border-[#5b2f22]/10 bg-[#fffaf4] p-4"><input type="checkbox" checked={!!metadata.noIndex} onChange={e=>setMetadata({...metadata,noIndex:e.target.checked})} className="mt-0.5"/><span><strong className="block text-xs">Masquer cette page des moteurs de recherche</strong><span className="mt-1 block text-[10px] leading-4 text-[#5b2f22]/48">Ajoute noindex/no-follow à cette page sans la dépublier.</span></span></label><button onClick={save} className="w-full rounded-lg bg-[#7e3518] px-4 py-3 text-white">Enregistrer le SEO</button><p className="text-center text-xs text-[#5b2f22]/50">{message}</p></div>:<p className="text-sm text-[#5b2f22]/50">Sélectionnez une page.</p>}</AdminCard>

  {selected?<AdminCard title="Partage social"><div className="space-y-3"><label className="block text-xs">Titre social<input value={metadata.ogTitle??""} onChange={e=>setMetadata({...metadata,ogTitle:e.target.value})} placeholder={title||selected.title} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="block text-xs">Description sociale<textarea rows={3} value={metadata.ogDescription??""} onChange={e=>setMetadata({...metadata,ogDescription:e.target.value})} placeholder={description||seo.defaultDescription} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><div><span className="mb-1 block text-xs">Image Open Graph</span>{socialImage?<img src={socialImage} alt="Aperçu social" className="mb-2 h-40 w-full rounded-xl border border-[#5b2f22]/8 object-cover"/>:<div className="mb-2 grid h-28 place-items-center rounded-xl border border-dashed border-[#5b2f22]/14 text-xs text-[#5b2f22]/38">Aucune image sociale</div>}<div className="flex flex-wrap gap-2"><AdminMediaPicker value={metadata.ogImageUrl??""} label="Choisir une image" onSelect={asset=>setMetadata({...metadata,ogImageUrl:asset.url})}/>{metadata.ogImageUrl?<button onClick={()=>setMetadata({...metadata,ogImageUrl:""})} className="rounded-lg border border-red-100 px-3 py-2.5 text-xs text-red-600">Utiliser le défaut</button>:null}</div></div><div className="overflow-hidden rounded-xl border border-[#5b2f22]/10 bg-white"><div className="h-40 bg-[#efe8e2] bg-cover bg-center" style={socialImage?{backgroundImage:`url(${socialImage})`}:undefined}/><div className="p-4"><p className="text-[10px] uppercase text-[#5b2f22]/40">{base.replace(/^https?:\/\//,"")}</p><p className="mt-1 font-semibold">{socialTitle}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#5b2f22]/55">{socialDescription}</p></div></div></div></AdminCard>:null}
  </div></div>

  {selected?<div className="mt-4 grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><AdminCard title="Checklist SEO">{selectedAudit?<div className="space-y-2">{selectedAudit.checks.map(item=><div key={item.label} className="flex items-center justify-between gap-4 rounded-lg border border-[#5b2f22]/8 bg-white px-3 py-2.5 text-xs"><span className="flex items-center gap-2">{item.ok?<CheckCircle2 size={14} className="text-emerald-700"/>:<TriangleAlert size={14} className="text-amber-700"/>}<strong>{item.label}</strong></span><span className="max-w-[55%] truncate text-[#5b2f22]/45">{item.detail}</span></div>)}</div>:null}</AdminCard><AdminCard title="Aperçu Google"><div className="rounded-xl border border-[#5b2f22]/10 bg-white p-5"><p className="text-[11px] text-emerald-700">{base}{canonicalPreview==="/"?"":canonicalPreview}</p><p className="mt-1 text-[20px] text-blue-700">{title||selected.title}</p><p className="mt-1 max-w-[760px] text-sm leading-5 text-[#5b2f22]/60">{description||"Ajoutez une meta description claire pour améliorer l’aperçu dans les résultats de recherche."}</p></div></AdminCard></div>:null}
 </AdminWorkspace>;
}
