"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Page={id:string;title:string;slug:string;status:string;seo_title:string|null;seo_description:string|null};
function score(page:Page){let s=55;if(page.status==="published")s+=10;if(page.seo_title?.length&&page.seo_title.length>=25&&page.seo_title.length<=65)s+=18;if(page.seo_description?.length&&page.seo_description.length>=90&&page.seo_description.length<=170)s+=17;return Math.min(100,s)}

export default function SeoPage(){
 const [pages,setPages]=useState<Page[]>([]);const [selected,setSelected]=useState<Page|null>(null);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/pages",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();const list=d.pages??[];setPages(list);if(!selected&&list.length)choose(list[0]);}
 useEffect(()=>{void load()},[]);
 function choose(page:Page){setSelected(page);setTitle(page.seo_title??"");setDescription(page.seo_description??"");setMessage("");}
 async function save(){if(!selected)return;setMessage("Enregistrement…");const r=await fetch("/api/admin/pages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,seoTitle:title,seoDescription:description})});const d=await r.json();if(!r.ok){setMessage(d.error??"Erreur");return;}setMessage("Métadonnées enregistrées.");await load();if(d.page)choose(d.page)}
 const average=useMemo(()=>pages.length?Math.round(pages.reduce((sum,p)=>sum+score(p),0)/pages.length):0,[pages]);const alerts=useMemo(()=>pages.filter(p=>score(p)<80).length,[pages]);
 return <AdminWorkspace active="SEO" title="SEO" subtitle="Pilotez le référencement naturel, les métadonnées et l’indexation de chaque page." actions={<button onClick={()=>void load()} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Analyser le site</button>}>
 <div className="grid gap-4 sm:grid-cols-3">{[["Score SEO moyen",`${average}/100`],["Pages publiées",String(pages.filter(p=>p.status==="published").length)],["Alertes actives",String(alerts)]].map(([l,v])=><div key={l} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/45">{l}</p><p className="moony-serif mt-2 text-4xl">{v}</p></div>)}</div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><AdminCard title="Pages"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-[#5b2f22]/45"><tr><th className="pb-3">Page</th><th>URL</th><th>Score</th><th>Indexation</th><th></th></tr></thead><tbody>{pages.map(p=><tr key={p.id} onClick={()=>choose(p)} className={`cursor-pointer border-t border-[#5b2f22]/8 hover:bg-[#fbf2eb] ${selected?.id===p.id?"bg-[#f7e7dc]":""}`}><td className="py-3 font-medium">{p.title}</td><td>{p.slug}</td><td><span className={`rounded-full px-2 py-1 ${score(p)>=85?"bg-emerald-100 text-emerald-800":score(p)>=70?"bg-amber-100 text-amber-800":"bg-red-100 text-red-700"}`}>{score(p)}</span></td><td>{p.status==="published"?"Indexable":"Non publiée"}</td><td className="text-right">Modifier</td></tr>)}</tbody></table></div></AdminCard>
 <AdminCard title="Métadonnées de la page">{selected?<div className="space-y-4 text-sm"><div className="rounded-lg bg-[#f8eee7] p-3 text-xs"><strong>{selected.title}</strong><p className="mt-1 text-[#5b2f22]/50">{selected.slug}</p></div><label className="block"><span className="mb-1 flex justify-between text-xs text-[#5b2f22]/45"><span>Meta title</span><span>{title.length}/65</span></span><input className="w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80}/></label><label className="block"><span className="mb-1 flex justify-between text-xs text-[#5b2f22]/45"><span>Meta description</span><span>{description.length}/170</span></span><textarea className="min-h-28 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3" value={description} onChange={e=>setDescription(e.target.value)} maxLength={220}/></label><div className="rounded-xl border border-[#5b2f22]/10 bg-white p-4"><p className="text-[11px] text-emerald-700">{title||selected.title}</p><p className="mt-1 text-lg text-blue-700">{title||selected.title}</p><p className="mt-1 text-xs leading-5 text-[#5b2f22]/55">{description||"Ajoutez une description pour améliorer l’aperçu dans les moteurs de recherche."}</p></div><button onClick={save} className="w-full rounded-lg bg-[#7e3518] px-4 py-3 text-white">Enregistrer</button><p className="text-center text-xs text-[#5b2f22]/50">{message}</p></div>:<p className="text-sm text-[#5b2f22]/50">Sélectionnez une page.</p>}</AdminCard></div>
 </AdminWorkspace>;
}
