"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BadgeCheck, CheckCircle2, FileCheck2, RefreshCw, Rocket, ShieldAlert } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Blocker={code:string;label:string;detail?:string|null;severity:"warning"|"critical"};
type Readiness={ready:boolean;percent:number;blockers:Blocker[];counts:{tasksDone:number;tasksRequired:number;documentsValidated:number;documentsRequired:number};contractSigned:boolean;kickoffConfirmed:boolean;ownerAssigned:boolean;targetDateSet:boolean};
type Lead={first_name:string;last_name:string;email:string;company:string|null;country:string|null};
type Opportunity={id:string;name:string;amount:number;currency:string;owner:string|null};
type CaseRow={id:string;lead_id:string;opportunity_id:string;status:string;owner:string|null;commercial_owner:string|null;target_go_live_date:string|null;kickoff_at:string|null;kickoff_response:string|null;readiness_status:string;readiness_checked_at:string|null;readiness_checked_by:string|null;readiness_notes:string|null;actual_go_live_at:string|null;website_leads:Lead|null;website_crm_opportunities:Opportunity|null};
type Task={id:string;title:string;status:string;required:boolean;template_key:string|null};
type DocumentRow={id:string;name:string;status:string;required:boolean;document_url:string|null};
type Contract={id:string;reference:string;version:number;status:string;signed_at:string|null;signed_by:string|null}|null;
type Item={case:CaseRow;tasks:Task[];documents:DocumentRow[];contract:Contract;clientAccount:any;readiness:Readiness};
type Payload={available:boolean;items:Item[];metrics:{pending:number;ready:number;blocked:number;live:number}};
const empty:Payload={available:true,items:[],metrics:{pending:0,ready:0,blocked:0,live:0}};
const labels:Record<string,string>={pending:"À préparer",ready:"Prêt à lancer",blocked:"Bloqué",live:"En service"};
const docLabels:Record<string,string>={required:"À fournir",requested:"Demandé",received:"Reçu",validated:"Validé",rejected:"À corriger",not_applicable:"Non applicable"};
function client(row:CaseRow){return row.website_leads?.company||`${row.website_leads?.first_name||""} ${row.website_leads?.last_name||""}`.trim()||row.website_leads?.email||"Client"}
function date(value:string|null){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(d)}

export default function ReadinessPage(){
 const [data,setData]=useState<Payload>(empty);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");const [selectedId,setSelectedId]=useState("");const [search,setSearch]=useState("");const [notes,setNotes]=useState("");
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/crm/onboarding/readiness",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Impossible de charger la readiness.");return}const next={...empty,...payload} as Payload;setData(next);const requested=new URLSearchParams(location.search).get("case");setSelectedId((current)=>current&&next.items.some((row)=>row.case.id===current)?current:requested&&next.items.some((row)=>row.case.id===requested)?requested:next.items[0]?.case.id||"")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>data.items.filter((row)=>[client(row.case),row.case.website_crm_opportunities?.name,row.case.owner,row.case.readiness_status].join(" ").toLowerCase().includes(search.toLowerCase())),[data.items,search]);
 const selected=data.items.find((row)=>row.case.id===selectedId)||null;
 async function action(actionName:string,extra:Record<string,unknown>={}){if(!selected)return;setBusy(actionName);setNotice("");try{const response=await fetch("/api/admin/crm/onboarding/readiness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:actionName,onboardingId:selected.case.id,notes,...extra})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Action impossible.");if(payload.readiness?.blockers?.length)setNotice(`${payload.error||"Action impossible."} ${payload.readiness.blockers.map((b:Blocker)=>b.label).join(" · ")}`);return}setNotes("");setNotice(actionName==="go_live"?"Client passé en production et ajouté au portefeuille Clients actifs.":actionName==="mark_ready"?"Dossier validé : prêt à lancer.":actionName==="block"?"Go-live bloqué.":actionName==="reopen"?"Readiness rouverte.":"Document mis à jour.");await load()}finally{setBusy("")}}
 async function reviewDocument(documentId:string,status:"validated"|"rejected"){await action("review_document",{documentId,status})}
 return <AdminWorkspace active="Readiness" title="Readiness & go-live" subtitle="Validez les prérequis opérationnels avant mise en service, bloquez ce qui doit l’être et transformez automatiquement un onboarding terminé en client actif." actions={<button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><RefreshCw size={15}/> Actualiser</button>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911074500_crm_onboarding_readiness_clients.sql</strong> pour activer CRM V7.2.</div>:null}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="admin-card admin-shadow p-5"><AlertTriangle size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{loading?"…":data.metrics.pending}</strong><span className="text-[10px] text-[#5b2f22]/45">À préparer</span></article><article className="admin-card admin-shadow p-5"><BadgeCheck size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.ready}</strong><span className="text-[10px] text-[#5b2f22]/45">Prêts à lancer</span></article><article className="admin-card admin-shadow p-5"><ShieldAlert size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.blocked}</strong><span className="text-[10px] text-[#5b2f22]/45">Bloqués</span></article><article className="admin-card admin-shadow p-5"><Rocket size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.live}</strong><span className="text-[10px] text-[#5b2f22]/45">En service</span></article></div>
  <div className="mt-5 grid gap-4 2xl:grid-cols-[.62fr_1.38fr]">
   <section className="admin-card admin-shadow overflow-hidden"><div className="border-b border-[#5b2f22]/8 p-4"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Rechercher client, deal, responsable…" className="w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs"/></div><div className="max-h-[1100px] divide-y divide-[#5b2f22]/7 overflow-auto">{visible.length?visible.map((row)=><button key={row.case.id} onClick={()=>setSelectedId(row.case.id)} className={`w-full p-4 text-left ${selectedId===row.case.id?"bg-[#f6e5d9]":"hover:bg-[#fffaf6]"}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{client(row.case)}</strong><p className="mt-1 text-[10px] text-[#5b2f22]/45">{row.case.website_crm_opportunities?.name||"Onboarding"}</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] text-[#7e3518]">{labels[row.case.readiness_status]||row.case.readiness_status}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eadfd6]"><div className="h-full bg-[#9d4c27]" style={{width:`${row.readiness.percent}%`}}/></div><p className="mt-2 text-[9px] text-[#5b2f22]/45">{row.readiness.percent}% · {row.readiness.blockers.length} prérequis restant{row.readiness.blockers.length>1?"s":""}</p></button>):<p className="p-10 text-center text-xs text-[#5b2f22]/40">Aucun dossier.</p>}</div></section>
   {selected?<div className="space-y-4"><AdminCard title="Décision go-live" action={<Link href={`/admin/onboarding?case=${selected.case.id}`} className="rounded-lg border border-[#5b2f22]/12 bg-white px-3 py-2 text-[10px]">Ouvrir l’onboarding</Link>}><div className="flex flex-wrap items-center gap-3"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#9d4c27]">{labels[selected.case.readiness_status]||selected.case.readiness_status}</p><h2 className="moony-serif mt-1 text-2xl">{client(selected.case)}</h2><p className="mt-1 text-[10px] text-[#5b2f22]/50">Ops : {selected.case.owner||"à assigner"} · cible : {date(selected.case.target_go_live_date)} · kickoff : {date(selected.case.kickoff_at)}</p></div><div className="ml-auto text-right"><strong className="moony-serif text-3xl font-normal">{selected.readiness.percent}%</strong><p className="text-[9px] text-[#5b2f22]/45">readiness</p></div></div><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} rows={2} placeholder="Note de validation, motif de blocage ou commentaire de mise en service…" className="mt-4 w-full rounded-xl border border-[#5b2f22]/10 px-3 py-2.5 text-xs"/><div className="mt-3 flex flex-wrap gap-2">{selected.case.readiness_status==="blocked"?<button onClick={()=>void action("reopen")} disabled={!!busy} className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2 text-xs">Rouvrir</button>:selected.case.readiness_status==="live"?<span className="inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-4 py-2 text-xs text-emerald-700"><CheckCircle2 size={14}/> En production depuis {date(selected.case.actual_go_live_at)}</span>:<><button onClick={()=>void action("mark_ready")} disabled={!!busy||!selected.readiness.ready||selected.case.readiness_status==="ready"} className="inline-flex items-center gap-2 rounded-lg bg-[#2d1812] px-4 py-2 text-xs text-white disabled:opacity-40"><BadgeCheck size={14}/> Marquer prêt à lancer</button><button onClick={()=>void action("go_live")} disabled={!!busy||selected.case.readiness_status!=="ready"} className="inline-flex items-center gap-2 rounded-lg bg-[#9d4c27] px-4 py-2 text-xs text-white disabled:opacity-40"><Rocket size={14}/> Mettre en service</button><button onClick={()=>void action("block")} disabled={!!busy||!notes.trim()} className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-xs text-red-700 disabled:opacity-40">Bloquer</button></>}</div></AdminCard>
    <div className="grid gap-4 xl:grid-cols-2"><AdminCard title="Prérequis"><div className="space-y-2">{selected.readiness.blockers.length?selected.readiness.blockers.map((blocker)=><div key={blocker.code} className={`rounded-xl border p-3 ${blocker.severity==="critical"?"border-red-200 bg-red-50":"border-amber-200 bg-amber-50"}`}><div className="flex gap-2"><AlertTriangle size={13} className={blocker.severity==="critical"?"text-red-600":"text-amber-700"}/><div><strong className="text-[11px]">{blocker.label}</strong>{blocker.detail?<p className="mt-1 text-[9px] leading-4 opacity-65">{blocker.detail}</p>:null}</div></div></div>):<div className="rounded-xl bg-emerald-50 p-4 text-xs text-emerald-700"><CheckCircle2 size={18}/><strong className="mt-2 block">Tous les prérequis sont satisfaits.</strong></div>}</div></AdminCard><AdminCard title="Contrôles"><div className="grid gap-2 sm:grid-cols-2">{[["Checklist",`${selected.readiness.counts.tasksDone}/${selected.readiness.counts.tasksRequired}`,selected.readiness.counts.tasksDone===selected.readiness.counts.tasksRequired],["Documents",`${selected.readiness.counts.documentsValidated}/${selected.readiness.counts.documentsRequired}`,selected.readiness.counts.documentsValidated===selected.readiness.counts.documentsRequired],["Contrat",selected.readiness.contractSigned?"Signé":"À finaliser",selected.readiness.contractSigned],["Kickoff",selected.readiness.kickoffConfirmed?"Confirmé":"À confirmer",selected.readiness.kickoffConfirmed],["Responsable Ops",selected.readiness.ownerAssigned?selected.case.owner||"Assigné":"Manquant",selected.readiness.ownerAssigned],["Date cible",selected.readiness.targetDateSet?date(selected.case.target_go_live_date):"Manquante",selected.readiness.targetDateSet]].map(([name,value,ok])=><div key={String(name)} className="rounded-xl bg-[#faf5f0] p-3"><span className="text-[9px] text-[#5b2f22]/45">{name}</span><strong className={`mt-1 block text-xs ${ok?"text-emerald-700":"text-[#7e3518]"}`}>{value}</strong></div>)}</div></AdminCard></div>
    <AdminCard title="Validation documentaire" action={<FileCheck2 size={16} className="text-[#9d4c27]"/>}><div className="divide-y divide-[#5b2f22]/8">{selected.documents.map((document)=><div key={document.id} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-0 flex-1"><strong className="text-xs">{document.name}</strong><p className="mt-1 text-[9px] text-[#5b2f22]/45">{document.required?"Requis":"Optionnel"} · {docLabels[document.status]||document.status}</p></div>{document.document_url?<a href={document.document_url} target="_blank" rel="noreferrer" className="rounded-lg border border-[#5b2f22]/12 bg-white px-3 py-1.5 text-[10px]">Voir</a>:null}{document.status!=="validated"?<button onClick={()=>void reviewDocument(document.id,"validated")} disabled={!!busy} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-[10px] text-emerald-700">Valider</button>:null}{document.status!=="rejected"?<button onClick={()=>void reviewDocument(document.id,"rejected")} disabled={!!busy} className="rounded-lg bg-red-50 px-3 py-1.5 text-[10px] text-red-700">À corriger</button>:null}</div>)}</div></AdminCard>
   </div>:null}
  </div>
 </AdminWorkspace>
}
