import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

export default function SiteDesignPage() {
  return (
    <AdminWorkspace active="Site & Design" title="Site design" subtitle="Personnalisez l’apparence du site public tout en préservant l’identité visuelle MOONY." actions={<><button className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Aperçu</button><button className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Publier les changements</button></>}>
      <div className="grid gap-4 xl:grid-cols-[360px_1fr]">
        <AdminCard title="Réglages du thème"><div className="space-y-2 text-sm">{["Général", "Couleurs", "Typographie", "En-tête & navigation", "Pied de page", "Sections & espacements"].map((x,i)=><button key={x} className={`w-full rounded-lg px-4 py-3 text-left ${i===1?"bg-[#edd6c7] font-semibold":"border border-[#5b2f22]/8 bg-white"}`}>{x}</button>)}</div><div className="mt-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#5b2f22]/45">Palette de marque</p><div className="mt-3 flex gap-3">{["#5b2f22","#9d4c27","#b9693d","#e9b78f","#f8f0e5"].map(c=><span key={c} className="h-10 w-10 rounded-full border border-black/10" style={{backgroundColor:c}} />)}</div></div></AdminCard>
        <AdminCard title="Aperçu du site" action={<button className="text-xs text-[#8d3b19]">Ouvrir le site ↗</button>}><div className="overflow-hidden rounded-xl border border-[#5b2f22]/10 bg-[#c57f56]"><div className="min-h-[520px] bg-[linear-gradient(90deg,rgba(70,31,18,.75),rgba(70,31,18,.16)),url('/images/home-hero.webp')] bg-cover bg-center p-8 text-white"><div className="moony-serif text-2xl">MOONY</div><div className="mt-28 max-w-sm"><h3 className="moony-serif text-5xl leading-[.95]">Ancrée dans nos cultures, tournée vers l’avenir.</h3><p className="mt-4 text-sm text-white/85">Une expérience de santé féminine qui réunit transmission, communauté, bien-être et innovation.</p><button className="mt-5 rounded-full bg-[#8d3b19] px-5 py-2.5 text-sm">Découvrir la communauté</button></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><button className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-left text-sm"><strong className="block">Image hero</strong><span className="text-xs text-[#5b2f22]/45">Remplacer l’image</span></button><button className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-left text-sm"><strong className="block">Couleurs</strong><span className="text-xs text-[#5b2f22]/45">Palette verrouillée</span></button><button className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-left text-sm"><strong className="block">Typographie</strong><span className="text-xs text-[#5b2f22]/45">Titres & textes</span></button></div></AdminCard>
      </div>
    </AdminWorkspace>
  );
}
