"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Check, ExternalLink, Image as ImageIcon, RotateCcw, Save, SlidersHorizontal } from "lucide-react";
import { AdminMediaPicker } from "@/components/admin-media-picker";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type ThemeDraft = { accent:string; surface:string; ink:string; overlay:number; radius:number; heroImageUrl:string; heroPosition:string };
const defaults: ThemeDraft = { accent:"#7e3518",surface:"#fffaf4",ink:"#5b2f22",overlay:82,radius:22,heroImageUrl:"/images/home-hero.jpg",heroPosition:"62% center" };
const brandPalette=["#5b2f22","#7e3518","#9d4c27","#b9693d","#e9b78f","#f8f0e5","#fffaf4"];

export default function SiteDesignPage(){
 const [draft,setDraft]=useState<ThemeDraft>(defaults);const [saved,setSaved]=useState(false);const [panel,setPanel]=useState<"images"|"couleurs"|"style">("images");const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
 useEffect(()=>{void (async()=>{const r=await fetch("/api/admin/settings",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();setDraft({...defaults,...(d.settings?.branding?.theme??{})});setLoading(false)})()},[]);
 function update<K extends keyof ThemeDraft>(key:K,value:ThemeDraft[K]){setSaved(false);setDraft(current=>({...current,[key]:value}))}
 async function save(){setNotice("Enregistrement…");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({branding:{theme:draft}})});const data=await r.json().catch(()=>({}));setSaved(r.ok);setNotice(r.ok?"Thème enregistré et appliqué au site.":data.error??"Enregistrement impossible.");if(r.ok)setTimeout(()=>setSaved(false),2200)}
 function reset(){setDraft(defaults);setSaved(false);setNotice("Réglages remis aux valeurs MOONY par défaut. Enregistrez pour les appliquer.")}
 const previewBackground=useMemo(()=>`linear-gradient(90deg, rgba(47,20,13,${draft.overlay/100}) 0%, rgba(61,25,15,${Math.max((draft.overlay-16)/100,.08)}) 32%, rgba(61,25,15,.14) 60%), url('${draft.heroImageUrl || "/images/home-hero.jpg"}')`,[draft]);
 return <AdminWorkspace active="Site & Design" title="Site & Design" subtitle="Personnalisez l’apparence du site public tout en préservant l’identité visuelle MOONY." actions={<><a href="/" target="_blank" className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><ExternalLink size={15}/> Voir le site</a><button onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white"><Save size={15}/>{saved?"Enregistré":"Enregistrer"}</button></>}>
 <div className="grid gap-4 2xl:grid-cols-[390px_1fr]"><div className="space-y-4"><AdminCard title="Éditeur du thème" action={<button onClick={reset} className="inline-flex items-center gap-1.5 text-xs text-[#8d3b19]"><RotateCcw size={13}/> Réinitialiser</button>}><div className="grid grid-cols-3 gap-2 rounded-xl bg-[#f6ebe3] p-1.5 text-xs"><button onClick={()=>setPanel("images")} className={`rounded-lg px-3 py-2.5 ${panel==="images"?"bg-white font-semibold shadow-sm":"text-[#5b2f22]/60"}`}>Images</button><button onClick={()=>setPanel("couleurs")} className={`rounded-lg px-3 py-2.5 ${panel==="couleurs"?"bg-white font-semibold shadow-sm":"text-[#5b2f22]/60"}`}>Couleurs</button><button onClick={()=>setPanel("style")} className={`rounded-lg px-3 py-2.5 ${panel==="style"?"bg-white font-semibold shadow-sm":"text-[#5b2f22]/60"}`}>Style</button></div>
 {panel==="images"?<div className="mt-5 space-y-5"><div><span className="mb-2 flex items-center gap-2 text-xs font-semibold"><ImageIcon size={14}/> Image principale de l’accueil</span>{draft.heroImageUrl?<div className="mb-3 overflow-hidden rounded-xl border border-[#5b2f22]/10 bg-[#efe5dd]"><img src={draft.heroImageUrl} alt="Aperçu du hero" className="h-40 w-full object-cover" style={{objectPosition:draft.heroPosition}}/></div>:null}<div className="flex flex-col gap-2"><input value={draft.heroImageUrl} onChange={e=>update("heroImageUrl",e.target.value)} placeholder="/images/home-hero.jpg ou https://…" className="w-full rounded-xl border border-[#5b2f22]/12 bg-white px-3 py-3 text-sm"/><div className="flex flex-wrap gap-2"><AdminMediaPicker value={draft.heroImageUrl} onSelect={asset=>{update("heroImageUrl",asset.url);setNotice(`Image « ${asset.fileName} » sélectionnée. Pensez à enregistrer.`)}}/><Link href="/admin/medias" className="inline-flex items-center rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs">Gérer les médias</Link>{draft.heroImageUrl!==defaults.heroImageUrl?<button type="button" onClick={()=>update("heroImageUrl",defaults.heroImageUrl)} className="rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs">Image par défaut</button>:null}</div></div><span className="mt-2 block text-[11px] leading-4 text-[#5b2f22]/45">Choisissez une image dans la bibliothèque MOONY ou collez une URL. Le changement reste en prévisualisation tant que vous n’avez pas enregistré.</span></div><label className="block"><span className="mb-2 block text-xs font-semibold">Position de l’image</span><select value={draft.heroPosition} onChange={e=>update("heroPosition",e.target.value)} className="w-full rounded-xl border border-[#5b2f22]/12 bg-white px-3 py-3 text-sm"><option value="center center">Centrée</option><option value="62% center">Légèrement à droite</option><option value="70% center">À droite</option><option value="40% center">À gauche</option></select></label><div className="rounded-xl border border-[#5b2f22]/10 bg-[#f8eee7] p-4 text-xs leading-5 text-[#5b2f22]/62">Les textes, boutons, titres et SEO de chaque page se modifient dans <Link href="/admin/pages" className="font-semibold text-[#8d3b19]">Pages / CMS</Link>. Ici, on gère l’identité visuelle globale.</div></div>:null}
 {panel==="couleurs"?<div className="mt-5 space-y-6"><div><p className="text-xs font-semibold">Couleur d’accent</p><div className="mt-3 flex flex-wrap gap-2">{brandPalette.map(color=><button key={color} onClick={()=>update("accent",color)} aria-label={`Choisir ${color}`} className="relative h-10 w-10 rounded-full border border-black/10" style={{backgroundColor:color}}>{draft.accent===color?<span className="absolute inset-0 grid place-items-center"><Check size={16} color={color==="#fffaf4"||color==="#f8f0e5"?"#5b2f22":"white"}/></span>:null}</button>)}</div></div><label className="block"><span className="mb-2 block text-xs font-semibold">Fond principal</span><div className="flex gap-2"><input type="color" value={draft.surface} onChange={e=>update("surface",e.target.value)} className="h-11 w-14 rounded-lg border border-[#5b2f22]/12 bg-white p-1"/><input value={draft.surface} onChange={e=>update("surface",e.target.value)} className="min-w-0 flex-1 rounded-xl border border-[#5b2f22]/12 px-3 text-sm"/></div></label><label className="block"><span className="mb-2 block text-xs font-semibold">Couleur de texte</span><div className="flex gap-2"><input type="color" value={draft.ink} onChange={e=>update("ink",e.target.value)} className="h-11 w-14 rounded-lg border border-[#5b2f22]/12 bg-white p-1"/><input value={draft.ink} onChange={e=>update("ink",e.target.value)} className="min-w-0 flex-1 rounded-xl border border-[#5b2f22]/12 px-3 text-sm"/></div></label></div>:null}
 {panel==="style"?<div className="mt-5 space-y-6"><label className="block"><span className="mb-2 flex items-center justify-between text-xs font-semibold"><span className="flex items-center gap-2"><SlidersHorizontal size={14}/> Intensité du voile</span><span>{draft.overlay}%</span></span><input type="range" min="35" max="92" value={draft.overlay} onChange={e=>update("overlay",Number(e.target.value))} className="w-full accent-[#8d3b19]"/></label><label className="block"><span className="mb-2 flex items-center justify-between text-xs font-semibold"><span>Arrondi global</span><span>{draft.radius}px</span></span><input type="range" min="8" max="36" value={draft.radius} onChange={e=>update("radius",Number(e.target.value))} className="w-full accent-[#8d3b19]"/></label><div className="rounded-xl border border-[#5b2f22]/10 bg-[#f8eee7] p-4 text-xs leading-5 text-[#5b2f22]/62">Les réglages sont enregistrés dans le Control Center et appliqués au site public. La charte MOONY reste la référence.</div></div>:null}</AdminCard><AdminCard title="État du thème"><div className="space-y-3 text-xs"><div className="flex items-center justify-between rounded-lg bg-[#eef6ef] px-3 py-3"><span>Connexion au site</span><strong className="text-emerald-700">{loading?"Vérification…":"Active"}</strong></div><div className="flex items-center justify-between rounded-lg bg-[#f8eee7] px-3 py-3"><span>Responsive</span><strong>Desktop · Mobile</strong></div><div className="flex items-center justify-between rounded-lg bg-[#f8eee7] px-3 py-3"><span>Source</span><strong>Control Center</strong></div></div>{notice?<p className="mt-3 rounded-lg bg-[#f8eee7] px-3 py-2.5 text-[11px] leading-5 text-[#5b2f22]/65">{notice}</p>:null}</AdminCard></div>
 <AdminCard title="Aperçu en direct" action={<span className="rounded-full bg-[#eef6ef] px-3 py-1 text-[10px] font-semibold text-emerald-700">Prévisualisation non publiée</span>}><div className="overflow-hidden border border-[#5b2f22]/10 bg-white shadow-[0_18px_60px_rgba(78,40,26,.08)]" style={{borderRadius:`${draft.radius}px`}}><div className="flex items-center justify-between border-b border-black/6 px-5 py-3 text-[10px]" style={{backgroundColor:draft.surface,color:draft.ink}}><span className="moony-serif text-lg">MOONY</span><div className="hidden gap-4 md:flex"><span>Accueil</span><span>Notre mission</span><span>Nos services</span><span>Communauté</span><span>Ressources</span></div><span className="rounded-full px-3 py-1.5 text-white" style={{backgroundColor:draft.accent}}>Prendre rendez-vous</span></div><div className="min-h-[610px] bg-cover p-7 sm:p-10 lg:p-14" style={{backgroundImage:previewBackground,backgroundPosition:draft.heroPosition}}><div className="flex min-h-[500px] max-w-[560px] flex-col justify-center text-white"><h3 className="moony-serif text-[54px] leading-[.94] tracking-[-.045em] sm:text-[66px]">Ancrée dans nos cultures, tournée vers l’avenir.</h3><p className="mt-5 max-w-[460px] text-sm leading-6 text-white/82">Une expérience de santé féminine qui réunit transmission, communauté, bien-être et innovation à chaque étape de la vie.</p><div className="mt-7 flex flex-wrap gap-3"><span className="px-6 py-3 text-sm font-medium text-white" style={{backgroundColor:draft.accent,borderRadius:`${draft.radius}px`}}>Découvrir la communauté</span><span className="border border-white/60 px-6 py-3 text-sm" style={{borderRadius:`${draft.radius}px`}}>Nos services</span></div></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-sm"><strong className="block">Accent</strong><div className="mt-3 flex items-center gap-2"><span className="h-6 w-6 rounded-full border border-black/10" style={{backgroundColor:draft.accent}}/><span className="text-xs text-[#5b2f22]/48">{draft.accent}</span></div></div><div className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-sm"><strong className="block">Voile hero</strong><p className="moony-serif mt-3 text-2xl">{draft.overlay}%</p></div><div className="rounded-xl border border-[#5b2f22]/10 bg-white p-4 text-sm"><strong className="block">Arrondis</strong><p className="moony-serif mt-3 text-2xl">{draft.radius}px</p></div></div></AdminCard></div>
 </AdminWorkspace>;
}
