import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { asText, requireAdmin, writeAuditLog } from "@/lib/admin-api";

const initiativeStatuses=["idea","discovery","planned","in_progress","released","declined"];
const releaseStatuses=["draft","planned","in_progress","released","cancelled"];
const priorities=["low","medium","high","critical"];
function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
async function bodyOf(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function nullable(value:unknown,max=6000){const text=asText(value,max);return text||null}
function dateOnly(value:unknown){const text=asText(value,20);return /^\d{4}-\d{2}-\d{2}$/.test(text)?text:null}
function actor(session:any){return session.name||session.email||"MOONY Admin"}
function score(value:unknown,fallback=3){const parsed=Math.round(Number(value??fallback));return Math.max(1,Math.min(5,Number.isFinite(parsed)?parsed:fallback))}
function themesOf(value:unknown){const raw=Array.isArray(value)?value.map(v=>asText(v,80)):asText(value,800).split(",");return [...new Set(raw.map(v=>v.trim()).filter(Boolean))].slice(0,12)}
function ref(){const day=new Date().toISOString().slice(0,10).replaceAll("-","");return `PRD-${day}-${randomUUID().slice(0,4).toUpperCase()}`}
function empty(){return{available:false,initiatives:[],releases:[],links:[],feedback:[],metrics:{open:0,planned:0,inProgress:0,released:0,linkedFeedback:0,unlinkedFeedback:0}}}

export async function GET(request:Request){
 const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;
 const [initiativesRes,releasesRes,linksRes,feedbackRes]=await Promise.all([
  supabase.from("website_crm_product_initiatives").select("*,website_crm_product_releases(name,version,status,planned_date)").order("updated_at",{ascending:false}).limit(1000),
  supabase.from("website_crm_product_releases").select("*").order("planned_date",{ascending:true,nullsFirst:false}).order("created_at",{ascending:false}).limit(300),
  supabase.from("website_crm_product_initiative_feedback").select("id,initiative_id,feedback_id,note,linked_by,linked_at,website_crm_feedback_items(id,title,priority,status,product_area,themes,source_type,source_score,client_id,website_crm_client_accounts(account_name))").order("linked_at",{ascending:false}).limit(3000),
  supabase.from("website_crm_feedback_items").select("id,title,feedback_text,priority,importance,status,product_area,themes,source_type,source_label,source_score,owner,client_id,website_crm_client_accounts(account_name)").not("status","eq","declined").order("updated_at",{ascending:false}).limit(1000),
 ]);
 if(initiativesRes.error&&missing(initiativesRes.error))return NextResponse.json(empty());
 const fatal=[initiativesRes.error,releasesRes.error,linksRes.error,feedbackRes.error].find((e:any)=>e&&!missing(e));if(fatal)return NextResponse.json({error:fatal.message},{status:500});
 const initiatives=initiativesRes.data??[],links=linksRes.data??[],feedback=feedbackRes.data??[],linkedIds=new Set(links.map((x:any)=>String(x.feedback_id)));
 const metrics={open:initiatives.filter((x:any)=>!["released","declined"].includes(x.status)).length,planned:initiatives.filter((x:any)=>x.status==="planned").length,inProgress:initiatives.filter((x:any)=>x.status==="in_progress").length,released:initiatives.filter((x:any)=>x.status==="released").length,linkedFeedback:linkedIds.size,unlinkedFeedback:feedback.filter((x:any)=>!["closed","declined"].includes(x.status)&&!linkedIds.has(String(x.id))).length};
 return NextResponse.json({available:true,initiatives,releases:releasesRes.data??[],links,feedback,metrics});
}

export async function POST(request:Request){
 const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;const body=await bodyOf(request);if(!body)return NextResponse.json({error:"Requête invalide."},{status:400});const action=asText(body.action,50),who=actor(session),now=new Date().toISOString();
 if(action==="create_initiative"){
  const title=asText(body.title,300);if(!title)return NextResponse.json({error:"Titre de l’initiative obligatoire."},{status:422});const priority=priorities.includes(asText(body.priority,20))?asText(body.priority,20):"medium";
  const created=await supabase.from("website_crm_product_initiatives").insert({reference:ref(),title,problem_statement:nullable(body.problemStatement,8000),product_area:asText(body.productArea,120)||"other",themes:themesOf(body.themes),status:"idea",priority,impact:score(body.impact),confidence:score(body.confidence),effort:score(body.effort),owner:nullable(body.owner,200),target_release_id:nullable(body.targetReleaseId,80),target_date:dateOnly(body.targetDate),decision_rationale:nullable(body.decisionRationale,8000),success_metric:nullable(body.successMetric,2000),expected_outcome:nullable(body.expectedOutcome,4000),created_by:who,updated_by:who}).select("*").single();
  if(created.error){if(missing(created.error))return NextResponse.json({error:"Appliquez la migration CRM V8.13."},{status:503});return NextResponse.json({error:created.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.product_initiative_created","crm_product_initiative",created.data.id,`Initiative produit créée · ${title}`,{priority,productArea:created.data.product_area});return NextResponse.json({ok:true,initiative:created.data},{status:201});
 }
 if(action==="update_initiative"){
  const id=asText(body.id,80);if(!id)return NextResponse.json({error:"Initiative obligatoire."},{status:422});const existing=await supabase.from("website_crm_product_initiatives").select("*").eq("id",id).maybeSingle();if(existing.error||!existing.data)return NextResponse.json({error:"Initiative introuvable."},{status:404});const patch:Record<string,unknown>={updated_by:who,updated_at:now};
  if("title" in body)patch.title=asText(body.title,300)||existing.data.title;if("problemStatement" in body)patch.problem_statement=nullable(body.problemStatement,8000);if("productArea" in body)patch.product_area=asText(body.productArea,120)||"other";if("themes" in body)patch.themes=themesOf(body.themes);if("status" in body){const value=asText(body.status,30);if(!initiativeStatuses.includes(value))return NextResponse.json({error:"Statut invalide."},{status:422});patch.status=value;if(value==="released"){patch.released_at=existing.data.released_at||now;patch.released_by=existing.data.released_by||who}else if(existing.data.status==="released"&&value!=="released"){patch.released_at=null;patch.released_by=null}}if("priority" in body){const value=asText(body.priority,20);if(!priorities.includes(value))return NextResponse.json({error:"Priorité invalide."},{status:422});patch.priority=value}if("impact" in body)patch.impact=score(body.impact);if("confidence" in body)patch.confidence=score(body.confidence);if("effort" in body)patch.effort=score(body.effort);if("owner" in body)patch.owner=nullable(body.owner,200);if("targetReleaseId" in body)patch.target_release_id=nullable(body.targetReleaseId,80);if("targetDate" in body)patch.target_date=dateOnly(body.targetDate);if("decisionRationale" in body)patch.decision_rationale=nullable(body.decisionRationale,8000);if("successMetric" in body)patch.success_metric=nullable(body.successMetric,2000);if("expectedOutcome" in body)patch.expected_outcome=nullable(body.expectedOutcome,4000);if("releaseNotes" in body)patch.release_notes=nullable(body.releaseNotes,8000);
  const updated=await supabase.from("website_crm_product_initiatives").update(patch).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.product_initiative_updated","crm_product_initiative",id,`Initiative produit mise à jour · ${updated.data.title}`,{status:updated.data.status,priority:updated.data.priority});return NextResponse.json({ok:true,initiative:updated.data});
 }
 if(action==="link_feedback"){
  const initiativeId=asText(body.initiativeId,80),feedbackId=asText(body.feedbackId,80);if(!initiativeId||!feedbackId)return NextResponse.json({error:"Initiative et feedback obligatoires."},{status:422});const linked=await supabase.from("website_crm_product_initiative_feedback").insert({initiative_id:initiativeId,feedback_id:feedbackId,note:nullable(body.note,2000),linked_by:who}).select("*").single();if(linked.error){if(linked.error.code==="23505")return NextResponse.json({error:"Ce feedback est déjà lié à cette initiative."},{status:409});return NextResponse.json({error:linked.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.product_feedback_linked","crm_product_initiative",initiativeId,"Feedback VoC lié à une initiative produit",{feedbackId,linkId:linked.data.id});return NextResponse.json({ok:true,link:linked.data},{status:201});
 }
 if(action==="unlink_feedback"){
  const linkId=asText(body.linkId,80);if(!linkId)return NextResponse.json({error:"Lien obligatoire."},{status:422});const row=await supabase.from("website_crm_product_initiative_feedback").select("initiative_id,feedback_id").eq("id",linkId).maybeSingle();if(row.error||!row.data)return NextResponse.json({error:"Lien introuvable."},{status:404});const deleted=await supabase.from("website_crm_product_initiative_feedback").delete().eq("id",linkId);if(deleted.error)return NextResponse.json({error:deleted.error.message},{status:500});await writeAuditLog(supabase,session,"crm.product_feedback_unlinked","crm_product_initiative",row.data.initiative_id,"Feedback VoC retiré d’une initiative produit",{feedbackId:row.data.feedback_id});return NextResponse.json({ok:true});
 }
 if(action==="create_release"){
  const name=asText(body.name,240);if(!name)return NextResponse.json({error:"Nom de release obligatoire."},{status:422});const created=await supabase.from("website_crm_product_releases").insert({name,version:nullable(body.version,80),status:"draft",planned_date:dateOnly(body.plannedDate),owner:nullable(body.owner,200),summary:nullable(body.summary,6000),created_by:who,updated_by:who}).select("*").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.product_release_created","crm_product_release",created.data.id,`Release créée · ${name}`,{version:created.data.version,plannedDate:created.data.planned_date});return NextResponse.json({ok:true,release:created.data},{status:201});
 }
 if(action==="update_release"){
  const id=asText(body.id,80);const existing=await supabase.from("website_crm_product_releases").select("*").eq("id",id).maybeSingle();if(existing.error||!existing.data)return NextResponse.json({error:"Release introuvable."},{status:404});if(existing.data.status==="released")return NextResponse.json({error:"Une release publiée est verrouillée. Les notes restent consultables dans l’historique."},{status:409});const patch:Record<string,unknown>={updated_by:who,updated_at:now};if("name" in body)patch.name=asText(body.name,240)||existing.data.name;if("version" in body)patch.version=nullable(body.version,80);if("status" in body){const value=asText(body.status,30);if(!releaseStatuses.includes(value)||value==="released")return NextResponse.json({error:"Utilisez l’action de publication pour marquer une release comme livrée."},{status:422});patch.status=value}if("plannedDate" in body)patch.planned_date=dateOnly(body.plannedDate);if("owner" in body)patch.owner=nullable(body.owner,200);if("summary" in body)patch.summary=nullable(body.summary,6000);if("releaseNotes" in body)patch.release_notes=nullable(body.releaseNotes,12000);const updated=await supabase.from("website_crm_product_releases").update(patch).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.product_release_updated","crm_product_release",id,`Release mise à jour · ${updated.data.name}`,{status:updated.data.status});return NextResponse.json({ok:true,release:updated.data});
 }
 if(action==="release"){
  const id=asText(body.id,80);const existing=await supabase.from("website_crm_product_releases").select("*").eq("id",id).maybeSingle();if(existing.error||!existing.data)return NextResponse.json({error:"Release introuvable."},{status:404});if(existing.data.status==="released")return NextResponse.json({ok:true,release:existing.data});const published=await supabase.from("website_crm_product_releases").update({status:"released",released_at:now,release_notes:nullable(body.releaseNotes,12000)??existing.data.release_notes,updated_by:who,updated_at:now}).eq("id",id).select("*").single();if(published.error)return NextResponse.json({error:published.error.message},{status:500});const initiatives=await supabase.from("website_crm_product_initiatives").update({status:"released",released_at:now,released_by:who,updated_by:who,updated_at:now}).eq("target_release_id",id).in("status",["planned","in_progress"]).select("id,title");if(initiatives.error)return NextResponse.json({error:initiatives.error.message},{status:500});await writeAuditLog(supabase,session,"crm.product_release_published","crm_product_release",id,`Release livrée · ${published.data.name}`,{initiativeIds:(initiatives.data??[]).map((x:any)=>x.id)});return NextResponse.json({ok:true,release:published.data,releasedInitiatives:initiatives.data??[]});
 }
 return NextResponse.json({error:"Action non prise en charge."},{status:422});
}
