import { NextResponse } from "next/server";
import { asText, requireAdmin, writeAuditLog } from "@/lib/admin-api";
import { syncVoiceFeedbackAlerts } from "@/lib/crm-voice-feedback";

const kinds=["feature_request","bug","usability","service","praise","pricing","integration","other"];
const priorities=["low","medium","high","critical"];
const statuses=["new","reviewed","planned","in_progress","closed","declined"];
function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
async function bodyOf(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function nullable(value:unknown,max=5000){const text=asText(value,max);return text||null}
function dateOnly(value:unknown){const text=asText(value,20);return /^\d{4}-\d{2}-\d{2}$/.test(text)?text:null}
function actor(session:any){return session.name||session.email||"MOONY Admin"}
function themesOf(value:unknown){const raw=Array.isArray(value)?value.map(v=>asText(v,80)):asText(value,800).split(",");return [...new Set(raw.map(v=>v.trim()).filter(Boolean))].slice(0,12)}
function relation(value:any){return Array.isArray(value)?value[0]??null:value??null}
function emptyPayload(){return{available:false,settings:null,clients:[],items:[],sources:{nps:[],support:[]},metrics:{open:0,new:0,critical:0,planned:0,closeLoopDue:0}}}

export async function GET(request:Request){
 const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;
 const [settingsRes,clientsRes,itemsRes,npsRes,supportRes]=await Promise.all([
  supabase.from("website_crm_feedback_settings").select("*").eq("id","default").maybeSingle(),
  supabase.from("website_crm_client_accounts").select("id,lead_id,account_name,status,owner,commercial_owner,website_leads(first_name,last_name,email,company,country)").order("account_name"),
  supabase.from("website_crm_feedback_items").select("*,website_crm_client_accounts(account_name,owner,commercial_owner,lead_id,website_leads(email,country))").order("updated_at",{ascending:false}).limit(1000),
  supabase.from("website_crm_client_surveys").select("id,client_id,survey_type,status,score,comment,respondent_name,sent_to_email,responded_at,website_crm_client_accounts(account_name,owner)").eq("status","responded").not("comment","is",null).order("responded_at",{ascending:false}).limit(200),
  supabase.from("support_tickets").select("id,requester_name,requester_email,type,subject,message,priority,status,created_at,updated_at").in("type",["feedback","complaint"]).order("updated_at",{ascending:false}).limit(200),
 ]);
 if(settingsRes.error&&missing(settingsRes.error))return NextResponse.json(emptyPayload());
 const fatal=[settingsRes.error,clientsRes.error,itemsRes.error,npsRes.error,supportRes.error].find((e:any)=>e&&!missing(e));if(fatal)return NextResponse.json({error:fatal.message},{status:500});
 const items=itemsRes.data??[],imported=new Set(items.filter((x:any)=>x.source_id).map((x:any)=>`${x.source_type}:${x.source_id}`));
 const nps=(npsRes.data??[]).filter((x:any)=>!imported.has(`nps:${x.id}`));
 const support=(supportRes.data??[]).filter((x:any)=>!imported.has(`support:${x.id}`));
 const active=items.filter((x:any)=>!["closed","declined"].includes(x.status)),today=new Date().toISOString().slice(0,10);
 const metrics={open:active.length,new:active.filter((x:any)=>x.status==="new").length,critical:active.filter((x:any)=>x.priority==="critical").length,planned:active.filter((x:any)=>["planned","in_progress"].includes(x.status)).length,closeLoopDue:active.filter((x:any)=>x.close_loop_due&&x.close_loop_due<=today).length};
 return NextResponse.json({available:true,settings:settingsRes.data,clients:clientsRes.data??[],items,sources:{nps,support},metrics});
}

export async function POST(request:Request){
 const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;const body=await bodyOf(request);if(!body)return NextResponse.json({error:"Requête invalide."},{status:400});
 const action=asText(body.action,50),who=actor(session),now=new Date().toISOString();
 if(action==="sync"){
  try{const result=await syncVoiceFeedbackAlerts(supabase);await writeAuditLog(supabase,session,"crm.voice_feedback_sync","crm_voice_feedback",null,"Alertes Voice of Customer analysées",result);return NextResponse.json(result)}catch(err){return NextResponse.json({error:err instanceof Error?err.message:"Analyse indisponible."},{status:500})}
 }
 if(action==="settings"){
  const enabled=Boolean(body.enabled),days=Math.max(0,Math.min(30,Math.round(Number(body.closeLoopWarningDays??3))));const updated=await supabase.from("website_crm_feedback_settings").upsert({id:"default",enabled,close_loop_warning_days:days,updated_by:who,updated_at:now},{onConflict:"id"}).select("*").single();if(updated.error){if(missing(updated.error))return NextResponse.json({error:"Appliquez la migration CRM V8.11."},{status:503});return NextResponse.json({error:updated.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.voice_feedback_settings","crm_voice_feedback_settings",null,"Paramètres Voice of Customer mis à jour",{enabled,closeLoopWarningDays:days});return NextResponse.json({ok:true,settings:updated.data});
 }
 if(action==="create"){
  const title=asText(body.title,300),feedbackText=asText(body.feedbackText,12000),kind=asText(body.feedbackKind,40)||"other",priority=asText(body.priority,20)||"medium",importance=Math.max(1,Math.min(5,Math.round(Number(body.importance||3))));if(!title||!feedbackText)return NextResponse.json({error:"Titre et retour client obligatoires."},{status:422});if(!kinds.includes(kind)||!priorities.includes(priority))return NextResponse.json({error:"Type ou priorité invalide."},{status:422});
  const created=await supabase.from("website_crm_feedback_items").insert({client_id:nullable(body.clientId,80),source_type:"manual",source_label:nullable(body.sourceLabel,160)||"Saisie manuelle",contact_name:nullable(body.contactName,200),contact_email:nullable(body.contactEmail,240),feedback_kind:kind,product_area:asText(body.productArea,120)||"other",themes:themesOf(body.themes),title,feedback_text:feedbackText,priority,importance,status:"new",owner:nullable(body.owner,200),close_loop_due:dateOnly(body.closeLoopDue),created_by:who,updated_by:who}).select("*").single();if(created.error){if(missing(created.error))return NextResponse.json({error:"Appliquez la migration CRM V8.11."},{status:503});return NextResponse.json({error:created.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.voice_feedback_created","crm_feedback",created.data.id,title,{clientId:created.data.client_id,source:"manual",priority});return NextResponse.json({ok:true,item:created.data},{status:201});
 }
 if(action==="import_nps"){
  const surveyId=asText(body.surveyId,80);const survey=await supabase.from("website_crm_client_surveys").select("id,client_id,status,score,comment,respondent_name,sent_to_email,responded_at,website_crm_client_accounts(account_name,owner)").eq("id",surveyId).maybeSingle();if(survey.error||!survey.data||survey.data.status!=="responded"||!String(survey.data.comment||"").trim())return NextResponse.json({error:"Réponse NPS explicite introuvable."},{status:404});const account=relation(survey.data.website_crm_client_accounts);const title=asText(body.title,300)||`Retour NPS ${survey.data.score??"—"}/10 · ${account?.account_name||"Client MOONY"}`;
  const created=await supabase.from("website_crm_feedback_items").insert({client_id:survey.data.client_id,source_type:"nps",source_id:survey.data.id,source_label:"Commentaire NPS",contact_name:survey.data.respondent_name,contact_email:survey.data.sent_to_email,source_score:survey.data.score,feedback_kind:kinds.includes(asText(body.feedbackKind,40))?asText(body.feedbackKind,40):"other",product_area:asText(body.productArea,120)||"other",themes:themesOf(body.themes),title,feedback_text:String(survey.data.comment),priority:priorities.includes(asText(body.priority,20))?asText(body.priority,20):"medium",importance:Math.max(1,Math.min(5,Math.round(Number(body.importance||3)))),status:"new",owner:nullable(body.owner,200)||account?.owner||null,close_loop_due:dateOnly(body.closeLoopDue),created_by:who,updated_by:who}).select("*").single();if(created.error){if(created.error.code==="23505")return NextResponse.json({error:"Ce commentaire NPS est déjà dans Voice of Customer."},{status:409});return NextResponse.json({error:created.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.voice_feedback_import_nps","crm_feedback",created.data.id,title,{surveyId});return NextResponse.json({ok:true,item:created.data},{status:201});
 }
 if(action==="import_support"){
  const ticketId=asText(body.ticketId,80),clientId=nullable(body.clientId,80);const ticket=await supabase.from("support_tickets").select("id,requester_name,requester_email,type,subject,message,priority,status,created_at").eq("id",ticketId).maybeSingle();if(ticket.error||!ticket.data||!["feedback","complaint"].includes(ticket.data.type))return NextResponse.json({error:"Ticket feedback/réclamation introuvable."},{status:404});
  const created=await supabase.from("website_crm_feedback_items").insert({client_id:clientId,source_type:"support",source_id:ticket.data.id,source_label:`Support · ${ticket.data.type}`,contact_name:ticket.data.requester_name,contact_email:ticket.data.requester_email,feedback_kind:kinds.includes(asText(body.feedbackKind,40))?asText(body.feedbackKind,40):"service",product_area:asText(body.productArea,120)||"other",themes:themesOf(body.themes),title:asText(body.title,300)||ticket.data.subject,feedback_text:ticket.data.message,priority:priorities.includes(asText(body.priority,20))?asText(body.priority,20):"medium",importance:Math.max(1,Math.min(5,Math.round(Number(body.importance||3)))),status:"new",owner:nullable(body.owner,200),close_loop_due:dateOnly(body.closeLoopDue),created_by:who,updated_by:who}).select("*").single();if(created.error){if(created.error.code==="23505")return NextResponse.json({error:"Ce ticket est déjà dans Voice of Customer."},{status:409});return NextResponse.json({error:created.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.voice_feedback_import_support","crm_feedback",created.data.id,created.data.title,{ticketId,clientId});return NextResponse.json({ok:true,item:created.data},{status:201});
 }
 if(action==="update"){
  const id=asText(body.id,80);if(!id)return NextResponse.json({error:"Feedback obligatoire."},{status:422});const existing=await supabase.from("website_crm_feedback_items").select("*").eq("id",id).maybeSingle();if(existing.error||!existing.data)return NextResponse.json({error:"Feedback introuvable."},{status:404});const patch:Record<string,unknown>={updated_by:who,updated_at:now};
  if("status" in body){const value=asText(body.status,30);if(!statuses.includes(value))return NextResponse.json({error:"Statut invalide."},{status:422});patch.status=value;if(value!=="new"&&!existing.data.reviewed_at){patch.reviewed_at=now;patch.reviewed_by=who}if(["closed","declined"].includes(value)){patch.closed_at=now;patch.closed_by=who}else if(["new","reviewed","planned","in_progress"].includes(value)){patch.closed_at=null;patch.closed_by=null}}
  if("priority" in body){const value=asText(body.priority,20);if(!priorities.includes(value))return NextResponse.json({error:"Priorité invalide."},{status:422});patch.priority=value}if("importance" in body)patch.importance=Math.max(1,Math.min(5,Math.round(Number(body.importance||3))));if("feedbackKind" in body){const value=asText(body.feedbackKind,40);if(!kinds.includes(value))return NextResponse.json({error:"Type de feedback invalide."},{status:422});patch.feedback_kind=value}if("productArea" in body)patch.product_area=asText(body.productArea,120)||"other";if("themes" in body)patch.themes=themesOf(body.themes);if("owner" in body)patch.owner=nullable(body.owner,200);if("closeLoopDue" in body)patch.close_loop_due=dateOnly(body.closeLoopDue);if("resolutionNote" in body)patch.resolution_note=nullable(body.resolutionNote,6000);if("title" in body)patch.title=asText(body.title,300)||existing.data.title;if("feedbackText" in body)patch.feedback_text=asText(body.feedbackText,12000)||existing.data.feedback_text;if("clientId" in body)patch.client_id=nullable(body.clientId,80);
  const updated=await supabase.from("website_crm_feedback_items").update(patch).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.voice_feedback_updated","crm_feedback",id,updated.data.title,{status:updated.data.status,priority:updated.data.priority,productArea:updated.data.product_area});return NextResponse.json({ok:true,item:updated.data});
 }
 if(action==="create_task"){
  const id=asText(body.id,80);const item=await supabase.from("website_crm_feedback_items").select("id,client_id,title,priority,owner,close_loop_due,website_crm_client_accounts(lead_id,account_name,owner,commercial_owner)").eq("id",id).maybeSingle();if(item.error||!item.data)return NextResponse.json({error:"Feedback introuvable."},{status:404});const account=relation(item.data.website_crm_client_accounts);if(!account?.lead_id)return NextResponse.json({error:"Rattachez ce feedback à un compte client avant de créer une tâche."},{status:422});const due=item.data.close_loop_due?`${item.data.close_loop_due}T12:00:00.000Z`:new Date(Date.now()+7*86400000).toISOString();const priority=item.data.priority==="critical"?"urgent":item.data.priority==="high"?"high":"normal";const task=await supabase.from("website_crm_tasks").insert({lead_id:account.lead_id,title:`VoC · ${item.data.title}`,due_at:due,status:"todo",priority,assigned_to:item.data.owner||account.owner||account.commercial_owner||null,notes:"Tâche interne de suivi Voice of Customer. Aucune communication client n’est envoyée automatiquement.",metadata:{source:"crm-voice-feedback",feedback_id:item.data.id,client_id:item.data.client_id}}).select("*").single();if(task.error)return NextResponse.json({error:task.error.message},{status:500});await writeAuditLog(supabase,session,"crm.voice_feedback_task","crm_feedback",id,`Tâche créée · ${item.data.title}`,{taskId:task.data.id});return NextResponse.json({ok:true,task:task.data},{status:201});
 }
 return NextResponse.json({error:"Action non prise en charge."},{status:422});
}
