"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, HeartPulse, Play, RefreshCw, Save, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Settings={enabled:boolean;health_risk_enabled:boolean;nps_detractor_enabled:boolean;renewal_enabled:boolean;expansion_enabled:boolean;expansion_adoption_threshold:number;renewal_day_1:number;renewal_day_2:number;renewal_day_3:number};
type Client={id:string;account_name:string;lead_id:string;owner:string|null;commercial_owner:string|null;health_score:number;health_status:string;adoption_score:number|null;renewal_date:string|null;website_leads?:{first_name:string;last_name:string;email:string;company:string|null;country:string|null}|null};
type CaseRow={id:string;client_id:string;trigger_type:"health_risk"|"nps_detractor";trigger_key:string;title:string;status:"open"|"in_progress"|"recovered"|"closed";priority:"high"|"urgent";owner:string|null;opened_at:string;due_at:string|null;recovered_at:string|null;trigger_snapshot:Record<string,unknown>;website_crm_client_accounts:Client|null};
type RunRow={id:string;client_id:string;trigger_type:string;trigger_key:string;status:string;summary:string|null;actions:unknown[];executed_at:string;website_crm_client_accounts:{id:string;account_name:string}|null};
type Payload={available:boolean;settings:Settings|null;cases:CaseRow[];runs:RunRow[];metrics:{open:number;urgent:number;recovered:number;runs7d:number};capabilities:{cron:boolean}};
const fallback:Settings={enabled:false,health_risk_enabled:true,nps_detractor_enabled:true,renewal_enabled:true,expansion_enabled:true,expansion_adoption_threshold:85,renewal_day_1:60,renewal_day_2:30,renewal_day_3:15};
const empty:Payload={available:true,settings:fallback,cases:[],runs:[],metrics:{open:0,urgent:0,recovered:0,runs7d:0},capabilities:{cron:false}};
const statusLabels:Record<string,string>={open:"Ouvert",in_progress:"En cours",recovered:"Récupéré",closed:"Clos",success:"Succès",partial:"Partiel",failed:"Échec",skipped:"Ignoré"};
const triggerLabels:Record<string,string>={health_risk:"Risque santé client",nps_detractor:"NPS détracteur",renewal:"Renouvellement",expansion:"Expansion"};
function date(value:string|null){if(!value)return"—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(parsed)}
function caseTone(row:CaseRow){return row.status==="recovered"?"bg-emerald-50 text-emerald-700":row.status==="closed"?"bg-stone-100 text-stone-600":row.priority==="urgent"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}

export default function RetentionAutomationPage(){
 const [data,setData]=useState<Payload>(empty);const [settings,setSettings]=useState<Settings>(fallback);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [notice,setNotice]=useState("");const [filter,setFilter]=useState("active");
 async function load(silent=false){if(!silent)setLoading(true);try{const response=await fetch("/api/admin/crm/retention",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Impossible de charger la rétention.");return}const next={...empty,...payload} as Payload;setData(next);if(next.settings)setSettings(next.settings)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const cases=useMemo(()=>data.cases.filter((row)=>filter==="all"?true:filter==="active"?["open","in_progress"].includes(row.status):row.status===filter),[data.cases,filter]);
 async function save(){setBusy("save");setNotice("");try{const response=await fetch("/api/admin/crm/retention",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:settings.enabled,healthRiskEnabled:settings.health_risk_enabled,npsDetractorEnabled:settings.nps_detractor_enabled,renewalEnabled:settings.renewal_enabled,expansionEnabled:settings.expansion_enabled,expansionAdoptionThreshold:settings.expansion_adoption_threshold,renewalDay1:settings.renewal_day_1,renewalDay2:settings.renewal_day_2,renewalDay3:settings.renewal_day_3})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Enregistrement impossible.");return}setNotice(settings.enabled?"Automatisations de rétention activées avec ces paramètres.":"Paramètres enregistrés. L’automatisation principale reste désactivée.");await load(true)}finally{setBusy("")}}
 async function run(){setBusy("run");setNotice("");try{const response=await fetch("/api/admin/crm/retention",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run"})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Exécution impossible.");return}const r=payload.retention;setNotice(`Exécution terminée : ${r?.runs||0} déclenchement(s), ${r?.createdTasks||0} tâche(s), ${r?.createdCases||0} cas, ${r?.createdGrowth||0} opportunité(s) de croissance.`);await load(true)}finally{setBusy("")}}
 async function updateCase(caseId:string,status:string){setBusy(caseId);try{const response=await fetch("/api/admin/crm/retention",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"case_status",caseId,status})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Mise à jour impossible.");return}setNotice("Cas de rétention mis à jour.");await load(true)}finally{setBusy("")}}
 const toggle=(key:keyof Pick<Settings,"enabled"|"health_risk_enabled"|"nps_detractor_enabled"|"renewal_enabled"|"expansion_enabled">)=><button type="button" onClick={()=>setSettings((current)=>({...current,[key]:!current[key]}))} className={`relative h-6 w-11 rounded-full transition ${settings[key]?"bg-[#9d4c27]":"bg-[#d9cec7]"}`} aria-pressed={settings[key]}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${settings[key]?"left-6":"left-1"}`}/></button>;
 return <AdminWorkspace active="Rétention auto" title="Rétention automatisée" subtitle="Transformez les signaux Customer Success en actions internes : anti-churn, récupération NPS, renouvellements et opportunités d’expansion — avec validation humaine avant tout contact client." actions={<><Link href="/admin/customer-success" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Customer Success</Link><button onClick={()=>void run()} disabled={busy==="run"||!data.available} className="inline-flex items-center gap-2 rounded-lg bg-[#2d1812] px-4 py-2.5 text-sm text-white disabled:opacity-40"><Play size={14}/>{busy==="run"?"Exécution…":"Exécuter maintenant"}</button></>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911091500_crm_retention_automations.sql</strong> après CRM V8 pour activer cette couche.</div>:null}
  {data.available&&!data.capabilities.cron?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800">Le moteur peut être exécuté manuellement ici, mais l’exécution automatique des jalons et changements de santé nécessite le scheduler protégé par <strong>AUTOMATION_CRON_SECRET</strong>.</div>:null}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="admin-card admin-shadow p-4"><HeartPulse size={16} className={settings.enabled?"text-emerald-600":"text-[#9d4c27]"}/><strong className="moony-serif mt-2 block text-2xl font-normal">{loading?"…":settings.enabled?"ON":"OFF"}</strong><span className="text-[9px] text-[#5b2f22]/45">Moteur de rétention</span></article><article className="admin-card admin-shadow p-4"><AlertTriangle size={16} className="text-red-600"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.urgent}</strong><span className="text-[9px] text-[#5b2f22]/45">Cas urgents</span></article><article className="admin-card admin-shadow p-4"><ShieldCheck size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.open}</strong><span className="text-[9px] text-[#5b2f22]/45">Cas ouverts</span></article><article className="admin-card admin-shadow p-4"><Zap size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.runs7d}</strong><span className="text-[9px] text-[#5b2f22]/45">Déclenchements réussis · 7 j</span></article></div>
  <div className="mt-5 grid gap-4 xl:grid-cols-[.9fr_1.1fr]">
   <AdminCard title="Règles de rétention" action={<button onClick={()=>void save()} disabled={busy==="save"||!data.available} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-3 py-2 text-[10px] text-white disabled:opacity-40"><Save size={12}/> Enregistrer</button>}>
    <div className="rounded-2xl bg-[#2d1812] p-5 text-[#fffaf4]"><div className="flex items-center justify-between gap-4"><div><span className="text-[9px] uppercase tracking-[.16em] text-[#e9b78f]">Activation générale</span><h3 className="moony-serif mt-1 text-2xl">Rétention automatique</h3><p className="mt-2 max-w-xl text-[10px] leading-5 text-[#fffaf4]/60">Désactivée par défaut. Même activée, cette couche ne contacte jamais automatiquement le client : elle crée des tâches, des cas de récupération, des alertes et des opportunités internes.</p></div>{toggle("enabled")}</div></div>
    <div className="mt-4 space-y-2">{[
      ["health_risk_enabled","Passage à risque → playbook anti-churn","Crée un cas et trois actions internes de récupération."],
      ["nps_detractor_enabled","NPS détracteur → séquence urgente","Crée un cas de récupération et trois tâches, sans réponse client automatique."],
      ["renewal_enabled","Renouvellement → jalons J-60 / J-30 / J-15","Prépare progressivement la décision de renouvellement."],
      ["expansion_enabled","Client sain + forte adoption → expansion","Crée une opportunité upsell/cross-sell à qualifier humainement."],
    ].map(([key,title,description])=><div key={key} className="flex items-center gap-4 rounded-xl border border-[#5b2f22]/8 bg-[#fffaf6] p-4"><div className="min-w-0 flex-1"><strong className="text-xs">{title}</strong><p className="mt-1 text-[9px] leading-4 text-[#5b2f22]/45">{description}</p></div>{toggle(key as keyof Pick<Settings,"health_risk_enabled"|"nps_detractor_enabled"|"renewal_enabled"|"expansion_enabled">)}</div>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-4"><label className="text-[10px] text-[#5b2f22]/50">Adoption min. expansion<input type="number" min="50" max="100" value={settings.expansion_adoption_threshold} onChange={(e)=>setSettings((d)=>({...d,expansion_adoption_threshold:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Premier jalon<input type="number" min="1" max="365" value={settings.renewal_day_1} onChange={(e)=>setSettings((d)=>({...d,renewal_day_1:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Deuxième jalon<input type="number" min="1" max="365" value={settings.renewal_day_2} onChange={(e)=>setSettings((d)=>({...d,renewal_day_2:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Dernier jalon<input type="number" min="1" max="365" value={settings.renewal_day_3} onChange={(e)=>setSettings((d)=>({...d,renewal_day_3:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label></div>
   </AdminCard>
   <AdminCard title="Principes de contrôle humain" action={<ShieldCheck size={16} className="text-[#9d4c27]"/>}><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#faf5f0] p-4"><Sparkles size={16} className="text-[#9d4c27]"/><strong className="mt-2 block text-xs">Automatiser l’interne</strong><p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/50">Création de tâches, dossiers anti-churn, rappels et opportunités de croissance.</p></div><div className="rounded-xl bg-[#faf5f0] p-4"><CheckCircle2 size={16} className="text-emerald-600"/><strong className="mt-2 block text-xs">Garder l’humain face au client</strong><p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/50">Aucun e-mail de récupération, renouvellement ou upsell n’est envoyé sur la seule base d’un score.</p></div><div className="rounded-xl bg-[#faf5f0] p-4"><HeartPulse size={16} className="text-[#9d4c27]"/><strong className="mt-2 block text-xs">Signaux explicites</strong><p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/50">Adoption renseignée, NPS, échéances, support, revues et suivi Customer Success.</p></div><div className="rounded-xl bg-[#faf5f0] p-4"><RefreshCw size={16} className="text-[#9d4c27]"/><strong className="mt-2 block text-xs">Idempotent</strong><p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/50">Chaque déclencheur possède une clé unique afin d’éviter de recréer les mêmes actions à chaque passage du cron.</p></div></div></AdminCard>
  </div>
  <div className="mt-5 grid gap-4 2xl:grid-cols-[1.25fr_.75fr]">
   <AdminCard title="Cas de rétention" action={<select value={filter} onChange={(e)=>setFilter(e.target.value)} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2 text-[10px]"><option value="active">Actifs</option><option value="open">Ouverts</option><option value="in_progress">En cours</option><option value="recovered">Récupérés</option><option value="closed">Clos</option><option value="all">Tous</option></select>}><div className="divide-y divide-[#5b2f22]/8">{cases.length?cases.map((item)=>{const client=item.website_crm_client_accounts;return <div key={item.id} className="py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{item.title}</strong><span className={`rounded-full px-2 py-1 text-[9px] ${caseTone(item)}`}>{item.priority==="urgent"?"Urgent · ":""}{statusLabels[item.status]}</span></div><p className="mt-1 text-[10px] text-[#5b2f22]/45">{triggerLabels[item.trigger_type]} · ouvert {date(item.opened_at)} · échéance {date(item.due_at)}</p><p className="mt-2 text-[10px]">{client?.account_name||"Client"} · {item.owner||client?.owner||"Responsable à assigner"}</p><div className="mt-2 flex flex-wrap gap-2"><Link href={`/admin/customer-success?client=${item.client_id}`} className="rounded-lg border border-[#5b2f22]/10 bg-white px-2.5 py-1.5 text-[9px]">Ouvrir Customer Success</Link>{client?.lead_id?<Link href={`/admin/crm?lead=${client.lead_id}`} className="rounded-lg border border-[#5b2f22]/10 bg-white px-2.5 py-1.5 text-[9px]">CRM</Link>:null}</div></div><select value={item.status} disabled={busy===item.id} onChange={(e)=>void updateCase(item.id,e.target.value)} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2 text-[10px]"><option value="open">Ouvert</option><option value="in_progress">En cours</option><option value="recovered">Récupéré</option><option value="closed">Clos</option></select></div></div>}):<p className="py-10 text-center text-xs text-[#5b2f22]/40">Aucun cas dans cette vue.</p>}</div></AdminCard>
   <AdminCard title="Derniers déclenchements" action={<Clock3 size={15} className="text-[#9d4c27]"/>}><div className="divide-y divide-[#5b2f22]/8">{data.runs.length?data.runs.slice(0,12).map((run)=><div key={run.id} className="py-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-[11px]">{run.website_crm_client_accounts?.account_name||"Client MOONY"}</strong><p className="mt-1 text-[9px] text-[#5b2f22]/45">{triggerLabels[run.trigger_type]||run.trigger_type} · {run.summary||"Exécution"}</p></div><span className={`rounded-full px-2 py-1 text-[8px] ${run.status==="success"?"bg-emerald-50 text-emerald-700":run.status==="failed"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{statusLabels[run.status]||run.status}</span></div><p className="mt-1 text-[8px] text-[#5b2f22]/35">{date(run.executed_at)}</p></div>):<p className="py-8 text-center text-xs text-[#5b2f22]/40">Aucun déclenchement enregistré.</p>}</div></AdminCard>
  </div>
 </AdminWorkspace>;
}
