"use client";

import Link from "next/link";
import { AlertCircle, Bell, CalendarClock, Check, CheckCircle2, FileCheck2, FileText, Headphones, ListTodo, Mail, UserPlus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type Item={id:string;kind:"task"|"lead"|"ticket"|"appointment"|"campaign"|"content"|"proposal";title:string;subtitle:string;href:string;severity:"info"|"warning"|"urgent";dueAt?:string|null;createdAt?:string|null;read?:boolean};

const icons={task:ListTodo,lead:UserPlus,ticket:Headphones,appointment:CalendarClock,campaign:Mail,content:FileText,proposal:FileCheck2};
function when(value?:string|null){if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return"";return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(date)}

export function AdminNotifications(){
 const [items,setItems]=useState<Item[]>([]);const [unread,setUnread]=useState(0);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [available,setAvailable]=useState(true);const [stateAvailable,setStateAvailable]=useState(true);const box=useRef<HTMLDivElement>(null);
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/notifications",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const data=await response.json();if(response.ok){setItems(data.items??[]);setUnread(data.unreadCount??0);setAvailable(data.tasksAvailable??true);setStateAvailable(data.stateAvailable??true)}}finally{setLoading(false)}}
 async function mark(action:"read"|"unread"|"dismiss",ids:string[]){if(!ids.length||!stateAvailable)return;const response=await fetch("/api/admin/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,ids})});if(response.ok)void load()}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),90000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const close=(event:MouseEvent)=>{if(box.current&&!box.current.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 return <div ref={box} className="relative">
  <button onClick={()=>{setOpen(value=>!value);if(!open)void load()}} className="relative rounded-full p-2 transition hover:bg-[#f5e8df]" aria-label="Notifications" aria-expanded={open}><Bell size={18}/>{unread?<span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-[#9d4c27] px-1 text-[8px] font-bold text-white">{unread>9?"9+":unread}</span>:null}</button>
  {open?<div className="absolute right-0 top-[calc(100%+12px)] z-50 w-[380px] max-w-[88vw] overflow-hidden rounded-2xl border border-[#5b2f22]/10 bg-[#fffdf9] shadow-[0_24px_65px_rgba(55,26,17,.17)]">
   <div className="flex items-center border-b border-[#5b2f22]/8 px-4 py-3"><div><h3 className="moony-serif text-xl">Notifications</h3><p className="text-[10px] text-[#5b2f22]/42">{unread?`${unread} non lue${unread>1?"s":""}`:"Vous êtes à jour."}</p></div>{unread&&stateAvailable?<button onClick={()=>void mark("read",items.filter(item=>!item.read).map(item=>item.id))} className="ml-auto mr-2 inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[9px] text-[#7e3518] hover:bg-[#f5e8df]"><Check size={11}/> Tout lire</button>:null}<button onClick={()=>setOpen(false)} className="rounded-full p-1.5 text-[#5b2f22]/40 hover:bg-[#f5e8df]" aria-label="Fermer"><X size={15}/></button></div>
   {!available?<div className="m-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[10px] leading-4 text-amber-800">Les relances commerciales seront incluses après application de la migration CRM.</div>:null}
   {!stateAvailable?<div className="m-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[10px] leading-4 text-amber-800">Appliquez la migration des notifications pour conserver les états lus/non lus.</div>:null}
   <div className="max-h-[440px] overflow-y-auto p-2">{loading&&!items.length?<div className="py-10 text-center text-xs text-[#5b2f22]/42">Actualisation…</div>:items.length?items.slice(0,12).map(item=>{const Icon=icons[item.kind]||FileText;return <div key={item.id} className={`group flex items-start gap-3 rounded-xl px-3 py-3 transition hover:bg-[#f8ece4] ${item.read?"opacity-65":""}`}><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-full ${item.severity==="urgent"?"bg-red-100 text-red-600":item.severity==="warning"?"bg-amber-100 text-amber-700":"bg-[#efe0d5] text-[#8d3b19]"}`}><Icon size={14}/></span><Link href={item.href} onClick={()=>{setOpen(false);if(!item.read)void mark("read",[item.id])}} className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="block truncate text-xs">{item.title}</strong>{!item.read?<span className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#9d4c27]"/>:null}</div><span className="mt-1 block text-[10px] leading-4 text-[#5b2f22]/48">{item.subtitle}</span>{item.dueAt||item.createdAt?<span className="mt-1 block text-[9px] text-[#8d3b19]">{when(item.dueAt||item.createdAt)}</span>:null}</Link>{item.severity==="urgent"?<AlertCircle size={13} className="mt-1 shrink-0 text-red-500"/>:null}{stateAvailable?<button onClick={()=>void mark("dismiss",[item.id])} className="hidden rounded-full p-1 text-[#5b2f22]/35 hover:bg-white group-hover:block" title="Masquer"><X size={11}/></button>:null}</div>}):<div className="py-10 text-center"><CheckCircle2 size={30} className="mx-auto text-emerald-500/65"/><p className="mt-2 text-xs font-medium">Rien d’urgent pour le moment.</p><p className="mt-1 text-[10px] text-[#5b2f22]/42">Le Control Center vous signalera les actions qui demandent votre attention.</p></div>}</div>
   <div className="border-t border-[#5b2f22]/8 bg-[#fbf7f3] p-2"><Link href="/admin/activite" onClick={()=>setOpen(false)} className="block rounded-lg px-3 py-2 text-center text-[10px] font-medium text-[#7e3518] hover:bg-white">Ouvrir le centre d’activité</Link></div>
  </div>:null}
 </div>;
}
