"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { BadgeDollarSign, ChevronDown, Coins, RefreshCw, TrendingUp, WalletCards } from "lucide-react";

export const ADMIN_CURRENCIES=["EUR","XOF","CDF","GHS","CAD","USD"] as const;
export type AdminCurrency=typeof ADMIN_CURRENCIES[number];
type Fx={available:boolean;cacheAvailable:boolean;baseCurrency:string;rates:Record<string,number>;rateDates:Record<string,string>;providers:Record<string,string[]>;source:string;fetchedAt:string|null;defaultDisplayCurrency:AdminCurrency;refreshHours:number;error?:string};
type SummaryRow={currency:string;mrr:number;arr:number;billed:number;collected:number;outstanding:number;overdue:number;pipeline:number;weightedPipeline:number;won:number;activeProposals:number};
type Payload={fx:Fx;summary:{rows:SummaryRow[];revenueAvailable:boolean;commercialAvailable:boolean};supportedCurrencies:string[]};
type ContextValue={currency:AdminCurrency;setCurrency:(value:AdminCurrency)=>void;fx:Fx|null;rows:SummaryRow[];loading:boolean;convert:(amount:number,from:string,to?:AdminCurrency)=>number|null;format:(amount:number,from?:string,to?:AdminCurrency)=>string;original:(amount:number,currency:string)=>string;total:(field:keyof Omit<SummaryRow,"currency">)=>number|null;refresh:()=>Promise<void>};
const Context=createContext<ContextValue|null>(null);
const labels:Record<AdminCurrency,string>={EUR:"Euro",XOF:"Franc CFA",CDF:"Franc congolais",GHS:"Cedi ghanéen",CAD:"Dollar canadien",USD:"Dollar américain"};
function isCurrency(value:unknown):value is AdminCurrency{return ADMIN_CURRENCIES.includes(String(value||"").toUpperCase() as AdminCurrency)}
function digits(code:string){return ["XOF","CDF"].includes(code)?0:2}
function formatRaw(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:digits(currency)}).format(Number(value||0))}catch{return`${Number(value||0).toLocaleString("fr-FR",{maximumFractionDigits:digits(currency)})} ${currency}`}}
function convertWithRates(amount:number,from:string,to:string,rates:Record<string,number>){const source=String(from||"").toUpperCase(),target=String(to||"").toUpperCase();if(source===target)return Number(amount||0);const sr=source==="EUR"?1:Number(rates[source]),tr=target==="EUR"?1:Number(rates[target]);if(!Number.isFinite(sr)||sr<=0||!Number.isFinite(tr)||tr<=0)return null;return Number(amount||0)/sr*tr}

export function AdminCurrencyProvider({children}:{children:React.ReactNode}){const [payload,setPayload]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[currency,setCurrencyState]=useState<AdminCurrency>("XOF");
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/crm/fx",{cache:"no-store"});if(!response.ok)return;const next=await response.json() as Payload;setPayload(next);const stored=localStorage.getItem("moony-admin-display-currency");setCurrencyState(isCurrency(stored)?stored:isCurrency(next.fx?.defaultDisplayCurrency)?next.fx.defaultDisplayCurrency:"XOF")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function setCurrency(value:AdminCurrency){setCurrencyState(value);localStorage.setItem("moony-admin-display-currency",value)}
 const convert=(amount:number,from:string,to:AdminCurrency=currency)=>payload?.fx?.available?convertWithRates(amount,from,to,payload.fx.rates):(String(from).toUpperCase()===to?Number(amount||0):null);
 const original=(amount:number,code:string)=>formatRaw(amount,String(code||"XOF").toUpperCase());
 const format=(amount:number,from="XOF",to:AdminCurrency=currency)=>{const converted=convert(amount,from,to);return converted==null?original(amount,from):`${String(from).toUpperCase()===to?"":"≈ "}${formatRaw(converted,to)}`};
 const total=(field:keyof Omit<SummaryRow,"currency">)=>{if(!payload?.fx?.available)return null;let sum=0,found=false;for(const row of payload.summary?.rows||[]){const value=convertWithRates(Number(row[field]||0),row.currency,currency,payload.fx.rates);if(value==null)continue;sum+=value;found=true}return found?sum:0};
 async function refresh(){try{const response=await fetch("/api/admin/crm/fx",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"refresh"})});if(response.ok)await load()}catch{}}
 const value=useMemo<ContextValue>(()=>({currency,setCurrency,fx:payload?.fx||null,rows:payload?.summary?.rows||[],loading,convert,format,original,total,refresh}),[currency,payload,loading]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAdminCurrency(){const value=useContext(Context);if(!value)throw new Error("useAdminCurrency must be used inside AdminCurrencyProvider");return value}

export function AdminCurrencySelector(){const {currency,setCurrency,fx,rows,loading,total,refresh}=useAdminCurrency();const unsupported=[...new Set(rows.map(row=>row.currency).filter(code=>!ADMIN_CURRENCIES.includes(code as AdminCurrency)))];const cards:[string,keyof Omit<SummaryRow,"currency">,typeof Coins][]=[["MRR","mrr",Coins],["Pipeline","pipeline",TrendingUp],["Signé","won",BadgeDollarSign],["Encaissé","collected",WalletCards]];const latestDates=Object.values(fx?.rateDates||{}).filter(Boolean).sort();const rateDate=latestDates.at(-1)||"—";
 return <details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-lg border border-[#5b2f22]/10 bg-white px-2.5 py-2 text-xs text-[#4c2a20] hover:bg-[#fff9f4]"><Coins size={15} strokeWidth={1.7}/><strong>{currency}</strong><ChevronDown size={13}/></summary><div className="absolute right-0 top-11 z-50 w-[340px] rounded-2xl border border-[#5b2f22]/10 bg-[#fffdf9] p-4 shadow-[0_22px_70px_rgba(45,24,18,.18)]"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#9d4c27]">Devise d’affichage</p><p className="mt-1 text-xs text-[#5b2f22]/55">Les montants d’origine restent inchangés.</p></div><button onClick={()=>void refresh()} disabled={loading} title="Actualiser les taux" className="rounded-lg border border-[#5b2f22]/10 p-2 text-[#6f351f] disabled:opacity-40"><RefreshCw size={14} className={loading?"animate-spin":""}/></button></div><select value={currency} onChange={e=>setCurrency(e.target.value as AdminCurrency)} className="mt-3 w-full rounded-lg border border-[#5b2f22]/12 bg-white px-3 py-2.5 text-sm">{ADMIN_CURRENCIES.map(code=><option key={code} value={code}>{code} · {labels[code]}</option>)}</select><div className="mt-4 grid grid-cols-2 gap-2">{cards.map(([label,field,Icon])=>{const value=total(field);return <div key={label} className="rounded-xl bg-[#f8f0e5] p-3"><Icon size={14} className="text-[#9d4c27]"/><span className="mt-2 block text-[9px] text-[#5b2f22]/45">{label} converti</span><strong className="mt-0.5 block text-sm">{value==null?"—":`≈ ${formatRaw(value,currency)}`}</strong></div>})}</div><div className="mt-3 rounded-xl border border-[#5b2f22]/8 bg-white p-3 text-[9px] leading-4 text-[#5b2f22]/48"><p>Source : Frankfurter v2 · taux de référence actuels · date la plus récente {rateDate}.</p><p>Les conversions sont indicatives pour le pilotage ; elles ne remplacent jamais le montant contractuel ou comptable.</p>{fx&&!fx.cacheAvailable?<p className="mt-1 text-amber-700">Cache Supabase FX non disponible : appliquer la migration V8.12.1.</p>:null}{fx?.error?<p className="mt-1 text-red-700">{fx.error}</p>:null}{unsupported.length?<p className="mt-1 text-amber-700">Devise(s) non converties : {unsupported.join(", ")}.</p>:null}</div></div></details>}
