import Link from "next/link";
import { ArrowUpRight, Check, Mail } from "lucide-react";
import type { CmsSection } from "@/lib/cms-types";
import { getFeaturedTestimonials, getPublishedPartners } from "@/lib/public-content";

const backgrounds:Record<NonNullable<CmsSection["background"]>,string>={
  ivory:"bg-[#fffaf4] text-[#5b2f22]",
  peach:"bg-[#f5e2d5] text-[#5b2f22]",
  terracotta:"bg-[#b9693d] text-white",
  brown:"bg-[#4b271d] text-white",
};

function SectionHeading({section}:{section:CmsSection}){
  return <>{section.eyebrow?<p className="text-[11px] font-semibold uppercase tracking-[.3em] opacity-65">{section.eyebrow}</p>:null}{section.title?<h2 className="moony-serif mt-3 whitespace-pre-line text-[42px] leading-[1] tracking-[-.035em] sm:text-[52px]">{section.title}</h2>:null}</>;
}

export async function CmsSections({sections}:{sections:CmsSection[]}){
  const visible=(sections??[]).filter(section=>section&&!section.hidden);
  if(!visible.length)return null;
  const needsTestimonials=visible.some(section=>section.type==="testimonials");
  const needsPartners=visible.some(section=>section.type==="partners");
  const [testimonials,partners]=await Promise.all([needsTestimonials?getFeaturedTestimonials(6):Promise.resolve([]),needsPartners?getPublishedPartners(12):Promise.resolve([])]);

  return <div>{visible.map(section=>{
    const tone=backgrounds[section.background??"ivory"];
    if(section.type==="spacer")return <div key={section.id} className="h-10 sm:h-16" aria-hidden="true"/>;
    if(section.type==="text")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto max-w-[1200px] px-6 py-16 lg:px-12 lg:py-24"><SectionHeading section={section}/>{section.body?<p className="mt-6 max-w-[800px] whitespace-pre-line text-[17px] leading-8 opacity-72">{section.body}</p>:null}</div></section>;
    if(section.type==="image_text")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className={`mx-auto grid max-w-[1500px] gap-10 px-6 py-16 lg:grid-cols-2 lg:items-center lg:px-12 lg:py-20 ${section.imageSide==="left"?"":""}`}><div className={section.imageSide==="left"?"lg:order-2":""}><SectionHeading section={section}/>{section.body?<p className="mt-5 max-w-[650px] whitespace-pre-line text-[16px] leading-7 opacity-72">{section.body}</p>:null}{section.ctaLabel&&section.ctaHref?<Link href={section.ctaHref} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#7e3518] px-6 py-3 text-sm font-medium text-white">{section.ctaLabel}<ArrowUpRight size={15}/></Link>:null}</div><div className={`min-h-[360px] overflow-hidden rounded-[28px] border border-current/10 bg-black/5 ${section.imageSide==="left"?"lg:order-1":""}`}>{section.imageUrl?<img src={section.imageUrl} alt={section.imageAlt||""} className="h-full min-h-[360px] w-full object-cover"/>:<div className="grid min-h-[360px] place-items-center text-sm opacity-40">Ajoutez une image depuis le Control Center</div>}</div></div></section>;
    if(section.type==="cards")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto max-w-[1500px] px-6 py-16 lg:px-12 lg:py-20"><SectionHeading section={section}/><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(section.items??[]).map((item,index)=><article key={`${section.id}-${index}`} className="rounded-[24px] border border-current/10 bg-white/20 p-6 backdrop-blur-[1px]"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#f2d9c7] text-sm text-[#8d3b19]">{String(index+1).padStart(2,"0")}</div><h3 className="moony-serif mt-5 text-3xl">{item.title}</h3><p className="mt-3 text-sm leading-6 opacity-68">{item.body}</p></article>)}</div></div></section>;
    if(section.type==="stats")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto max-w-[1500px] px-6 py-14 lg:px-12"><SectionHeading section={section}/><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(section.items??[]).map((item,index)=><div key={`${section.id}-${index}`} className="border-l border-current/18 px-5 py-3"><strong className="moony-serif block text-5xl font-normal">{item.value}</strong><span className="mt-2 block text-sm opacity-60">{item.label}</span></div>)}</div></div></section>;
    if(section.type==="cta")return <section key={section.id} className={`${tone} border-t border-white/10`}><div className="mx-auto flex max-w-[1500px] flex-col gap-6 px-6 py-14 lg:flex-row lg:items-center lg:justify-between lg:px-12"><div className="max-w-[800px]"><SectionHeading section={section}/>{section.body?<p className="mt-4 text-sm leading-6 opacity-68">{section.body}</p>:null}</div>{section.ctaLabel&&section.ctaHref?<Link href={section.ctaHref} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full border border-current/30 px-7 py-3.5 text-sm font-medium">{section.ctaLabel}<ArrowUpRight size={15}/></Link>:null}</div></section>;
    if(section.type==="quote")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto max-w-[1050px] px-6 py-20 text-center lg:px-12"><span className="moony-serif text-5xl opacity-30">“</span><blockquote className="moony-serif mt-2 whitespace-pre-line text-[38px] italic leading-[1.12] tracking-[-.025em] sm:text-[48px]">{section.body}</blockquote></div></section>;
    if(section.type==="faq")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto grid max-w-[1500px] gap-8 px-6 py-16 lg:grid-cols-[.55fr_1.45fr] lg:px-12"><div><SectionHeading section={section}/></div><div className="divide-y divide-current/12 border-y border-current/12">{(section.items??[]).map((item,index)=><details key={`${section.id}-${index}`} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium"><span>{item.title}</span><span className="text-xl transition group-open:rotate-45">+</span></summary><p className="max-w-[850px] pt-3 text-sm leading-6 opacity-65">{item.body}</p></details>)}</div></div></section>;
    if(section.type==="testimonials")return <section key={section.id} className="border-t border-[#5b2f22]/8 bg-[#fffaf4] text-[#5b2f22]"><div className="mx-auto max-w-[1500px] px-6 py-16 lg:px-12"><SectionHeading section={section}/><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{testimonials.map(item=><article key={item.id} className="rounded-[24px] border border-[#5b2f22]/10 bg-white p-6"><div className="text-amber-500">{"★".repeat(item.rating??5)}</div><p className="moony-serif mt-4 text-2xl leading-tight">« {item.quote} »</p><p className="mt-5 text-xs font-semibold">{item.author_name}</p><p className="mt-1 text-[11px] text-[#5b2f22]/45">{[item.author_role,item.author_location].filter(Boolean).join(" · ")}</p></article>)}{!testimonials.length?<p className="col-span-full py-6 text-sm text-[#5b2f22]/45">Les témoignages approuvés et autorisés apparaîtront ici.</p>:null}</div></div></section>;
    if(section.type==="partners")return <section key={section.id} className="border-t border-[#5b2f22]/8 bg-[#f8eee7] text-[#5b2f22]"><div className="mx-auto max-w-[1500px] px-6 py-14 lg:px-12"><SectionHeading section={section}/><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{partners.map(item=><a key={item.id} href={item.website_url||undefined} target={item.website_url?"_blank":undefined} rel="noreferrer" className="grid min-h-24 place-items-center rounded-xl border border-[#5b2f22]/9 bg-white p-4 text-center text-xs font-semibold">{item.logo_url?<img src={item.logo_url} alt={item.name} className="max-h-12 max-w-full object-contain"/>:item.name}</a>)}{!partners.length?<p className="col-span-full py-6 text-sm text-[#5b2f22]/45">Les partenaires publiés apparaîtront ici.</p>:null}</div></div></section>;
    if(section.type==="newsletter")return <section key={section.id} className={`${tone} border-t border-[#5b2f22]/8`}><div className="mx-auto grid max-w-[1300px] gap-7 px-6 py-16 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-12"><div><SectionHeading section={section}/>{section.body?<p className="mt-4 max-w-[650px] text-sm leading-6 opacity-68">{section.body}</p>:null}</div><form action="/api/newsletter" method="post" className="flex flex-col gap-2 rounded-[22px] border border-current/10 bg-white/25 p-3 sm:flex-row"><label className="sr-only" htmlFor={`newsletter-${section.id}`}>Votre e-mail</label><input id={`newsletter-${section.id}`} name="email" type="email" required placeholder="votre@email.com" className="min-w-0 flex-1 rounded-full border border-[#5b2f22]/12 bg-white px-5 py-3 text-sm text-[#5b2f22] outline-none"/><button className="inline-flex items-center justify-center gap-2 rounded-full bg-[#7e3518] px-6 py-3 text-sm font-medium text-white"><Mail size={15}/>S’inscrire</button></form></div></section>;
    return null;
  })}</div>;
}
