"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Printer, ShieldCheck, XCircle } from "lucide-react";
import type { ProposalPortalDocument } from "@/lib/crm-proposal-portal";

const labels:Record<string,string>={draft:"Brouillon",sent:"Envoyée",viewed:"Consultée",accepted:"Acceptée",rejected:"Refusée",expired:"Expirée",superseded:"Remplacée"};
function money(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0))}catch{return`${Math.round(Number(value||0)).toLocaleString("fr-FR")} ${currency}`}}
function date(value:string|null){if(!value)return"—";return new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(`${value.includes("T")?value:value+"T12:00:00Z"}`))}
function company(document:ProposalPortalDocument){return document.lead?.company||`${document.lead?.first_name||""} ${document.lead?.last_name||""}`.trim()||"Client MOONY"}

export function ProposalDocumentView({document,clientActions=false,onDecision,busy=false}:{document:ProposalPortalDocument;clientActions?:boolean;onDecision?:(action:"accept"|"reject",name:string,email:string,message:string)=>void;busy?:boolean}){
  const [decision,setDecision]=useState<"accept"|"reject"|null>(null);const [name,setName]=useState(document.proposal.response_name||document.primaryContact?.name||"");const [email,setEmail]=useState(document.proposal.response_email||document.proposal.sent_to_email||document.primaryContact?.email||document.lead?.email||"");const [message,setMessage]=useState(document.proposal.response_message||"");
  const status=document.proposal.status;const canRespond=clientActions&&["sent","viewed"].includes(status);
  return <div className="min-h-screen bg-[#f8f0e5] px-4 py-8 text-[#3d241c] print:bg-white print:p-0">
    <div className="mx-auto max-w-[960px] print:max-w-none">
      <div className="mb-4 flex items-center justify-between gap-3 print:hidden"><div className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-2 text-[11px] text-[#5b2f22]/65"><ShieldCheck size={14}/> Espace sécurisé MOONY</div><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-full border border-[#5b2f22]/15 bg-white px-4 py-2 text-xs font-medium"><Printer size={14}/> Imprimer / PDF</button></div>
      <article className="overflow-hidden rounded-[34px] border border-[#d9c0ac] bg-[#fffaf4] shadow-[0_24px_80px_rgba(91,47,34,.12)] print:rounded-none print:border-0 print:shadow-none">
        <header className="relative overflow-hidden bg-[#2d1812] px-8 py-10 text-[#fffaf4] md:px-14 md:py-14"><div className="absolute -right-24 -top-28 h-72 w-72 rounded-full border border-[#e9b78f]/20"/><div className="absolute -right-10 -top-14 h-48 w-48 rounded-full border border-[#e9b78f]/25"/><div className="relative"><div className="text-[30px] font-semibold tracking-[.18em]">MOONY</div><p className="mt-2 text-[10px] uppercase tracking-[.25em] text-[#e9b78f]">Proposition commerciale</p><div className="mt-12 grid gap-7 md:grid-cols-[1fr_auto]"><div><p className="text-xs text-[#e8d7ca]">Préparée pour</p><h1 className="mt-2 max-w-2xl font-serif text-4xl font-normal leading-tight md:text-5xl">{company(document)}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#eadfd8]">{document.proposal.title}</p></div><div className="self-end text-left md:text-right"><p className="text-[10px] uppercase tracking-[.18em] text-[#c9a891]">Référence</p><strong className="mt-1 block text-lg">{document.proposal.reference}</strong><p className="mt-4 text-[10px] uppercase tracking-[.18em] text-[#c9a891]">Version</p><strong className="mt-1 block">V{document.proposal.version}</strong></div></div></div></header>

        <div className="px-8 py-9 md:px-14 md:py-12">
          <div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-[#f3e4d3] p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#7f6154]">Montant total</p><strong className="mt-2 block font-serif text-3xl font-normal text-[#7e3518]">{money(document.proposal.total_amount,document.proposal.currency)}</strong></div><div className="rounded-2xl border border-[#5b2f22]/10 p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#7f6154]">Validité</p><strong className="mt-2 block text-sm">Jusqu’au {date(document.proposal.valid_until)}</strong></div><div className="rounded-2xl border border-[#5b2f22]/10 p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#7f6154]">Statut</p><strong className="mt-2 block text-sm">{labels[status]||status}</strong></div></div>

          {document.proposal.introduction?<section className="mt-10"><p className="text-[10px] uppercase tracking-[.18em] text-[#9d4c27]">Notre proposition</p><div className="mt-4 whitespace-pre-wrap font-serif text-xl leading-9 text-[#5b2f22]">{document.proposal.introduction}</div></section>:null}

          <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#9d4c27]">Offre</p><h2 className="mt-2 font-serif text-3xl font-normal">Détail de la proposition</h2></div></div><div className="mt-5 overflow-hidden rounded-2xl border border-[#5b2f22]/10"><div className="hidden grid-cols-[1fr_100px_140px] gap-3 bg-[#f3e4d3] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.12em] text-[#76594d] md:grid"><span>Prestation</span><span>Qté</span><span className="text-right">Montant</span></div>{document.items.length?document.items.map((item)=><div key={item.id} className="grid gap-2 border-t border-[#5b2f22]/8 px-5 py-4 first:border-t-0 md:grid-cols-[1fr_100px_140px] md:gap-3"><div><strong className="text-sm">{item.name}</strong>{item.description?<p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/50">{item.description}</p>:null}<p className="mt-1 text-[9px] text-[#5b2f22]/40">{money(item.unit_price,document.proposal.currency)} / unité · remise {item.discount_percent}%</p></div><span className="text-xs md:pt-1">{item.quantity}</span><strong className="text-sm md:pt-1 md:text-right">{money(item.total_amount,document.proposal.currency)}</strong></div>):<div className="p-5 text-sm">Montant forfaitaire de la proposition.</div>}</div><div className="ml-auto mt-5 max-w-sm space-y-2 text-sm"><div className="flex justify-between"><span className="text-[#5b2f22]/55">Sous-total</span><span>{money(document.proposal.subtotal,document.proposal.currency)}</span></div>{document.proposal.discount_amount>0?<div className="flex justify-between"><span className="text-[#5b2f22]/55">Remise</span><span>- {money(document.proposal.discount_amount,document.proposal.currency)}</span></div>:null}{document.proposal.tax_amount>0?<div className="flex justify-between"><span className="text-[#5b2f22]/55">Taxes</span><span>{money(document.proposal.tax_amount,document.proposal.currency)}</span></div>:null}<div className="flex justify-between border-t border-[#5b2f22]/12 pt-3 font-serif text-xl"><span>Total</span><strong className="font-normal text-[#7e3518]">{money(document.proposal.total_amount,document.proposal.currency)}</strong></div></div></section>

          {document.proposal.terms?<section className="mt-10 rounded-2xl bg-[#f8f0e5] p-6"><p className="text-[10px] uppercase tracking-[.18em] text-[#9d4c27]">Conditions</p><div className="mt-3 whitespace-pre-wrap text-xs leading-6 text-[#5b2f22]/70">{document.proposal.terms}</div></section>:null}

          {status==="accepted"?<div className="mt-10 rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 text-emerald-700"/><div><strong className="text-emerald-800">Proposition acceptée</strong><p className="mt-1 text-xs leading-5 text-emerald-700">Merci. Votre décision a été enregistrée{document.proposal.response_name?` au nom de ${document.proposal.response_name}`:""}. L’équipe MOONY peut maintenant poursuivre les prochaines étapes.</p></div></div></div>:null}
          {status==="rejected"?<div className="mt-10 rounded-2xl border border-red-100 bg-red-50 p-6"><div className="flex gap-3"><XCircle className="mt-0.5 text-red-600"/><div><strong className="text-red-700">Proposition refusée</strong><p className="mt-1 text-xs leading-5 text-red-600">Votre réponse a bien été enregistrée. L’équipe MOONY pourra reprendre contact si nécessaire.</p></div></div></div>:null}
          {status==="expired"?<div className="mt-10 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Cette proposition a dépassé sa date de validité. Contactez l’équipe MOONY pour recevoir une nouvelle version.</div>:null}

          {canRespond?<section className="mt-10 border-t border-[#5b2f22]/10 pt-8 print:hidden"><p className="text-[10px] uppercase tracking-[.18em] text-[#9d4c27]">Votre décision</p><h2 className="mt-2 font-serif text-3xl font-normal">Répondre à la proposition</h2>{decision?<div className="mt-5 rounded-2xl bg-[#f8f0e5] p-5"><div className="grid gap-3 md:grid-cols-2"><label className="text-[10px] text-[#5b2f22]/55">Nom complet<input value={name} onChange={(e)=>setName(e.target.value)} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 bg-white px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/55">E-mail<input value={email} onChange={(e)=>setEmail(e.target.value)} type="email" className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 bg-white px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/55 md:col-span-2">Message (optionnel)<textarea rows={3} value={message} onChange={(e)=>setMessage(e.target.value)} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 bg-white px-3 py-2.5 text-sm" placeholder={decision==="reject"?"Vous pouvez préciser ce qui doit être ajusté.":"Un commentaire pour l’équipe MOONY…"}/></label></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>onDecision?.(decision,name,email,message)} className={`inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-medium text-white ${decision==="accept"?"bg-emerald-700":"bg-[#9c3b32]"}`}>{busy?<Loader2 size={14} className="animate-spin"/>:decision==="accept"?<CheckCircle2 size={14}/>:<XCircle size={14}/>}Confirmer {decision==="accept"?"l’acceptation":"le refus"}</button><button disabled={busy} onClick={()=>setDecision(null)} className="rounded-full border border-[#5b2f22]/15 bg-white px-5 py-2.5 text-sm">Annuler</button></div></div>:<div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>setDecision("accept")} className="inline-flex items-center gap-2 rounded-full bg-emerald-700 px-6 py-3 text-sm font-semibold text-white"><CheckCircle2 size={16}/> Accepter la proposition</button><button onClick={()=>setDecision("reject")} className="inline-flex items-center gap-2 rounded-full border border-[#9c3b32]/30 bg-white px-6 py-3 text-sm font-semibold text-[#9c3b32]"><XCircle size={16}/> Refuser</button></div>}</section>:null}

          <footer className="mt-12 border-t border-[#5b2f22]/10 pt-6 text-[10px] leading-5 text-[#5b2f22]/45"><div className="font-semibold tracking-[.16em] text-[#5b2f22]">MOONY</div><p>Pour la santé des femmes, à chaque étape de leur vie.</p><p className="mt-2">Document commercial confidentiel · {document.proposal.reference}</p></footer>
        </div>
      </article>
    </div>
  </div>
}

export function PublicProposalPortal({proposalId,token}:{proposalId:string;token:string}){
  const [document,setDocument]=useState<ProposalPortalDocument|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function load(){setLoading(true);setError("");try{const response=await fetch(`/api/proposals/${encodeURIComponent(proposalId)}?token=${encodeURIComponent(token)}`,{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Cette proposition est indisponible.");return}setDocument(payload.document)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[proposalId,token]);
  async function decide(action:"accept"|"reject",name:string,email:string,message:string){setBusy(true);setError("");try{const response=await fetch(`/api/proposals/${encodeURIComponent(proposalId)}?token=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,name,email,message})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Impossible d’enregistrer votre décision.");return}if(payload.document)setDocument(payload.document)}finally{setBusy(false)}}
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#f8f0e5] text-[#5b2f22]"><div className="text-center"><Loader2 className="mx-auto animate-spin"/><p className="mt-3 text-sm">Ouverture de votre proposition MOONY…</p></div></div>;
  if(error&&!document)return <div className="grid min-h-screen place-items-center bg-[#f8f0e5] p-6"><div className="max-w-lg rounded-3xl border border-[#d9c0ac] bg-[#fffaf4] p-8 text-center text-[#5b2f22]"><div className="text-2xl font-semibold tracking-[.16em]">MOONY</div><h1 className="mt-8 font-serif text-3xl">Proposition indisponible</h1><p className="mt-3 text-sm leading-6 text-[#5b2f22]/60">{error}</p></div></div>;
  return <>{error?<div className="fixed left-1/2 top-4 z-50 -translate-x-1/2 rounded-full bg-[#8b312b] px-5 py-2 text-xs text-white shadow-xl print:hidden">{error}</div>:null}{document?<ProposalDocumentView document={document} clientActions onDecision={decide} busy={busy}/>:null}</>
}
