"use client";

import { FormEvent, useState } from "react";

export function TestimonialForm(){
 const [form,setForm]=useState({authorName:"",email:"",authorLocation:"",authorRole:"",quote:"",rating:5,consentToPublish:false,website:""});const [message,setMessage]=useState("");const [sending,setSending]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setSending(true);setMessage("");const r=await fetch("/api/testimonials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setSending(false);if(!r.ok){setMessage(d.error??"Une erreur est survenue.");return;}setForm({authorName:"",email:"",authorLocation:"",authorRole:"",quote:"",rating:5,consentToPublish:false,website:""});setMessage("Merci. Votre témoignage a bien été reçu et sera relu avant toute publication.");}
 return <form onSubmit={submit} className="rounded-[28px] border border-[#5b2f22]/10 bg-white p-6 shadow-[0_20px_70px_rgba(84,42,28,.07)] sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Votre nom<input required value={form.authorName} onChange={e=>setForm({...form,authorName:e.target.value})} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3 outline-none focus:border-[#9d4c27]/50"/></label><label className="text-sm">Votre e-mail<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3 outline-none focus:border-[#9d4c27]/50"/></label><label className="text-sm">Ville / pays <span className="text-[#5b2f22]/40">(facultatif)</span><input value={form.authorLocation} onChange={e=>setForm({...form,authorLocation:e.target.value})} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3"/></label><label className="text-sm">Profil <span className="text-[#5b2f22]/40">(facultatif)</span><input value={form.authorRole} onChange={e=>setForm({...form,authorRole:e.target.value})} placeholder="Utilisatrice, maman, professionnelle…" className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3"/></label></div><label className="mt-4 block text-sm">Votre témoignage<textarea required rows={7} value={form.quote} onChange={e=>setForm({...form,quote:e.target.value})} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3 leading-6"/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">Votre note<select value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-[#5b2f22]/12 px-4 py-3">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label className="hidden">Site<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></label></div><label className="mt-5 flex items-start gap-3 text-xs leading-5 text-[#5b2f22]/65"><input type="checkbox" required checked={form.consentToPublish} onChange={e=>setForm({...form,consentToPublish:e.target.checked})} className="mt-1"/><span>J’autorise MOONY à examiner ce témoignage en vue d’une publication. Il ne sera visible sur le site qu’après validation par l’équipe.</span></label><button disabled={sending} className="mt-6 rounded-full bg-[#7e3518] px-7 py-3.5 text-sm font-semibold text-white disabled:opacity-60">{sending?"Envoi…":"Envoyer mon témoignage"}</button>{message?<p className="mt-4 text-sm leading-6 text-[#5b2f22]/65">{message}</p>:null}</form>;
}
