export const CRM_CURRENCIES=["EUR","XOF","CDF","GHS","CAD","USD"] as const;
export type CrmCurrency=typeof CRM_CURRENCIES[number];
export const CRM_CURRENCY_META:Record<CrmCurrency,{label:string;symbol:string}>={
 EUR:{label:"Euro",symbol:"€"},XOF:{label:"Franc CFA BCEAO",symbol:"F CFA"},CDF:{label:"Franc congolais",symbol:"FC"},GHS:{label:"Cedi ghanéen",symbol:"GH₵"},CAD:{label:"Dollar canadien",symbol:"$ CA"},USD:{label:"Dollar américain",symbol:"$ US"},
};
export type FxBundle={available:boolean;cacheAvailable:boolean;baseCurrency:CrmCurrency;rates:Record<string,number>;rateDates:Record<string,string>;providers:Record<string,string[]>;source:string;fetchedAt:string|null;requestedDate:string|null;defaultDisplayCurrency:CrmCurrency;refreshHours:number;error?:string};
const SOURCE="frankfurter_v2";
function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
function validCurrency(value:unknown):value is CrmCurrency{return CRM_CURRENCIES.includes(String(value||"").toUpperCase() as CrmCurrency)}
function defaults(){return{defaultDisplayCurrency:"XOF" as CrmCurrency,refreshHours:6}}
function fromSnapshot(row:any,settings:ReturnType<typeof defaults>,cacheAvailable=true):FxBundle{return{available:true,cacheAvailable,baseCurrency:"EUR",rates:{EUR:1,...(row?.rates||{})},rateDates:{...(row?.rate_dates||{})},providers:{...(row?.providers||{})},source:SOURCE,fetchedAt:row?.fetched_at||null,requestedDate:row?.requested_date||null,defaultDisplayCurrency:settings.defaultDisplayCurrency,refreshHours:settings.refreshHours}}
async function settingsFor(supabase:any){const result=await supabase.from("website_crm_fx_settings").select("default_display_currency,refresh_hours").eq("id","default").maybeSingle();if(result.error){if(missing(result.error))return{...defaults(),cacheAvailable:false};throw new Error(result.error.message)}return{defaultDisplayCurrency:validCurrency(result.data?.default_display_currency)?result.data.default_display_currency:"XOF",refreshHours:Math.max(1,Math.min(72,Number(result.data?.refresh_hours||6))),cacheAvailable:true}}
async function cached(supabase:any,date:string|null,refreshHours:number){let query=supabase.from("website_crm_fx_snapshots").select("*").eq("source",SOURCE).eq("base_currency","EUR");query=date?query.eq("requested_date",date):query.is("requested_date",null).order("fetched_at",{ascending:false}).limit(1);const result=await query;if(result.error){if(missing(result.error))return{row:null,cacheAvailable:false};throw new Error(result.error.message)}const row=result.data?.[0]||null;if(!row)return{row:null,cacheAvailable:true};if(date)return{row,cacheAvailable:true};const age=Date.now()-new Date(row.fetched_at).getTime();return{row:age<=refreshHours*3600000?row:null,cacheAvailable:true}}
async function fetchFrankfurter(date:string|null){const quotes=CRM_CURRENCIES.filter(code=>code!=="EUR").map(code=>code.toLowerCase()).join(",");const url=new URL("https://api.frankfurter.dev/v2/rates");url.searchParams.set("base","eur");url.searchParams.set("quotes",quotes);url.searchParams.set("expand","providers");if(date)url.searchParams.set("date",date);const response=await fetch(url,{cache:"no-store",headers:{Accept:"application/json"}});if(!response.ok){let detail="";try{detail=String((await response.json())?.message||"")}catch{}throw new Error(`FX provider ${response.status}${detail?`: ${detail}`:""}`)}const rows=await response.json() as Array<{date:string;base:string;quote:string;rate:number;providers?:string[]}>;const rates:Record<string,number>={EUR:1},rateDates:Record<string,string>={},providers:Record<string,string[]>={EUR:[]};for(const row of rows||[]){const quote=String(row.quote||"").toUpperCase();if(!validCurrency(quote))continue;const rate=Number(row.rate);if(!Number.isFinite(rate)||rate<=0)continue;rates[quote]=rate;rateDates[quote]=String(row.date||date||"");providers[quote]=Array.isArray(row.providers)?row.providers.map(String):[]}const missingQuotes=CRM_CURRENCIES.filter(code=>rates[code]==null);if(missingQuotes.length)throw new Error(`Taux indisponibles : ${missingQuotes.join(", ")}`);return{rates,rateDates,providers}}
export async function getFxBundle(supabase:any,options:{date?:string|null;forceRefresh?:boolean;actor?:string}={}):Promise<FxBundle>{const requestedDate=options.date&&/^\d{4}-\d{2}-\d{2}$/.test(options.date)?options.date:null;const settings=await settingsFor(supabase);if(!options.forceRefresh){const hit=await cached(supabase,requestedDate,settings.refreshHours);if(hit.row)return fromSnapshot(hit.row,settings,hit.cacheAvailable)}try{const fresh=await fetchFrankfurter(requestedDate);const now=new Date().toISOString(),row={requested_date:requestedDate,base_currency:"EUR",source:SOURCE,rates:fresh.rates,rate_dates:fresh.rateDates,providers:fresh.providers,fetched_at:now,fetched_by:options.actor||"MOONY FX",metadata:{api:"https://api.frankfurter.dev/v2/rates"}};if(settings.cacheAvailable){const saved=await supabase.from("website_crm_fx_snapshots").insert(row);if(saved.error&&saved.error.code!=="23505"&&!missing(saved.error))throw new Error(saved.error.message)}return{available:true,cacheAvailable:settings.cacheAvailable,baseCurrency:"EUR",rates:fresh.rates,rateDates:fresh.rateDates,providers:fresh.providers,source:SOURCE,fetchedAt:now,requestedDate,defaultDisplayCurrency:settings.defaultDisplayCurrency,refreshHours:settings.refreshHours}}catch(error){return{available:false,cacheAvailable:settings.cacheAvailable,baseCurrency:"EUR",rates:{EUR:1},rateDates:{},providers:{},source:SOURCE,fetchedAt:null,requestedDate,defaultDisplayCurrency:settings.defaultDisplayCurrency,refreshHours:settings.refreshHours,error:error instanceof Error?error.message:String(error)}}}
export function convertCurrency(amount:number,from:string,to:string,rates:Record<string,number>){const source=String(from||"").toUpperCase(),target=String(to||"").toUpperCase();if(source===target)return Number(amount||0);const sourceRate=source==="EUR"?1:Number(rates[source]),targetRate=target==="EUR"?1:Number(rates[target]);if(!Number.isFinite(sourceRate)||sourceRate<=0||!Number.isFinite(targetRate)||targetRate<=0)return null;return Number(amount||0)/sourceRate*targetRate}
export function formatCurrency(value:number,currency:string,maximumFractionDigits=0){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits}).format(Number(value||0))}catch{return`${Number(value||0).toLocaleString("fr-FR",{maximumFractionDigits})} ${currency}`}}
