type LifecycleResult={available:boolean;enabled:boolean;processed:number;alerts:number;runs:number;errors:string[]};
function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
function day(value:string|null|undefined){if(!value)return null;const parsed=new Date(`${value}T00:00:00Z`);return Number.isNaN(parsed.getTime())?null:Math.floor(parsed.getTime()/86400000)}
function accountOf(value:any){return Array.isArray(value)?value[0]:value}
async function beginRun(supabase:any,triggerType:"effective_soon"|"effective_due"|"unsigned_due",amendmentId:string,key:string,summary:string){const result=await supabase.from("website_crm_contract_lifecycle_runs").insert({trigger_type:triggerType,amendment_id:amendmentId,trigger_key:key,status:"success",summary}).select("id").single();if(result.error){if(result.error.code==="23505")return null;throw new Error(result.error.message)}return String(result.data.id)}
async function notify(supabase:any,id:string,key:string,title:string,subtitle:string,severity:"info"|"warning"|"urgent"){let count=0;for(const role of ["founder","admin","sales"]){const result=await supabase.from("control_center_generated_notifications").insert({target_role:role,title,subtitle,href:`/admin/customer-success/contracts?amendment=${id}`,severity,source_type:"crm_contract_lifecycle",source_id:key});if(!result.error)count+=1}return count}
export async function syncContractLifecycleAlerts(supabase:any):Promise<LifecycleResult>{
 const output:LifecycleResult={available:true,enabled:false,processed:0,alerts:0,runs:0,errors:[]};
 const settingsResult=await supabase.from("website_crm_contract_lifecycle_settings").select("*").eq("id","default").maybeSingle();if(settingsResult.error){if(missing(settingsResult.error))return {...output,available:false};throw new Error(settingsResult.error.message)}
 const settings=settingsResult.data??{enabled:false,upcoming_effective_days:14,unsigned_effective_grace_days:0};output.enabled=Boolean(settings.enabled);if(!output.enabled)return output;
 const result=await supabase.from("website_crm_contract_amendments").select("id,reference,title,kind,status,effective_date,website_crm_client_accounts(account_name)").in("status",["review","approved","signed"]).order("effective_date",{ascending:true});if(result.error){if(missing(result.error))return {...output,available:false};throw new Error(result.error.message)}
 const today=Math.floor(Date.now()/86400000),upcoming=Math.max(1,Number(settings.upcoming_effective_days||14)),grace=Math.max(0,Number(settings.unsigned_effective_grace_days||0));
 for(const amendment of result.data??[]){output.processed+=1;const effective=day(amendment.effective_date);if(effective===null)continue;const account=accountOf(amendment.website_crm_client_accounts);const label=account?.account_name||"Compte client";const delta=effective-today;
  if(amendment.status==="signed"&&delta<0){const key=`effective-due:${amendment.id}:${amendment.effective_date}`;const run=await beginRun(supabase,"effective_due",amendment.id,key,`${amendment.reference} doit être appliqué.`);if(run){output.runs+=1;output.alerts+=await notify(supabase,amendment.id,key,"Avenant signé à appliquer",`${label} · ${amendment.reference} · date d’effet ${amendment.effective_date}. Application manuelle requise.`,"urgent")}}
  else if(amendment.status==="signed"&&delta>=0&&delta<=upcoming){const key=`effective-soon:${amendment.id}:${amendment.effective_date}`;const run=await beginRun(supabase,"effective_soon",amendment.id,key,`${amendment.reference} prend bientôt effet.`);if(run){output.runs+=1;output.alerts+=await notify(supabase,amendment.id,key,"Avenant bientôt effectif",`${label} · ${amendment.reference} · effet le ${amendment.effective_date}. Aucun changement n’est appliqué automatiquement.`,"warning")}}
  else if(amendment.status!=="signed"&&today-effective>grace){const key=`unsigned-due:${amendment.id}:${amendment.effective_date}`;const run=await beginRun(supabase,"unsigned_due",amendment.id,key,`${amendment.reference} atteint sa date d’effet sans signature.`);if(run){output.runs+=1;output.alerts+=await notify(supabase,amendment.id,key,"Avenant non signé à clarifier",`${label} · ${amendment.reference} · date d’effet dépassée sans signature. Aucun terme n’a été modifié.`,"urgent")}}
 }
 return output;
}
