export type PortfolioTier="strategic"|"growth"|"standard"|"light_touch";
export type PortfolioPriority="urgent"|"high"|"medium"|"normal";
export type PortfolioAction={key:string;clientId:string;type:string;title:string;reason:string;priority:PortfolioPriority;score:number;dueAt:string|null;owner:string|null};

const DAY=86400000;
export function tierDefaultMonthlyEffort(tier:string|null|undefined){return tier==="strategic"?6:tier==="growth"?4:tier==="light_touch"?1:2}
export function monthlyEffort(account:any){const value=Number(account?.service_effort_hours_monthly);return Number.isFinite(value)&&value>=0?value:tierDefaultMonthlyEffort(account?.portfolio_tier)}
export function weeklyEffort(account:any){return Math.round(monthlyEffort(account)/4.345*10)/10}
function daysUntil(value:string|null|undefined,now=Date.now()){if(!value)return null;const time=new Date(value).getTime();if(Number.isNaN(time))return null;return Math.ceil((time-now)/DAY)}
function priorityFor(score:number):PortfolioPriority{return score>=85?"urgent":score>=60?"high":score>=35?"medium":"normal"}
function isoAfter(days:number){return new Date(Date.now()+days*DAY).toISOString()}
function dateKey(value:string|null|undefined){if(!value)return"none";const date=new Date(value);return Number.isNaN(date.getTime())?String(value).slice(0,10):date.toISOString().slice(0,10)}

export function computePortfolioPriority(input:{account:any;plan?:any|null;objectives?:any[];retentionCases?:any[];now?:number}){
 const {account,plan}=input;const objectives=input.objectives??[],retentionCases=input.retentionCases??[];const now=input.now??Date.now();let score=0;const reasons:string[]=[];
 if(account.portfolio_tier==="strategic"){score+=20;reasons.push("Compte stratégique")}else if(account.portfolio_tier==="growth"){score+=10;reasons.push("Compte croissance")}
 if(account.health_status==="critical"){score+=38;reasons.push("Santé client critique")}else if(account.health_status==="at_risk"){score+=28;reasons.push("Santé client à risque")}else if(account.health_status==="watch"){score+=8;reasons.push("Santé client à surveiller")}
 if(account.governance_status==="critical"){score+=28;reasons.push("Gouvernance critique")}else if(account.governance_status==="at_risk"){score+=20;reasons.push("Gouvernance à risque")}else if(account.governance_status==="watch"){score+=5;reasons.push("Gouvernance à surveiller")}
 const openRetention=retentionCases.filter((row)=>["open","in_progress"].includes(row.status));if(openRetention.some((row)=>row.priority==="urgent")){score+=35;reasons.push("Dossier anti-churn urgent")}else if(openRetention.length){score+=22;reasons.push("Dossier de rétention ouvert")}
 const renewalDays=daysUntil(account.renewal_date,now);if(renewalDays!=null&&renewalDays<=30){score+=28;reasons.push(`Renouvellement dans ${Math.max(0,renewalDays)} j`)}else if(renewalDays!=null&&renewalDays<=60){score+=18;reasons.push(`Renouvellement dans ${renewalDays} j`)}else if(renewalDays!=null&&renewalDays<=90){score+=8;reasons.push(`Renouvellement dans ${renewalDays} j`)}
 const reviewDays=daysUntil(plan?.next_review_at||account.next_success_review_at,now);if(reviewDays!=null&&reviewDays<0){score+=20;reasons.push("Revue client en retard")}else if(reviewDays!=null&&reviewDays<=14){score+=10;reasons.push("Revue client proche")}
 const blocked=objectives.filter((row)=>row.status==="blocked").length,atRisk=objectives.filter((row)=>row.status==="at_risk").length;if(blocked){score+=Math.min(20,blocked*10);reasons.push(`${blocked} objectif${blocked>1?"s":""} bloqué${blocked>1?"s":""}`)}else if(atRisk){score+=Math.min(15,atRisk*7);reasons.push(`${atRisk} objectif${atRisk>1?"s":""} à risque`)}
 if(!account.owner){score+=18;reasons.push("Responsable Customer Success non assigné")}
 score=Math.min(100,score);return{score,priority:priorityFor(score),reasons};
}

export function buildPortfolioActions(input:{account:any;plan?:any|null;objectives?:any[];retentionCases?:any[];now?:number}):PortfolioAction[]{
 const account=input.account,plan=input.plan??null,objectives=input.objectives??[],retentionCases=input.retentionCases??[],now=input.now??Date.now();const actions:PortfolioAction[]=[];const clientId=String(account.id),owner=account.owner||account.commercial_owner||null;const push=(action:Omit<PortfolioAction,"clientId"|"owner"|"priority">)=>actions.push({...action,clientId,owner,priority:priorityFor(action.score)});
 if(!account.owner)push({key:"assign-owner",type:"ownership",title:"Assigner un responsable Customer Success",reason:"Le compte n’a pas de responsable Customer Success explicite.",score:95,dueAt:isoAfter(1)});
 for(const item of retentionCases.filter((row)=>["open","in_progress"].includes(row.status))){push({key:`retention:${item.id}`,type:"retention",title:item.title||"Traiter le dossier de rétention",reason:item.priority==="urgent"?"Un dossier anti-churn urgent est ouvert.":"Un dossier de rétention est encore ouvert.",score:item.priority==="urgent"?100:82,dueAt:item.due_at||isoAfter(1)})}
 if(account.health_status==="critical"||account.health_status==="at_risk")push({key:`health:${account.health_status}:${new Date(now).toISOString().slice(0,7)}`,type:"health",title:"Définir le plan de récupération client",reason:account.health_summary||`Health score ${account.health_score}/100.`,score:account.health_status==="critical"?96:78,dueAt:isoAfter(account.health_status==="critical"?1:3)});
 if(account.governance_status==="critical"||account.governance_status==="at_risk")push({key:`governance:${account.governance_status}:${new Date(now).toISOString().slice(0,7)}`,type:"governance",title:"Renforcer la gouvernance du compte",reason:account.governance_summary||`Governance score ${account.governance_score}/100.`,score:account.governance_status==="critical"?88:68,dueAt:isoAfter(account.governance_status==="critical"?2:5)});
 const renewalDays=daysUntil(account.renewal_date,now);if(renewalDays!=null&&renewalDays<=60){push({key:`renewal:${dateKey(account.renewal_date)}`,type:"renewal",title:"Préparer le renouvellement",reason:`Échéance de renouvellement ${renewalDays<0?"dépassée":`dans ${renewalDays} jours`}.`,score:renewalDays<=15?92:renewalDays<=30?80:62,dueAt:renewalDays<=0?isoAfter(1):new Date(Math.min(new Date(account.renewal_date).getTime(),now+7*DAY)).toISOString()})}
 const reviewAt=plan?.next_review_at||account.next_success_review_at,reviewDays=daysUntil(reviewAt,now);if(reviewDays!=null&&reviewDays<=14){push({key:`review:${dateKey(reviewAt)}`,type:"review",title:"Préparer la revue de succès",reason:reviewDays<0?"La revue client est en retard.":`Revue prévue dans ${reviewDays} jours.`,score:reviewDays<0?78:55,dueAt:reviewAt||isoAfter(3)})}
 const blocked=objectives.filter((row)=>row.status==="blocked"),atRisk=objectives.filter((row)=>row.status==="at_risk");if(blocked.length||atRisk.length){const rows=blocked.length?blocked:atRisk;push({key:`objectives:${rows.map((row)=>row.id).sort().join("-")}`,type:"success_plan",title:blocked.length?"Débloquer les objectifs du Success Plan":"Recaler les objectifs à risque",reason:rows.map((row)=>row.title).slice(0,3).join(" · "),score:blocked.length?72:52,dueAt:isoAfter(blocked.length?3:7)})}
 if(account.portfolio_tier==="strategic"&&!plan)push({key:"strategic-success-plan",type:"success_plan",title:"Formaliser le Success Plan stratégique",reason:"Ce compte est classé stratégique mais ne possède pas encore de Success Plan.",score:65,dueAt:isoAfter(7)});
 return actions.sort((a,b)=>b.score-a.score||new Date(a.dueAt||"2999-01-01").getTime()-new Date(b.dueAt||"2999-01-01").getTime());
}

async function notifyOnce(supabase:any,sourceId:string,title:string,subtitle:string,severity:"info"|"warning"|"urgent",href:string){const existing=await supabase.from("control_center_generated_notifications").select("id").eq("source_type","crm_executive_portfolio").eq("source_id",sourceId).limit(1);if(!existing.error&&existing.data?.length)return 0;let count=0;for(const role of ["founder","admin"]){const inserted=await supabase.from("control_center_generated_notifications").insert({target_role:role,title,subtitle,href,severity,source_type:"crm_executive_portfolio",source_id:sourceId});if(!inserted.error)count+=1}return count}

export async function syncExecutivePortfolioAlerts(supabase:any){
 const result={available:true,alerts:0,ownersChecked:0,strategicRisks:0,errors:[] as string[]};const accountsResult=await supabase.from("website_crm_client_accounts").select("id,account_name,status,owner,commercial_owner,portfolio_tier,service_effort_hours_monthly,health_score,health_status,governance_score,governance_status").eq("status","active").limit(1000);if(accountsResult.error){if(["42P01","42703"].includes(String(accountsResult.error.code||"")))return{...result,available:false};throw new Error(accountsResult.error.message)}
 const profilesResult=await supabase.from("website_crm_csm_capacity_profiles").select("owner_name,weekly_capacity_hours,active").eq("active",true);if(profilesResult.error){if(["42P01","42703"].includes(String(profilesResult.error.code||"")))return{...result,available:false};throw new Error(profilesResult.error.message)}
 const week=new Date().toISOString().slice(0,10);const accounts=accountsResult.data??[];
 for(const account of accounts.filter((row)=>row.portfolio_tier==="strategic"&&(["at_risk","critical"].includes(row.health_status)||["at_risk","critical"].includes(row.governance_status)))){try{const urgent=rowCritical(account);result.strategicRisks+=1;result.alerts+=await notifyOnce(supabase,`strategic:${account.id}:${week}`,urgent?"Compte stratégique critique":"Compte stratégique à sécuriser",`${account.account_name} · santé ${account.health_score}/100 · gouvernance ${account.governance_score}/100.`,urgent?"urgent":"warning",`/admin/customer-success/portfolio?client=${account.id}`)}catch(error){result.errors.push(`${account.account_name}: ${error instanceof Error?error.message:"Erreur alerte stratégique"}`)}}
 for(const profile of profilesResult.data??[]){const owner=String(profile.owner_name),capacity=Number(profile.weekly_capacity_hours||0);if(!capacity)continue;const owned=accounts.filter((row)=>(row.owner||row.commercial_owner)===owner);const load=owned.reduce((sum,row)=>sum+weeklyEffort(row),0);result.ownersChecked+=1;if(load>capacity){const pct=Math.round(load/capacity*100);result.alerts+=await notifyOnce(supabase,`capacity:${owner}:${week}`,"Capacité Customer Success dépassée",`${owner} · charge estimée ${load.toFixed(1)} h/semaine pour ${capacity.toFixed(1)} h configurées (${pct} %).`,pct>=120?"urgent":"warning","/admin/customer-success/portfolio")}}
 return result;
}
function rowCritical(account:any){return account.health_status==="critical"||account.governance_status==="critical"}
