"use client";

import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Eye, EyeOff, Link2, Plus, Save, Trash2 } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type NavItem={label:string;href:string;visible?:boolean};
type Navigation={items:NavItem[];primaryLabel:string;primaryHref:string;secondaryLabel:string;secondaryHref:string};
type FooterLink={label:string;href:string};
type FooterColumn={title:string;links:FooterLink[]};
type Footer={headline:string;body:string;primaryLabel:string;primaryHref:string;secondaryLabel:string;secondaryHref:string;columns:FooterColumn[];instagramUrl:string;linkedinUrl:string};

const defaultNavigation:Navigation={items:[{label:"Accueil",href:"/",visible:true},{label:"Notre mission",href:"/notre-mission",visible:true},{label:"Notre approche",href:"/notre-approche",visible:true},{label:"À propos",href:"/a-propos",visible:true},{label:"Nos services",href:"/services",visible:true},{label:"Communauté",href:"/communaute",visible:true},{label:"Ressources",href:"/ressources",visible:true}],primaryLabel:"Prendre rendez-vous",primaryHref:"/contact?objet=rendez-vous",secondaryLabel:"Se connecter",secondaryHref:"https://application.moony-africa.com"};
const defaultFooter:Footer={headline:"Pour la santé des femmes, à chaque étape de leur vie.",body:"Une expérience de santé féminine pensée pour être utile, rassurante et accessible, avec une ambition africaine et une ouverture sur le monde.",primaryLabel:"Accéder à l’application",primaryHref:"https://application.moony-africa.com",secondaryLabel:"Nous contacter",secondaryHref:"/contact",columns:[{title:"Découvrir",links:[{label:"Notre mission",href:"/notre-mission"},{label:"Notre approche",href:"/notre-approche"},{label:"Nos services",href:"/services"},{label:"Communauté",href:"/communaute"},{label:"Ressources",href:"/ressources"}]},{title:"Confiance",links:[{label:"Protection des données",href:"/confidentialite"},{label:"Sécurité",href:"/confidentialite#securite"},{label:"Service client",href:"/support"},{label:"Méthode & qualité",href:"/notre-approche"},{label:"Professionnels de santé",href:"/services#professionnels"}]},{title:"Entreprise",links:[{label:"À propos",href:"/a-propos"},{label:"Partenariats",href:"/contact?objet=partenariat"},{label:"Presse",href:"/presse"},{label:"Carrières",href:"/carrieres"},{label:"Nous contacter",href:"/contact"}]}],instagramUrl:"",linkedinUrl:""};

function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T}
function move<T>(items:T[],index:number,direction:-1|1){const next=[...items];const target=index+direction;if(target<0||target>=next.length)return next;[next[index],next[target]]=[next[target],next[index]];return next}

export default function NavigationPage(){
 const [navigation,setNavigation]=useState<Navigation>(clone(defaultNavigation));const [footer,setFooter]=useState<Footer>(clone(defaultFooter));const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const r=await fetch("/api/admin/settings",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();setNavigation({...defaultNavigation,...(d.settings?.navigation??{}),items:Array.isArray(d.settings?.navigation?.items)?d.settings.navigation.items:defaultNavigation.items});setFooter({...defaultFooter,...(d.settings?.footer??{}),columns:Array.isArray(d.settings?.footer?.columns)?d.settings.footer.columns:defaultFooter.columns});setLoading(false)}
 async function save(){setSaving(true);setNotice("Enregistrement…");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({navigation,footer})});const d=await r.json().catch(()=>({}));setNotice(r.ok?"Navigation et footer enregistrés. Le site public utilise maintenant ces réglages.":d.error??"Enregistrement impossible.");setSaving(false)}
 function navPatch(index:number,patch:Partial<NavItem>){setNavigation(current=>({...current,items:current.items.map((item,i)=>i===index?{...item,...patch}:item)}))}
 function removeNav(index:number){setNavigation(current=>({...current,items:current.items.filter((_,i)=>i!==index)}))}
 function addNav(){setNavigation(current=>({...current,items:[...current.items,{label:"Nouveau lien",href:"/",visible:true}]}))}
 function columnPatch(index:number,patch:Partial<FooterColumn>){setFooter(current=>({...current,columns:current.columns.map((column,i)=>i===index?{...column,...patch}:column)}))}
 function linkPatch(columnIndex:number,linkIndex:number,patch:Partial<FooterLink>){setFooter(current=>({...current,columns:current.columns.map((column,i)=>i===columnIndex?{...column,links:column.links.map((link,j)=>j===linkIndex?{...link,...patch}:link)}:column)}))}
 function addFooterLink(columnIndex:number){setFooter(current=>({...current,columns:current.columns.map((column,i)=>i===columnIndex?{...column,links:[...column.links,{label:"Nouveau lien",href:"/"}]}:column)}))}
 function removeFooterLink(columnIndex:number,linkIndex:number){setFooter(current=>({...current,columns:current.columns.map((column,i)=>i===columnIndex?{...column,links:column.links.filter((_,j)=>j!==linkIndex)}:column)}))}
 function addColumn(){setFooter(current=>({...current,columns:[...current.columns,{title:"Nouvelle colonne",links:[]}]}))}
 function removeColumn(index:number){setFooter(current=>({...current,columns:current.columns.filter((_,i)=>i!==index)}))}

 return <AdminWorkspace active="Navigation & Footer" title="Navigation & Footer" subtitle="Gérez le menu public, ses boutons, les colonnes du footer et les liens sociaux sans modifier le code." actions={<><a href="/" target="_blank" className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><Eye size={15}/>Voir le site</a><button onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white disabled:opacity-50"><Save size={15}/>{saving?"Enregistrement…":"Enregistrer"}</button></>}>
  {notice?<div className="mb-4 rounded-xl border border-[#5b2f22]/10 bg-[#f8eee7] px-4 py-3 text-sm text-[#5b2f22]/70">{notice}</div>:null}
  <div className="grid gap-4 2xl:grid-cols-[1fr_1fr]">
   <AdminCard title="Menu principal" action={<button onClick={addNav} className="inline-flex items-center gap-1.5 rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs"><Plus size={13}/>Ajouter un lien</button>}>
    <p className="mb-4 text-xs leading-5 text-[#5b2f22]/50">L’ordre affiché ici est l’ordre du menu desktop et mobile. Masquer un lien ne supprime pas sa page.</p>
    <div className="space-y-2">{navigation.items.map((item,index)=><div key={`${index}-${item.href}`} className="grid gap-2 rounded-xl border border-[#5b2f22]/10 bg-white p-3 sm:grid-cols-[38px_1fr_1.2fr_auto]"><div className="flex flex-col gap-1"><button disabled={index===0} onClick={()=>setNavigation(current=>({...current,items:move(current.items,index,-1)}))} className="grid h-7 w-8 place-items-center rounded border border-[#5b2f22]/10 disabled:opacity-25"><ArrowUp size={12}/></button><button disabled={index===navigation.items.length-1} onClick={()=>setNavigation(current=>({...current,items:move(current.items,index,1)}))} className="grid h-7 w-8 place-items-center rounded border border-[#5b2f22]/10 disabled:opacity-25"><ArrowDown size={12}/></button></div><label className="text-[11px]">Libellé<input value={item.label} onChange={e=>navPatch(index,{label:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[11px]">Lien<input value={item.href} onChange={e=>navPatch(index,{href:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><div className="flex items-end gap-1"><button title={item.visible===false?"Afficher":"Masquer"} onClick={()=>navPatch(index,{visible:item.visible===false})} className="grid h-10 w-10 place-items-center rounded-lg border border-[#5b2f22]/10">{item.visible===false?<EyeOff size={14}/>:<Eye size={14}/>}</button><button title="Supprimer" onClick={()=>removeNav(index)} className="grid h-10 w-10 place-items-center rounded-lg border border-red-100 text-red-600"><Trash2 size={14}/></button></div></div>)}</div>
   </AdminCard>

   <div className="space-y-4"><AdminCard title="Boutons du header"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs">Bouton principal<input value={navigation.primaryLabel} onChange={e=>setNavigation({...navigation,primaryLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="text-xs">Destination<input value={navigation.primaryHref} onChange={e=>setNavigation({...navigation,primaryHref:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="text-xs">Bouton secondaire<input value={navigation.secondaryLabel} onChange={e=>setNavigation({...navigation,secondaryLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="text-xs">Destination<input value={navigation.secondaryHref} onChange={e=>setNavigation({...navigation,secondaryHref:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label></div></AdminCard>
   <AdminCard title="Aperçu du menu"><div className="rounded-xl border border-[#5b2f22]/10 bg-[#fffaf4] p-4"><div className="flex flex-wrap items-center gap-4 text-xs"><strong className="moony-serif mr-3 text-xl">MOONY</strong>{navigation.items.filter(i=>i.visible!==false).map(item=><span key={`${item.label}-${item.href}`}>{item.label}</span>)}<span className="ml-auto rounded-full bg-[#7e3518] px-4 py-2 text-white">{navigation.primaryLabel}</span></div></div></AdminCard></div>
  </div>

  <div className="mt-4"><AdminCard title="Footer"><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><label className="block text-xs">Grand titre<textarea rows={3} value={footer.headline} onChange={e=>setFooter({...footer,headline:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3 text-sm"/></label><label className="block text-xs">Texte<textarea rows={4} value={footer.body} onChange={e=>setFooter({...footer,body:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">CTA principal<input value={footer.primaryLabel} onChange={e=>setFooter({...footer,primaryLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-xs">Lien<input value={footer.primaryHref} onChange={e=>setFooter({...footer,primaryHref:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-xs">CTA secondaire<input value={footer.secondaryLabel} onChange={e=>setFooter({...footer,secondaryLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-xs">Lien<input value={footer.secondaryHref} onChange={e=>setFooter({...footer,secondaryHref:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Instagram<input value={footer.instagramUrl} onChange={e=>setFooter({...footer,instagramUrl:e.target.value})} placeholder="https://instagram.com/…" className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-xs">LinkedIn<input value={footer.linkedinUrl} onChange={e=>setFooter({...footer,linkedinUrl:e.target.value})} placeholder="https://linkedin.com/company/…" className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label></div></div>
   <div><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#8d4b32]">Colonnes de liens</p><button onClick={addColumn} className="inline-flex items-center gap-1.5 rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs"><Plus size={12}/>Colonne</button></div><div className="grid gap-3 lg:grid-cols-3">{footer.columns.map((column,columnIndex)=><div key={columnIndex} className="rounded-xl border border-[#5b2f22]/10 bg-[#fffaf4] p-3"><div className="flex gap-2"><input value={column.title} onChange={e=>columnPatch(columnIndex,{title:e.target.value})} className="min-w-0 flex-1 rounded-lg border border-[#5b2f22]/10 px-2.5 py-2 text-xs font-semibold"/><button onClick={()=>removeColumn(columnIndex)} className="grid h-8 w-8 place-items-center rounded-lg border border-red-100 text-red-600"><Trash2 size={12}/></button></div><div className="mt-3 space-y-2">{column.links.map((link,linkIndex)=><div key={linkIndex} className="rounded-lg border border-[#5b2f22]/8 bg-white p-2"><div className="flex items-center gap-1"><Link2 size={11} className="shrink-0 text-[#5b2f22]/35"/><input value={link.label} onChange={e=>linkPatch(columnIndex,linkIndex,{label:e.target.value})} className="min-w-0 flex-1 border-0 bg-transparent text-xs font-medium outline-none"/><button onClick={()=>removeFooterLink(columnIndex,linkIndex)} className="text-red-500"><Trash2 size={11}/></button></div><input value={link.href} onChange={e=>linkPatch(columnIndex,linkIndex,{href:e.target.value})} className="mt-1 w-full border-0 bg-transparent text-[10px] text-[#5b2f22]/45 outline-none"/></div>)}<button onClick={()=>addFooterLink(columnIndex)} className="w-full rounded-lg border border-dashed border-[#5b2f22]/15 py-2 text-[10px] text-[#5b2f22]/50">+ Ajouter un lien</button></div></div>)}</div></div></div></AdminCard></div>

  <div className="mt-4 rounded-xl bg-[#321b14] p-7 text-white"><p className="text-[10px] uppercase tracking-[.2em] text-[#e9b78f]">Aperçu footer</p><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_1.2fr]"><div><h3 className="moony-serif whitespace-pre-line text-3xl">{footer.headline}</h3><p className="mt-3 max-w-lg text-xs leading-5 text-white/60">{footer.body}</p></div><div className="grid gap-5 sm:grid-cols-3">{footer.columns.map((column,i)=><div key={i}><strong className="text-[10px] uppercase tracking-[.15em] text-[#e9b78f]">{column.title}</strong><div className="mt-3 space-y-2 text-xs text-white/60">{column.links.map((link,j)=><p key={j}>{link.label}</p>)}</div></div>)}</div></div></div>
  {loading?<span className="sr-only">Chargement…</span>:null}
 </AdminWorkspace>;
}
