"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, BriefcaseBusiness, CalendarClock, CheckCircle2, Clock3, Gauge, Save, ShieldCheck, Sparkles, Target, UserRoundCog, UsersRound } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Priority={score:number;priority:"urgent"|"high"|"medium"|"normal";reasons:string[]};
type Plan={id:string;title:string;status:string;overall_progress:number;next_review_at:string|null}|null;
type Account={id:string;lead_id:string;account_name:string;status:string;owner:string|null;commercial_owner:string|null;renewal_date:string|null;next_success_review_at:string|null;health_score:number;health_status:string;health_summary:string|null;governance_score:number;governance_status:string;governance_summary:string|null;portfolio_tier:string;service_effort_hours_monthly:number|null;portfolio_notes:string|null;monthlyEffort:number;weeklyEffort:number;objectivesAtRisk:number;retentionOpen:number;openActions:number;priority:Priority;plan:Plan;website_leads:{email:string;country:string|null;company:string|null}|null;website_crm_opportunities:{name:string;amount:number;currency:string}|null};
type Capacity={ownerName:string;accounts:number;strategic:number;atRisk:number;weeklyLoad:number;configuredCapacity:number|null;utilization:number|null;notes?:string|null};
type Action={key:string;clientId:string;type:string;title:string;reason:string;priority:"urgent"|"high"|"medium"|"normal";score:number;dueAt:string|null;owner:string|null;state:string};
type Payload={available:boolean;accounts:Account[];capacity:Capacity[];actions:Action[];metrics:{active:number;strategic:number;attention:number;renewals60:number;unassigned:number;openActions:number};effortDefaults?:Record<string,number>};
const empty:Payload={available:true,accounts:[],capacity:[],actions:[],metrics:{active:0,strategic:0,attention:0,renewals60:0,unassigned:0,openActions:0}};
const tierLabels:Record<string,string>={strategic:"Stratégique",growth:"Croissance",standard:"Standard",light_touch:"Light-touch"};
const priorityLabels:Record<string,string>={urgent:"Urgent",high:"Haute",medium:"Moyenne",normal:"Normale"};
function fmtDate(value:string|null){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(d)}
function money(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0))}catch{return`${Math.round(Number(value||0)).toLocaleString("fr-FR")} ${currency}`}}
function priorityTone(priority:string){return priority==="urgent"?"bg-red-50 text-red-700":priority==="high"?"bg-orange-50 text-orange-700":priority==="medium"?"bg-amber-50 text-amber-700":"bg-[#f4e8de] text-[#7e3518]"}
function scoreTone(status:string){return status==="healthy"?"text-emerald-700":status==="watch"?"text-amber-700":status==="at_risk"?"text-orange-700":"text-red-700"}
function utilizationTone(value:number|null){if(value==null)return"text-[#5b2f22]/45";return value>=120?"text-red-700":value>100?"text-orange-700":value>=80?"text-amber-700":"text-emerald-700"}

export default function ExecutivePortfolioPage(){
 const [data,setData]=useState<Payload>(empty);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");const [search,setSearch]=useState("");const [tierFilter,setTierFilter]=useState("all");const [ownerFilter,setOwnerFilter]=useState("all");const [selectedId,setSelectedId]=useState("");const [profile,setProfile]=useState({portfolioTier:"standard",serviceEffortHoursMonthly:"",portfolioNotes:""});const [capacityDrafts,setCapacityDrafts]=useState<Record<string,string>>({});
 async function load(silent=false){if(!silent)setLoading(true);try{const response=await fetch("/api/admin/crm/executive-portfolio",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Impossible de charger le portefeuille exécutif.");return}const next={...empty,...payload} as Payload;setData(next);const requested=new URLSearchParams(location.search).get("client");setSelectedId((current)=>current&&next.accounts.some((row)=>row.id===current)?current:requested&&next.accounts.some((row)=>row.id===requested)?requested:next.accounts[0]?.id||"");setCapacityDrafts((current)=>{const copy={...current};for(const row of next.capacity)if(copy[row.ownerName]===undefined)copy[row.ownerName]=row.configuredCapacity==null?"":String(row.configuredCapacity);return copy})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const owners=useMemo(()=>[...new Set(data.accounts.map((row)=>row.owner||row.commercial_owner||"Non assigné"))].sort(),[data.accounts]);
 const visible=useMemo(()=>data.accounts.filter((row)=>{const owner=row.owner||row.commercial_owner||"Non assigné";return(tierFilter==="all"||row.portfolio_tier===tierFilter)&&(ownerFilter==="all"||owner===ownerFilter)&&[row.account_name,row.website_leads?.email,row.website_leads?.country,owner,row.website_crm_opportunities?.name].join(" ").toLowerCase().includes(search.toLowerCase())}).sort((a,b)=>b.priority.score-a.priority.score),[data.accounts,search,tierFilter,ownerFilter]);
 const selected=data.accounts.find((row)=>row.id===selectedId)||null;
 useEffect(()=>{if(!selected)return;setProfile({portfolioTier:selected.portfolio_tier||"standard",serviceEffortHoursMonthly:selected.service_effort_hours_monthly==null?"":String(selected.service_effort_hours_monthly),portfolioNotes:selected.portfolio_notes||""})},[selectedId,selected?.portfolio_tier,selected?.service_effort_hours_monthly]);
 async function act(action:string,body:Record<string,unknown>,message:string){setBusy(action);setNotice("");try{const response=await fetch("/api/admin/crm/executive-portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Action impossible.");return false}setNotice(message);await load(true);return true}finally{setBusy("")}}
 async function saveProfile(){if(!selected)return;await act("account_profile",{clientId:selected.id,portfolioTier:profile.portfolioTier,serviceEffortHoursMonthly:profile.serviceEffortHoursMonthly,portfolioNotes:profile.portfolioNotes},"Profil de portefeuille enregistré.")}
 async function saveCapacity(ownerName:string){const value=Number(capacityDrafts[ownerName]);if(!Number.isFinite(value)||value<=0){setNotice("Renseignez une capacité hebdomadaire supérieure à 0.");return}await act("capacity_profile",{ownerName,weeklyCapacityHours:value,active:true},`Capacité de ${ownerName} enregistrée.`)}
 async function queueState(item:Action,status:"done"|"snoozed"|"dismissed"){await act("action_state",{clientId:item.clientId,actionKey:item.key,status,snoozedUntil:status==="snoozed"?new Date(Date.now()+7*86400000).toISOString():null},status==="done"?"Action marquée terminée.":status==="snoozed"?"Action reportée de 7 jours.":"Action classée.")}
 async function createTask(item:Action){await act("create_task",{clientId:item.clientId,actionKey:item.key,title:item.title,priority:item.priority,dueAt:item.dueAt,reason:item.reason},"Tâche CRM créée et action retirée de la file.")}
 return <AdminWorkspace active="Portefeuille CS" title="Executive Portfolio & CSM Capacity" subtitle="Une vue direction pour arbitrer les comptes stratégiques, la santé client, la gouvernance, les renouvellements, les Success Plans et la capacité réelle de l’équipe Customer Success." actions={<><Link href="/admin/customer-success" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Customer Success</Link><Link href="/admin/customer-success/plans" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Plans de succès</Link><Link href="/admin/customer-success/governance" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Gouvernance</Link></>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911110000_crm_executive_portfolio_capacity.sql</strong> après CRM V8.3 pour activer le portefeuille exécutif.</div>:null}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><article className="admin-card admin-shadow p-4"><UsersRound size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{loading?"…":data.metrics.active}</strong><span className="text-[9px] text-[#5b2f22]/45">Clients actifs</span></article><article className="admin-card admin-shadow p-4"><Sparkles size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.strategic}</strong><span className="text-[9px] text-[#5b2f22]/45">Comptes stratégiques</span></article><article className="admin-card admin-shadow p-4"><AlertTriangle size={16} className="text-orange-600"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.attention}</strong><span className="text-[9px] text-[#5b2f22]/45">Comptes à sécuriser</span></article><article className="admin-card admin-shadow p-4"><CalendarClock size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.renewals60}</strong><span className="text-[9px] text-[#5b2f22]/45">Renouvellements ≤60 j</span></article><article className="admin-card admin-shadow p-4"><UserRoundCog size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.unassigned}</strong><span className="text-[9px] text-[#5b2f22]/45">Sans responsable CS</span></article><article className="admin-card admin-shadow p-4"><Target size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-2xl font-normal">{data.metrics.openActions}</strong><span className="text-[9px] text-[#5b2f22]/45">Actions prioritaires</span></article></div>
  <div className="mt-5 grid gap-4 2xl:grid-cols-[1.25fr_.75fr]">
   <AdminCard title="File d’actions hebdomadaire" action={<span className="text-[10px] text-[#5b2f22]/45">{data.actions.length} action{data.actions.length>1?"s":""}</span>}><div className="space-y-2">{data.actions.slice(0,18).map((item)=>{const account=data.accounts.find((row)=>row.id===item.clientId);return <article key={`${item.clientId}-${item.key}`} className="rounded-xl border border-[#5b2f22]/8 bg-[#fffaf6] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] ${priorityTone(item.priority)}`}>{priorityLabels[item.priority]} · {item.score}</span><strong className="text-xs">{item.title}</strong></div><p className="mt-2 text-[10px] text-[#5b2f22]/60">{account?.account_name||"Compte client"} · {item.reason}</p><p className="mt-1 text-[9px] text-[#5b2f22]/40">Responsable {item.owner||"à assigner"} · échéance {fmtDate(item.dueAt)}</p></div><div className="flex flex-wrap gap-1.5"><button onClick={()=>void createTask(item)} disabled={busy==="create_task"} className="rounded-lg bg-[#2d1812] px-3 py-2 text-[9px] text-white">Créer tâche</button><button onClick={()=>void queueState(item,"snoozed")} className="rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-[9px]">+7 jours</button><button onClick={()=>void queueState(item,"done")} className="rounded-lg border border-emerald-200 px-3 py-2 text-[9px] text-emerald-700">Fait</button></div></div></article>})}{!data.actions.length?<div className="rounded-xl bg-[#faf5f0] p-8 text-center text-xs text-[#5b2f22]/45"><CheckCircle2 size={22} className="mx-auto mb-2 text-emerald-600"/>Aucune action prioritaire ouverte.</div>:null}</div></AdminCard>
   <AdminCard title="Capacité CSM" action={<Gauge size={16} className="text-[#9d4c27]"/>}><div className="space-y-3">{data.capacity.map((row)=><div key={row.ownerName} className="rounded-xl border border-[#5b2f22]/8 p-4"><div className="flex items-start justify-between gap-3"><div><strong className="text-xs">{row.ownerName}</strong><p className="mt-1 text-[9px] text-[#5b2f22]/45">{row.accounts} compte{row.accounts>1?"s":""} · {row.strategic} stratégique{row.strategic>1?"s":""} · {row.atRisk} à sécuriser</p></div><span className={`text-xs font-semibold ${utilizationTone(row.utilization)}`}>{row.utilization==null?"Capacité non configurée":`${row.utilization}%`}</span></div><div className="mt-3 flex items-end gap-2"><label className="min-w-0 flex-1 text-[9px] text-[#5b2f22]/45">Charge estimée<strong className="mt-1 block text-sm text-[#2d1812]">{row.weeklyLoad.toFixed(1)} h / sem.</strong></label><label className="w-28 text-[9px] text-[#5b2f22]/45">Capacité<input type="number" min="1" max="168" step="0.5" value={capacityDrafts[row.ownerName]??""} onChange={(e)=>setCapacityDrafts((current)=>({...current,[row.ownerName]:e.target.value}))} placeholder="h/sem." className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-2 py-2 text-xs"/></label><button onClick={()=>void saveCapacity(row.ownerName)} className="rounded-lg bg-[#7e3518] p-2.5 text-white"><Save size={13}/></button></div>{row.configuredCapacity?<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eadfd6]"><div className={`h-full ${Number(row.utilization)>=120?"bg-red-500":Number(row.utilization)>100?"bg-orange-500":Number(row.utilization)>=80?"bg-amber-500":"bg-emerald-500"}`} style={{width:`${Math.min(100,Number(row.utilization||0))}%`}}/></div>:null}</div>)}</div><p className="mt-4 text-[9px] leading-4 text-[#5b2f22]/40">La capacité hebdomadaire est configurée manuellement. La charge utilise l’estimation propre au compte ; lorsqu’elle n’est pas renseignée, MOONY affiche une estimation transparente par niveau de portefeuille.</p></AdminCard>
  </div>
  <div className="mt-5 grid gap-4 2xl:grid-cols-[.62fr_1.38fr]">
   <section className="admin-card admin-shadow overflow-hidden"><div className="grid gap-2 border-b border-[#5b2f22]/8 p-4 sm:grid-cols-2"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Client, pays, responsable…" className="rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs sm:col-span-2"/><select value={tierFilter} onChange={(e)=>setTierFilter(e.target.value)} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-xs"><option value="all">Tous les niveaux</option>{Object.entries(tierLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={ownerFilter} onChange={(e)=>setOwnerFilter(e.target.value)} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-xs"><option value="all">Tous les responsables</option>{owners.map((owner)=><option key={owner} value={owner}>{owner}</option>)}</select></div><div className="max-h-[1100px] divide-y divide-[#5b2f22]/7 overflow-auto">{visible.map((row)=><button key={row.id} onClick={()=>setSelectedId(row.id)} className={`w-full p-4 text-left ${selectedId===row.id?"bg-[#f6e5d9]":"hover:bg-[#fffaf6]"}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{row.account_name}</strong><p className="mt-1 text-[9px] text-[#5b2f22]/45">{tierLabels[row.portfolio_tier]} · {row.owner||row.commercial_owner||"Non assigné"}</p></div><span className={`rounded-full px-2 py-1 text-[9px] ${priorityTone(row.priority.priority)}`}>{row.priority.score}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-[9px]"><span>Santé <strong className={scoreTone(row.health_status)}>{row.health_score}</strong></span><span>Gouv. <strong className={scoreTone(row.governance_status)}>{row.governance_score}</strong></span><span>Charge <strong>{row.weeklyEffort} h/s</strong></span></div></button>)}</div></section>
   {selected?<div className="space-y-4"><AdminCard title={selected.account_name} action={<span className={`rounded-full px-3 py-1.5 text-[10px] ${priorityTone(selected.priority.priority)}`}>Priorité {priorityLabels[selected.priority.priority]} · {selected.priority.score}/100</span>}><div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="rounded-2xl bg-[#2d1812] p-6 text-[#fffaf4]"><span className="text-[9px] uppercase tracking-[.16em] text-[#e9b78f]">Vue direction</span><strong className="moony-serif mt-2 block text-4xl font-normal">{tierLabels[selected.portfolio_tier]}</strong><div className="mt-5 grid grid-cols-2 gap-3 text-[10px]"><span>Santé<strong className="mt-1 block text-xl">{selected.health_score}/100</strong></span><span>Gouvernance<strong className="mt-1 block text-xl">{selected.governance_score}/100</strong></span><span>Success Plan<strong className="mt-1 block text-xl">{selected.plan?`${selected.plan.overall_progress}%`:"—"}</strong></span><span>Actions<strong className="mt-1 block text-xl">{selected.openActions}</strong></span></div></div><div><h3 className="text-xs font-semibold">Pourquoi ce compte remonte ici</h3><div className="mt-2 space-y-2">{selected.priority.reasons.length?selected.priority.reasons.map((reason)=><div key={reason} className="rounded-lg bg-[#faf5f0] px-3 py-2 text-[10px]">{reason}</div>):<div className="rounded-lg bg-emerald-50 px-3 py-2 text-[10px] text-emerald-700">Aucun signal prioritaire majeur.</div>}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 text-[10px] text-[#5b2f22]/55"><span>Renouvellement <strong className="block text-[#2d1812]">{fmtDate(selected.renewal_date)}</strong></span><span>Prochaine revue <strong className="block text-[#2d1812]">{fmtDate(selected.plan?.next_review_at||selected.next_success_review_at)}</strong></span><span>Valeur initiale <strong className="block text-[#2d1812]">{selected.website_crm_opportunities?money(selected.website_crm_opportunities.amount,selected.website_crm_opportunities.currency):"—"}</strong></span><span>Charge planifiée <strong className="block text-[#2d1812]">{selected.monthlyEffort} h/mois · {selected.weeklyEffort} h/sem.</strong></span></div></div></div></AdminCard>
    <AdminCard title="Profil de portefeuille" action={<button onClick={()=>void saveProfile()} disabled={busy==="account_profile"} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-3 py-2 text-[10px] text-white"><Save size={12}/> Enregistrer</button>}><div className="grid gap-3 md:grid-cols-2"><label className="text-[10px] text-[#5b2f22]/50">Niveau<select value={profile.portfolioTier} onChange={(e)=>setProfile((current)=>({...current,portfolioTier:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-xs">{Object.entries(tierLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-[10px] text-[#5b2f22]/50">Charge CS estimée · heures/mois<input type="number" min="0" max="500" step="0.5" value={profile.serviceEffortHoursMonthly} onChange={(e)=>setProfile((current)=>({...current,serviceEffortHoursMonthly:e.target.value}))} placeholder={`Défaut ${data.effortDefaults?.[profile.portfolioTier]??"—"} h/mois`} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs"/></label><label className="md:col-span-2 text-[10px] text-[#5b2f22]/50">Notes portefeuille<textarea value={profile.portfolioNotes} onChange={(e)=>setProfile((current)=>({...current,portfolioNotes:e.target.value}))} rows={4} placeholder="Contexte exécutif, enjeu du compte, arbitrages de capacité…" className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs"/></label></div><p className="mt-3 text-[9px] text-[#5b2f22]/40">Le niveau stratégique et la charge sont des décisions de pilotage explicitement saisies par l’équipe ; ils ne sont pas déduits de données sensibles.</p></AdminCard>
    <div className="grid gap-4 md:grid-cols-2"><AdminCard title="Health & rétention"><div className="space-y-2 text-[10px]"><div className="flex justify-between rounded-lg bg-[#faf5f0] p-3"><span>Health score</span><strong>{selected.health_score}/100</strong></div><div className="flex justify-between rounded-lg bg-[#faf5f0] p-3"><span>Dossiers rétention ouverts</span><strong>{selected.retentionOpen}</strong></div><p className="text-[#5b2f22]/45">{selected.health_summary||"Aucun résumé de risque santé client."}</p></div></AdminCard><AdminCard title="Gouvernance & Success Plan"><div className="space-y-2 text-[10px]"><div className="flex justify-between rounded-lg bg-[#faf5f0] p-3"><span>Governance score</span><strong>{selected.governance_score}/100</strong></div><div className="flex justify-between rounded-lg bg-[#faf5f0] p-3"><span>Objectifs à risque / bloqués</span><strong>{selected.objectivesAtRisk}</strong></div><p className="text-[#5b2f22]/45">{selected.governance_summary||"Aucun résumé de risque de gouvernance."}</p></div></AdminCard></div>
   </div>:null}
  </div>
 </AdminWorkspace>
}
