"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, Building2, CircleDollarSign, Download, Gauge, RefreshCw, Save, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { AdminWorkspace } from "@/components/admin-workspace";

type Metric={currency:string;currentMrr:number;currentArr:number;startingMrr:number;newMrr:number;expansionMrr:number;contractionMrr:number;churnMrr:number;nrr:number|null;grr:number|null;topClientShare:number;top5Share:number;invoicedMonth:number;collectedMonth:number;outstanding:number;overdue:number;overdueRatio:number;dso:number|null;aging:{current:number;d1_30:number;d31_60:number;d61_90:number;d90plus:number};clients:{total:number;new:number;expanded:number;contracted:number;churned:number}};
type Account={clientId:string;accountName:string;owner:string|null;country:string|null;currency:string;mrr:number;arr:number;share:number;subscriptions:number};
type Product={name:string;currency:string;mrr:number;arr:number;subscriptions:number};
type Trend={periodMonth:string;currency:string;mrr:number;arr:number;clients:number};
type Payload={available:boolean;baseline:{periodMonth:string;capturedAt:string|null}|null;currentMonth:string;currencies:Metric[];trend:Trend[];accounts:Account[];products:Product[];settings:any};
const empty:Payload={available:true,baseline:null,currentMonth:"",currencies:[],trend:[],accounts:[],products:[],settings:null};
function money(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:0}).format(value)}catch{return `${Math.round(value).toLocaleString("fr-FR")} ${currency}`}}
function pct(value:number|null){return value===null?"—":`${value.toFixed(1)}%`}
function date(value:string|null|undefined){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(d)}
function month(value:string){if(!value)return"—";const d=new Date(`${value}T12:00:00`);return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(d)}
function csvCell(value:unknown){return `"${String(value??"").replaceAll('"','""')}"`}

export default function RevenueCommandPage(){
 const [data,setData]=useState<Payload>(empty),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[currency,setCurrency]=useState("");
 const [settings,setSettings]=useState({alertsEnabled:false,nrrFloorPercent:90,topClientConcentrationPercent:35,overdueRatioPercent:20});
 async function load(silent=false){if(!silent)setLoading(true);try{const response=await fetch("/api/admin/crm/revenue-command",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Impossible de charger Revenue Command.");return}const next={...empty,...payload} as Payload;setData(next);if(next.settings)setSettings({alertsEnabled:Boolean(next.settings.alerts_enabled),nrrFloorPercent:Number(next.settings.nrr_floor_percent??90),topClientConcentrationPercent:Number(next.settings.top_client_concentration_percent??35),overdueRatioPercent:Number(next.settings.overdue_ratio_percent??20)});if(!currency&&next.currencies[0])setCurrency(next.currencies[0].currency)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function act(action:string,body:Record<string,unknown>,message:string){setBusy(action);setNotice("");try{const response=await fetch("/api/admin/crm/revenue-command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Action impossible.");return false}setNotice(message);await load(true);return true}finally{setBusy("")}}
 const current=data.currencies.find(m=>m.currency===currency)||data.currencies[0]||null;const accounts=useMemo(()=>data.accounts.filter(a=>!currency||a.currency===currency),[data.accounts,currency]);const products=useMemo(()=>data.products.filter(p=>!currency||p.currency===currency),[data.products,currency]);const trend=useMemo(()=>data.trend.filter(t=>!currency||t.currency===currency),[data.trend,currency]);const maxTrend=Math.max(1,...trend.map(t=>t.mrr));
 function exportCsv(){if(!current)return;const rows=[["Compte","Pays","Owner","Devise","MRR","ARR","Part MRR","Abonnements"],...accounts.map(a=>[a.accountName,a.country||"",a.owner||"",a.currency,a.mrr,a.arr,a.share,a.subscriptions])];const csv=rows.map(r=>r.map(csvCell).join(";")).join("\n");const blob=new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`moony-revenue-command-${currency||"all"}.csv`;a.click();URL.revokeObjectURL(url)}
 const aging=current?Object.entries(current.aging) as Array<[keyof Metric["aging"],number]>:[];const agingLabels:Record<string,string>={current:"Non échu",d1_30:"1–30 j",d31_60:"31–60 j",d61_90:"61–90 j",d90plus:"> 90 j"};const agingMax=Math.max(1,...aging.map(([,v])=>v));
 return <AdminWorkspace active="Revenue Command" title="Revenue Command Center" subtitle="Cockpit exécutif post-signature : revenu récurrent, rétention nette, cash, créances et concentration. Chaque devise reste isolée ; aucune conversion FX implicite n’est effectuée." actions={<div className="flex flex-wrap gap-2"><Link href="/admin/customer-success/billing" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Billing</Link><Link href="/admin/customer-success/collections" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Encaissements</Link><Link href="/admin/customer-success/contracts" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Avenants</Link><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><RefreshCw size={14}/> Actualiser</button><button disabled={!data.available||busy==="snapshot"} onClick={()=>void act("snapshot",{},"Baseline mensuel vérifié. Un snapshot existant n’est jamais réécrit.")} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-4 py-2.5 text-sm text-white disabled:opacity-50"><ShieldCheck size={14}/> Capturer baseline</button></div>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911144500_crm_revenue_command_center.sql</strong> après V8.9 pour activer CRM V8.10.</div>:null}
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#5b2f22]/8 bg-white/65 p-4"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#5b2f22]/45">Baseline de comparaison</p><p className="mt-1 text-sm font-medium">{data.baseline?`${month(data.baseline.periodMonth)} · capturé ${date(data.baseline.capturedAt)}`:"Aucun baseline mensuel disponible"}</p><p className="mt-1 text-[10px] text-[#5b2f22]/45">NRR et GRR restent indisponibles tant qu’un revenu de départ explicite n’existe pas.</p></div><div className="flex items-center gap-2"><select value={currency} onChange={e=>setCurrency(e.target.value)} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2 text-sm">{data.currencies.map(m=><option key={m.currency} value={m.currency}>{m.currency}</option>)}</select><button onClick={exportCsv} disabled={!current} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2 text-sm disabled:opacity-40"><Download size={14}/> CSV</button></div></div>
  {current?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><article className="admin-card admin-shadow p-5 xl:col-span-2"><CircleDollarSign size={17} className="text-[#9d4c27]"/><p className="mt-3 text-[10px] uppercase tracking-[.13em] text-[#5b2f22]/45">MRR / ARR · {current.currency}</p><strong className="moony-serif mt-1 block text-3xl font-normal">{money(current.currentMrr,current.currency)}</strong><span className="text-[10px] text-[#5b2f22]/45">ARR {money(current.currentArr,current.currency)} · {current.clients.total} comptes</span></article><article className="admin-card admin-shadow p-5"><Gauge size={17} className="text-[#9d4c27]"/><p className="mt-3 text-[10px] text-[#5b2f22]/45">NRR</p><strong className="moony-serif mt-1 block text-3xl font-normal">{pct(current.nrr)}</strong><span className="text-[10px] text-[#5b2f22]/45">GRR {pct(current.grr)}</span></article><article className="admin-card admin-shadow p-5"><WalletCards size={17} className="text-[#9d4c27]"/><p className="mt-3 text-[10px] text-[#5b2f22]/45">Facturé / encaissé ce mois</p><strong className="moony-serif mt-1 block text-xl font-normal">{money(current.invoicedMonth,current.currency)}</strong><span className="text-[10px] text-[#5b2f22]/45">encaissé {money(current.collectedMonth,current.currency)}</span></article><article className="admin-card admin-shadow p-5"><AlertTriangle size={17} className="text-red-600"/><p className="mt-3 text-[10px] text-[#5b2f22]/45">À recevoir</p><strong className="moony-serif mt-1 block text-xl font-normal">{money(current.outstanding,current.currency)}</strong><span className="text-[10px] text-red-700">retard {money(current.overdue,current.currency)} · {pct(current.overdueRatio)}</span></article><article className="admin-card admin-shadow p-5"><BarChart3 size={17} className="text-[#9d4c27]"/><p className="mt-3 text-[10px] text-[#5b2f22]/45">DSO opérationnel</p><strong className="moony-serif mt-1 block text-3xl font-normal">{current.dso===null?"—":`${current.dso.toFixed(0)} j`}</strong><span className="text-[10px] text-[#5b2f22]/45">solde / facturé 90 j × 90</span></article></div>
  <section className="admin-card admin-shadow mt-5 p-5"><div className="flex items-center justify-between"><div><h2 className="moony-serif text-2xl">Revenue Bridge</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Du dernier baseline au revenu contractuel live. Le nouveau MRR est exclu du calcul NRR/GRR.</p></div><span className="rounded-full bg-[#f3e4d3] px-3 py-1 text-[10px] text-[#7e3518]">{current.currency}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Départ",current.startingMrr,"neutral"],["Nouveau",current.newMrr,"up"],["Expansion",current.expansionMrr,"up"],["Contraction",current.contractionMrr,"down"],["Churn",current.churnMrr,"down"],["MRR live",current.currentMrr,"neutral"]].map(([label,value,t])=><div key={String(label)} className="rounded-xl border border-[#5b2f22]/8 bg-white/65 p-4"><div className="flex items-center gap-1 text-[10px] text-[#5b2f22]/45">{t==="up"?<ArrowUpRight size={12} className="text-emerald-600"/>:t==="down"?<ArrowDownRight size={12} className="text-red-600"/>:null}{String(label)}</div><strong className={`mt-2 block text-lg ${t==="down"?"text-red-700":t==="up"?"text-emerald-700":"text-[#2d1812]"}`}>{money(Number(value),current.currency)}</strong></div>)}</div><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-[#5b2f22]/55"><span>{current.clients.new} nouveaux comptes</span><span>{current.clients.expanded} expansions</span><span>{current.clients.contracted} contractions</span><span>{current.clients.churned} churns</span></div></section>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="admin-card admin-shadow p-5"><h2 className="moony-serif text-2xl">Aging des créances</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Solde restant dû uniquement.</p><div className="mt-5 space-y-3">{aging.map(([key,value])=><div key={key}><div className="mb-1 flex justify-between text-[10px]"><span>{agingLabels[key]}</span><strong>{money(value,current.currency)}</strong></div><div className="h-2 rounded-full bg-[#f3e4d3]"><div className="h-2 rounded-full bg-[#9d4c27]" style={{width:`${Math.max(value>0?3:0,value/agingMax*100)}%`}}/></div></div>)}</div></section><section className="admin-card admin-shadow p-5"><h2 className="moony-serif text-2xl">Concentration</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Dépendance du MRR live à quelques comptes.</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#fff8f2] p-4"><span className="text-[10px] text-[#5b2f22]/45">Top client</span><strong className="moony-serif mt-1 block text-3xl font-normal">{pct(current.topClientShare)}</strong></div><div className="rounded-xl bg-[#fff8f2] p-4"><span className="text-[10px] text-[#5b2f22]/45">Top 5</span><strong className="moony-serif mt-1 block text-3xl font-normal">{pct(current.top5Share)}</strong></div></div><div className="mt-4 space-y-2">{accounts.slice(0,5).map(a=><div key={a.clientId} className="flex items-center justify-between border-t border-[#5b2f22]/7 pt-2 text-xs"><span className="truncate pr-3">{a.accountName}</span><span>{money(a.mrr,a.currency)} · {pct(a.share)}</span></div>)}</div></section></div>
  <section className="admin-card admin-shadow mt-5 p-5"><h2 className="moony-serif text-2xl">Historique des baselines</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Chaque barre provient d’un snapshot mensuel enregistré, jamais d’un recalcul rétroactif.</p>{trend.length?<div className="mt-5 space-y-3">{trend.map(t=><div key={`${t.periodMonth}-${t.currency}`} className="grid grid-cols-[95px_1fr_140px] items-center gap-3 text-[10px]"><span className="capitalize">{month(t.periodMonth)}</span><div className="h-3 rounded-full bg-[#f3e4d3]"><div className="h-3 rounded-full bg-[#9d4c27]" style={{width:`${Math.max(3,t.mrr/maxTrend*100)}%`}}/></div><strong className="text-right">{money(t.mrr,t.currency)} · {t.clients} cl.</strong></div>)}</div>:<p className="mt-5 text-xs text-[#5b2f22]/45">Capturez le premier baseline pour commencer l’historique.</p>}</section>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="admin-card admin-shadow overflow-hidden"><div className="p-5"><h2 className="moony-serif text-2xl">Comptes</h2><p className="mt-1 text-xs text-[#5b2f22]/45">MRR live par compte, owner et pays explicite du CRM.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-[#f8f0e5]"><tr><th className="px-4 py-3">Compte</th><th>Pays</th><th>Owner</th><th>MRR</th><th>Part</th></tr></thead><tbody>{accounts.map(a=><tr key={`${a.clientId}-${a.currency}`} className="border-t border-[#5b2f22]/7"><td className="px-4 py-3 font-medium">{a.accountName}</td><td>{a.country||"—"}</td><td>{a.owner||"—"}</td><td>{money(a.mrr,a.currency)}</td><td>{pct(a.share)}</td></tr>)}</tbody></table></div></section><section className="admin-card admin-shadow overflow-hidden"><div className="p-5"><h2 className="moony-serif text-2xl">Produits / abonnements</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Répartition du revenu récurrent par offre explicitement enregistrée.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left text-xs"><thead className="bg-[#f8f0e5]"><tr><th className="px-4 py-3">Produit</th><th>Abonnements</th><th>MRR</th><th>ARR</th></tr></thead><tbody>{products.map(p=><tr key={`${p.name}-${p.currency}`} className="border-t border-[#5b2f22]/7"><td className="px-4 py-3 font-medium">{p.name}</td><td>{p.subscriptions}</td><td>{money(p.mrr,p.currency)}</td><td>{money(p.arr,p.currency)}</td></tr>)}</tbody></table></div></section></div></>:<div className="admin-card admin-shadow p-8 text-center text-sm text-[#5b2f22]/50">{loading?"Calcul des métriques…":"Aucune donnée de revenu récurrent disponible."}</div>}
  <section className="admin-card admin-shadow mt-6 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="moony-serif text-2xl">Seuils exécutifs</h2><p className="mt-1 text-xs text-[#5b2f22]/45">Alertes internes uniquement. Désactivées par défaut ; elles ne déclenchent aucune action commerciale ou communication client.</p></div><div className="flex gap-2"><button disabled={!data.available||busy==="sync"} onClick={()=>void act("sync",{},"Revenue Command analysé et baseline mensuel vérifié.")} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/10 bg-white px-4 py-2.5 text-sm disabled:opacity-40"><Sparkles size={14}/> Analyser</button><button disabled={!data.available||busy==="settings"} onClick={()=>void act("settings",settings,"Seuils exécutifs enregistrés.")} className="inline-flex items-center gap-2 rounded-lg bg-[#2d1812] px-4 py-2.5 text-sm text-white disabled:opacity-40"><Save size={14}/> Enregistrer</button></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><label className="flex items-center gap-3 rounded-xl border border-[#5b2f22]/10 bg-white p-3 text-xs"><input type="checkbox" checked={settings.alertsEnabled} onChange={e=>setSettings(s=>({...s,alertsEnabled:e.target.checked}))}/> Activer les alertes</label><label className="text-[10px] text-[#5b2f22]/50">NRR minimum (%)<input type="number" min="0" max="200" value={settings.nrrFloorPercent} onChange={e=>setSettings(s=>({...s,nrrFloorPercent:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-sm text-[#2d1812]"/></label><label className="text-[10px] text-[#5b2f22]/50">Top client max (%)<input type="number" min="1" max="100" value={settings.topClientConcentrationPercent} onChange={e=>setSettings(s=>({...s,topClientConcentrationPercent:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-sm text-[#2d1812]"/></label><label className="text-[10px] text-[#5b2f22]/50">Créances en retard max (%)<input type="number" min="0" max="100" value={settings.overdueRatioPercent} onChange={e=>setSettings(s=>({...s,overdueRatioPercent:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-sm text-[#2d1812]"/></label></div></section>
  <div className="mt-5 rounded-xl border border-[#5b2f22]/8 bg-[#fffaf4] p-4 text-[10px] leading-5 text-[#5b2f22]/55"><strong className="text-[#5b2f22]">Méthode.</strong> MRR = montant contractuel récurrent normalisé selon la périodicité ; les contrats « sur mesure » ne sont pas convertis artificiellement. NRR = (MRR départ + expansion − contraction − churn) / MRR départ ; GRR exclut l’expansion et le nouveau revenu. Le DSO affiché est un indicateur opérationnel = créances ouvertes / montant facturé sur 90 jours × 90. Aucun taux de change n’est appliqué.</div>
 </AdminWorkspace>
}
