import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

export default function NewslettersPage(){return <AdminWorkspace active="Newsletters" title="Newsletters" subtitle="Créez, programmez et analysez vos campagnes email depuis le Control Center." actions={<button className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">+ Créer une newsletter</button>}>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Abonnés","12 480","+12%"],["Taux d’ouverture","38,6%","+6,2%"],["Taux de clics","4,8%","+1,4%"],["Nouveaux abonnés","+1 245","+28%"]].map(([l,v,d])=><div key={l} className="admin-card admin-shadow p-5"><p className="text-xs text-[#5b2f22]/45">{l}</p><div className="mt-2 flex items-end justify-between"><p className="moony-serif text-4xl">{v}</p><span className="text-xs text-emerald-700">↗ {d}</span></div></div>)}</div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]">
<AdminCard title="Éditeur d’email"><div className="grid gap-4 lg:grid-cols-[1fr_190px]"><div className="rounded-xl border border-[#5b2f22]/10 bg-[#fbf2ea] p-5"><div className="text-center moony-serif text-2xl">MOONY</div><div className="mt-5 rounded-lg bg-[#d6a17e] p-8 text-white"><p className="moony-serif text-4xl leading-tight">Des femmes plus sereines,<br/>pour un monde plus lumineux.</p><button className="mt-5 rounded-full bg-[#7e3518] px-5 py-2.5 text-xs">Découvrir notre sélection</button></div></div><div className="space-y-2">{["Texte","Image","Bouton","Séparateur","Réseaux sociaux","Vidéo","Code HTML"].map(x=><button key={x} className="w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-left text-xs">+ {x}</button>)}</div></div></AdminCard>
<AdminCard title="Paramètres d’envoi"><div className="space-y-3 text-sm"><label className="block"><span className="mb-1 block text-xs text-[#5b2f22]/45">Destinataires</span><select className="w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3"><option>Toutes les abonnées (12 480)</option></select></label><label className="block"><span className="mb-1 block text-xs text-[#5b2f22]/45">Planification</span><select className="w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3"><option>Envoyer maintenant</option><option>Programmer</option></select></label><button className="w-full rounded-lg bg-[#7e3518] px-4 py-3 text-white">Envoyer la newsletter</button></div></AdminCard>
</div>
</AdminWorkspace>}
