import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { asText, requireAdmin, writeAuditLog } from "@/lib/admin-api";
import { syncContractLifecycleAlerts } from "@/lib/crm-contract-lifecycle";

function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
async function bodyOf(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function nullable(value:unknown,max=4000){const text=asText(value,max);return text||null}
function dateOnly(value:unknown){const text=asText(value,20);return /^\d{4}-\d{2}-\d{2}$/.test(text)?text:null}
function nonNegative(value:unknown){if(value===null||value===undefined||value==="")return null;const number=Number(value);return Number.isFinite(number)&&number>=0?number:NaN}
function positive(value:unknown){if(value===null||value===undefined||value==="")return null;const number=Number(value);return Number.isFinite(number)&&number>0?number:NaN}
function percent(value:unknown){if(value===null||value===undefined||value==="")return null;const number=Number(value);return Number.isFinite(number)&&number>=0&&number<=100?number:NaN}
function actor(session:any){return session.name||session.email||"MOONY Admin"}
function amendmentReference(){const d=new Date();return `MNY-AMD-${d.getUTCFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`}
function relation(value:any){return Array.isArray(value)?value[0]??null:value??null}
function snapshotSubscription(row:any){if(!row)return{};return{id:row.id,name:row.name,status:row.status,billing_model:row.billing_model,pricing_unit:row.pricing_unit,quantity:Number(row.quantity||0),unit_price:Number(row.unit_price||0),discount_percent:Number(row.discount_percent||0),recurring_amount:Number(row.recurring_amount||0),currency:row.currency,start_date:row.start_date,end_date:row.end_date,next_invoice_date:row.next_invoice_date}}

export async function GET(request:Request){
 const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;
 const [settings,clients,contracts,subscriptions,amendments,events]=await Promise.all([
  supabase.from("website_crm_contract_lifecycle_settings").select("*").eq("id","default").maybeSingle(),
  supabase.from("website_crm_client_accounts").select("id,onboarding_id,account_name,status,owner,commercial_owner,renewal_date").eq("status","active").order("account_name"),
  supabase.from("website_crm_contracts").select("id,onboarding_id,reference,title,status,effective_date,signed_at,signed_by,signed_by_email,version").order("created_at",{ascending:false}).limit(500),
  supabase.from("website_crm_account_subscriptions").select("id,client_id,name,status,billing_model,pricing_unit,quantity,unit_price,discount_percent,recurring_amount,currency,start_date,end_date,next_invoice_date,website_crm_client_accounts(account_name)").order("updated_at",{ascending:false}).limit(500),
  supabase.from("website_crm_contract_amendments").select("*,website_crm_client_accounts(account_name,owner,renewal_date),website_crm_contracts(reference,title,status),website_crm_account_subscriptions(name,status,recurring_amount,currency)").order("effective_date",{ascending:true}).limit(500),
  supabase.from("website_crm_subscription_change_events").select("*,website_crm_client_accounts(account_name),website_crm_account_subscriptions(name),website_crm_contract_amendments(reference,title)").order("created_at",{ascending:false}).limit(500),
 ]);
 if(settings.error&&missing(settings.error))return NextResponse.json({available:false,settings:null,clients:[],contracts:[],subscriptions:[],amendments:[],events:[],metrics:{draft:0,inReview:0,signedPending:0,effectiveSoon:0,applied:0}});
 const fatal=[settings.error,clients.error,contracts.error,subscriptions.error,amendments.error,events.error].find(item=>item&&!missing(item));if(fatal)return NextResponse.json({error:fatal.message},{status:500});
 const today=new Date().toISOString().slice(0,10),in14=new Date(Date.now()+14*86400000).toISOString().slice(0,10),rows=amendments.data??[];
 return NextResponse.json({available:true,settings:settings.data??{id:"default",enabled:false,upcoming_effective_days:14,unsigned_effective_grace_days:0},clients:clients.data??[],contracts:contracts.data??[],subscriptions:subscriptions.data??[],amendments:rows,events:events.data??[],metrics:{draft:rows.filter((r:any)=>r.status==="draft").length,inReview:rows.filter((r:any)=>["review","approved"].includes(r.status)).length,signedPending:rows.filter((r:any)=>r.status==="signed").length,effectiveSoon:rows.filter((r:any)=>r.status==="signed"&&r.effective_date>=today&&r.effective_date<=in14).length,applied:rows.filter((r:any)=>r.status==="applied").length}});
}

export async function POST(request:Request){
 const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;const body=await bodyOf(request);if(!body)return NextResponse.json({error:"Requête invalide."},{status:400});const action=asText(body.action,40),who=actor(session),now=new Date().toISOString();
 if(action==="sync"){try{const result=await syncContractLifecycleAlerts(supabase);await writeAuditLog(supabase,session,"crm.contract_lifecycle_sync","crm_contract_lifecycle",null,"Analyse du cycle contractuel",result);return NextResponse.json(result)}catch(err){return NextResponse.json({error:err instanceof Error?err.message:"Analyse impossible."},{status:500})}}
 if(action==="settings"){
  const upcoming=Math.round(Number(body.upcomingEffectiveDays)),grace=Math.round(Number(body.unsignedEffectiveGraceDays));if(!Number.isFinite(upcoming)||upcoming<1||upcoming>180||!Number.isFinite(grace)||grace<0||grace>30)return NextResponse.json({error:"Paramètres contractuels invalides."},{status:422});const saved=await supabase.from("website_crm_contract_lifecycle_settings").upsert({id:"default",enabled:Boolean(body.enabled),upcoming_effective_days:upcoming,unsigned_effective_grace_days:grace,updated_by:who,updated_at:now},{onConflict:"id"}).select("*").single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_lifecycle_settings_updated","crm_contract_lifecycle_settings","default","Paramètres cycle contractuel mis à jour",{enabled:Boolean(body.enabled),upcoming,grace});return NextResponse.json({ok:true,settings:saved.data});
 }
 if(action==="amendment_create"){
  const clientId=asText(body.clientId,80),contractId=asText(body.contractId,80)||null,subscriptionId=asText(body.subscriptionId,80)||null,title=asText(body.title,260),kind=asText(body.kind,30)||"other",effectiveDate=dateOnly(body.effectiveDate);if(!clientId||!title||!effectiveDate||!["upgrade","downgrade","pricing","quantity","scope","renewal","term","other"].includes(kind))return NextResponse.json({error:"Client, titre, type et date d’effet sont obligatoires."},{status:422});
  const client=await supabase.from("website_crm_client_accounts").select("id,onboarding_id,account_name,renewal_date").eq("id",clientId).maybeSingle();if(client.error||!client.data)return NextResponse.json({error:"Client introuvable."},{status:404});let subscription:any=null;
  if(subscriptionId){const result=await supabase.from("website_crm_account_subscriptions").select("*").eq("id",subscriptionId).eq("client_id",clientId).maybeSingle();if(result.error||!result.data)return NextResponse.json({error:"Abonnement introuvable pour ce client."},{status:404});subscription=result.data}
  if(contractId){const result=await supabase.from("website_crm_contracts").select("id,onboarding_id,reference,status").eq("id",contractId).maybeSingle();if(result.error||!result.data||result.data.onboarding_id!==client.data.onboarding_id)return NextResponse.json({error:"Contrat de base introuvable pour ce client."},{status:404})}
  const quantity=positive(body.newQuantity),unitPrice=nonNegative(body.newUnitPrice),discount=percent(body.newDiscountPercent),recurring=nonNegative(body.newRecurringAmount);if([quantity,unitPrice,discount,recurring].some(v=>typeof v==="number"&&Number.isNaN(v)))return NextResponse.json({error:"Valeurs financières invalides."},{status:422});const billingModel=asText(body.newBillingModel,30)||null;if(billingModel&&!["monthly","quarterly","semiannual","annual","custom"].includes(billingModel))return NextResponse.json({error:"Périodicité invalide."},{status:422});const renewalDate=dateOnly(body.newRenewalDate),endDate=dateOnly(body.newSubscriptionEndDate),nextInvoiceDate=dateOnly(body.newNextInvoiceDate),currency=(asText(body.currency,3)||subscription?.currency||"").toUpperCase()||null;if(currency&&currency.length!==3)return NextResponse.json({error:"Devise invalide."},{status:422});
  const requested={billing_model:billingModel,quantity,unit_price:unitPrice,discount_percent:discount,recurring_amount:recurring,subscription_end_date:endDate,next_invoice_date:nextInvoiceDate,renewal_date:renewalDate};if(!Object.values(requested).some(v=>v!==null)&&!nullable(body.summary))return NextResponse.json({error:"Décrivez au moins un changement contractuel."},{status:422});const before={subscription:snapshotSubscription(subscription),renewal_date:client.data.renewal_date};
  const created=await supabase.from("website_crm_contract_amendments").insert({client_id:clientId,contract_id:contractId,subscription_id:subscriptionId,reference:asText(body.reference,100)||amendmentReference(),kind,status:"draft",title,summary:nullable(body.summary,6000),effective_date:effectiveDate,currency,new_billing_model:billingModel,new_quantity:quantity,new_unit_price:unitPrice,new_discount_percent:discount,new_recurring_amount:recurring,new_subscription_end_date:endDate,new_next_invoice_date:nextInvoiceDate,new_renewal_date:renewalDate,owner:nullable(body.owner,240),before_snapshot:before,after_snapshot:{requested},created_by:who,updated_by:who}).select("*").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_amendment_created","crm_contract_amendment",created.data.id,`${created.data.reference} · ${client.data.account_name}`,{kind,effectiveDate,clientId,subscriptionId,contractId});return NextResponse.json({ok:true,amendment:created.data},{status:201});
 }
 const id=asText(body.amendmentId,80);if(!id)return NextResponse.json({error:"Avenant obligatoire."},{status:422});const current=await supabase.from("website_crm_contract_amendments").select("*").eq("id",id).maybeSingle();if(current.error||!current.data)return NextResponse.json({error:"Avenant introuvable."},{status:404});const amendment=current.data;
 if(action==="amendment_status"){
  const status=asText(body.status,20);if(!["draft","review","approved","cancelled"].includes(status)||["signed","applied"].includes(amendment.status))return NextResponse.json({error:"Transition de statut non autorisée."},{status:422});const patch:any={status,updated_by:who,updated_at:now};if(status==="approved"){patch.approved_at=now;patch.approved_by=who}else if(amendment.status==="approved"){patch.approved_at=null;patch.approved_by=null}const updated=await supabase.from("website_crm_contract_amendments").update(patch).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_amendment_status","crm_contract_amendment",id,`${amendment.reference} · ${status}`,{from:amendment.status,to:status});return NextResponse.json({ok:true,amendment:updated.data});
 }
 if(action==="amendment_sign"){
  if(amendment.status!=="approved")return NextResponse.json({error:"L’avenant doit être approuvé avant signature."},{status:422});const signedBy=asText(body.signedBy,240),signedByEmail=nullable(body.signedByEmail,320);if(!signedBy)return NextResponse.json({error:"Signataire obligatoire."},{status:422});const updated=await supabase.from("website_crm_contract_amendments").update({status:"signed",signed_at:now,signed_by:signedBy,signed_by_email:signedByEmail,updated_by:who,updated_at:now}).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_amendment_signed","crm_contract_amendment",id,`${amendment.reference} signé`,{signedBy,signedByEmail});return NextResponse.json({ok:true,amendment:updated.data});
 }
 if(action==="amendment_apply"){
  if(amendment.status!=="signed")return NextResponse.json({error:"Seul un avenant signé peut être appliqué."},{status:422});const today=new Date().toISOString().slice(0,10);if(amendment.effective_date>today)return NextResponse.json({error:`Cet avenant prend effet le ${amendment.effective_date}. Il ne peut pas être appliqué avant cette date.`},{status:422});const client=await supabase.from("website_crm_client_accounts").select("id,account_name,renewal_date").eq("id",amendment.client_id).maybeSingle();if(client.error||!client.data)return NextResponse.json({error:"Compte client introuvable."},{status:404});let beforeSubscription:any=null,afterSubscription:any=null;
  if(amendment.subscription_id){const sub=await supabase.from("website_crm_account_subscriptions").select("*").eq("id",amendment.subscription_id).eq("client_id",amendment.client_id).maybeSingle();if(sub.error||!sub.data)return NextResponse.json({error:"Abonnement lié introuvable."},{status:404});beforeSubscription=snapshotSubscription(sub.data);const patch:any={updated_by:who,updated_at:now};if(amendment.new_billing_model!==null)patch.billing_model=amendment.new_billing_model;if(amendment.new_quantity!==null)patch.quantity=amendment.new_quantity;if(amendment.new_unit_price!==null)patch.unit_price=amendment.new_unit_price;if(amendment.new_discount_percent!==null)patch.discount_percent=amendment.new_discount_percent;if(amendment.new_recurring_amount!==null)patch.recurring_amount=amendment.new_recurring_amount;if(amendment.new_subscription_end_date!==null)patch.end_date=amendment.new_subscription_end_date;if(amendment.new_next_invoice_date!==null)patch.next_invoice_date=amendment.new_next_invoice_date;const updated=await supabase.from("website_crm_account_subscriptions").update(patch).eq("id",amendment.subscription_id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});afterSubscription=snapshotSubscription(updated.data);const event=await supabase.from("website_crm_subscription_change_events").insert({client_id:amendment.client_id,subscription_id:amendment.subscription_id,amendment_id:id,change_type:amendment.kind,effective_date:amendment.effective_date,before_state:beforeSubscription,after_state:afterSubscription,applied_by:who});if(event.error)return NextResponse.json({error:event.error.message},{status:500})}
  if(amendment.new_renewal_date!==null){const updatedClient=await supabase.from("website_crm_client_accounts").update({renewal_date:amendment.new_renewal_date,updated_by:who,updated_at:now}).eq("id",amendment.client_id);if(updatedClient.error)return NextResponse.json({error:updatedClient.error.message},{status:500})}
  const after={subscription:afterSubscription,renewal_date:amendment.new_renewal_date??client.data.renewal_date};const applied=await supabase.from("website_crm_contract_amendments").update({status:"applied",applied_at:now,applied_by:who,before_snapshot:{subscription:beforeSubscription??relation(amendment.before_snapshot)?.subscription??{},renewal_date:client.data.renewal_date},after_snapshot:after,updated_by:who,updated_at:now}).eq("id",id).select("*").single();if(applied.error)return NextResponse.json({error:applied.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_amendment_applied","crm_contract_amendment",id,`${amendment.reference} appliqué · ${client.data.account_name}`,{effectiveDate:amendment.effective_date,before:beforeSubscription,after:afterSubscription,renewalBefore:client.data.renewal_date,renewalAfter:after.renewal_date});return NextResponse.json({ok:true,amendment:applied.data});
 }
 if(action==="create_task"){
  const title=asText(body.title,240);if(!title)return NextResponse.json({error:"Titre de tâche obligatoire."},{status:422});const client=await supabase.from("website_crm_client_accounts").select("lead_id,owner,commercial_owner,account_name").eq("id",amendment.client_id).maybeSingle();if(client.error||!client.data)return NextResponse.json({error:"Client introuvable."},{status:404});const due=body.dueAt?new Date(String(body.dueAt)):new Date(Date.now()+24*3600000);if(Number.isNaN(due.getTime()))return NextResponse.json({error:"Échéance invalide."},{status:422});const priority=asText(body.priority,20);const created=await supabase.from("website_crm_tasks").insert({lead_id:client.data.lead_id,title,due_at:due.toISOString(),status:"todo",priority:["normal","high","urgent"].includes(priority)?priority:"normal",assigned_to:client.data.owner||client.data.commercial_owner||who,notes:nullable(body.notes),metadata:{source:"crm-contract-lifecycle",client_id:amendment.client_id,amendment_id:id}}).select("id").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.contract_amendment_task_created","crm_task",created.data.id,`Tâche avenant · ${client.data.account_name}`,{amendmentId:id});return NextResponse.json({ok:true,taskId:created.data.id},{status:201});
 }
 return NextResponse.json({error:"Action non prise en charge."},{status:422});
}
