import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { asText, requireAdmin, writeAuditLog } from "@/lib/admin-api";
import { syncReceivablesCollections } from "@/lib/crm-receivables";

function missing(error:any){return ["42P01","42703"].includes(String(error?.code||""))}
async function bodyOf(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function nullable(value:unknown,max=4000){const text=asText(value,max);return text||null}
function dateOnly(value:unknown){const text=asText(value,20);return /^\d{4}-\d{2}-\d{2}$/.test(text)?text:null}
function money(value:unknown){const number=Number(value);return Number.isFinite(number)&&number>0?number:null}
function actor(session:any){return session.name||session.email||"MOONY Admin"}
function paymentReference(){const d=new Date();return `PAY-${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}-${randomUUID().slice(0,8).toUpperCase()}`}
function relation(value:any){return Array.isArray(value)?value[0]:value}

async function recalcInvoice(supabase:any,invoiceId:string,who:string){
 const invoice=await supabase.from("website_crm_billing_invoices").select("id,status,total_amount,due_date").eq("id",invoiceId).maybeSingle();if(invoice.error||!invoice.data)return invoice.error?{error:invoice.error}:null;
 const allocations=await supabase.from("website_crm_payment_allocations").select("amount,website_crm_payments(status,received_at)").eq("invoice_id",invoiceId);if(allocations.error)return {error:allocations.error};
 let paid=0,lastPayment:string|null=null;for(const allocation of allocations.data??[]){const payment=relation(allocation.website_crm_payments);if(payment?.status!=="received")continue;paid+=Number(allocation.amount||0);if(payment.received_at&&(!lastPayment||payment.received_at>lastPayment))lastPayment=payment.received_at}
 paid=Math.min(Number(invoice.data.total_amount||0),Math.max(0,paid));let status=invoice.data.status;let paidAt:null|string=null;
 if(!["draft","cancelled"].includes(status)){if(paid>=Number(invoice.data.total_amount||0)&&Number(invoice.data.total_amount||0)>0){status="paid";paidAt=lastPayment||new Date().toISOString()}else{const today=new Date().toISOString().slice(0,10);status=invoice.data.due_date&&invoice.data.due_date<today?"overdue":"issued"}}
 const updated=await supabase.from("website_crm_billing_invoices").update({amount_paid:paid,last_payment_at:lastPayment,status,paid_at:paidAt,updated_by:who,updated_at:new Date().toISOString()}).eq("id",invoiceId).select("*").single();return updated.error?{error:updated.error}:{invoice:updated.data};
}

export async function GET(request:Request){
 const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;
 const [settings,clients,invoices,payments,allocations,promises]=await Promise.all([
  supabase.from("website_crm_collection_settings").select("*").eq("id","default").maybeSingle(),
  supabase.from("website_crm_client_accounts").select("id,lead_id,account_name,status,owner,commercial_owner").eq("status","active").order("account_name"),
  supabase.from("website_crm_billing_invoices").select("id,client_id,reference,title,status,issue_date,due_date,paid_at,total_amount,amount_paid,last_payment_at,currency,website_crm_client_accounts(account_name,owner)").order("due_date",{ascending:true}).limit(400),
  supabase.from("website_crm_payments").select("*,website_crm_client_accounts(account_name,owner)").order("created_at",{ascending:false}).limit(400),
  supabase.from("website_crm_payment_allocations").select("id,payment_id,invoice_id,amount,created_at,website_crm_billing_invoices(reference,title,currency)").order("created_at",{ascending:false}).limit(800),
  supabase.from("website_crm_collection_promises").select("*,website_crm_client_accounts(account_name,owner),website_crm_billing_invoices(reference,title)").order("promised_date",{ascending:true}).limit(400),
 ]);
 if(settings.error&&missing(settings.error))return NextResponse.json({available:false,settings:null,clients:[],invoices:[],payments:[],allocations:[],promises:[],metrics:{currencies:{},openPromises:0,missedPromises:0,unallocatedPayments:0}});
 const fatal=[settings.error,clients.error,invoices.error,payments.error,allocations.error,promises.error].find((item)=>item&&!missing(item));if(fatal)return NextResponse.json({error:fatal.message},{status:500});
 const allocatedByPayment=new Map<string,number>();for(const row of allocations.data??[])allocatedByPayment.set(row.payment_id,(allocatedByPayment.get(row.payment_id)||0)+Number(row.amount||0));
 const currencies:Record<string,{outstanding:number;overdue:number;received30:number;unallocated:number;aging0_30:number;aging31_60:number;aging61_90:number;aging90Plus:number}>={};const bucket=(currency:string)=>currencies[currency]??(currencies[currency]={outstanding:0,overdue:0,received30:0,unallocated:0,aging0_30:0,aging31_60:0,aging61_90:0,aging90Plus:0});
 const today=Math.floor(Date.now()/86400000),last30=Date.now()-30*86400000;
 const decoratedInvoices=(invoices.data??[]).map((row:any)=>{const balance=Math.max(0,Number(row.total_amount||0)-Number(row.amount_paid||0)),values=bucket(row.currency||"XOF");if(["issued","overdue"].includes(row.status)){values.outstanding+=balance;if(row.status==="overdue")values.overdue+=balance;const due=row.due_date?Math.floor(new Date(`${row.due_date}T00:00:00Z`).getTime()/86400000):null;if(due!==null&&due<today&&balance>0){const age=today-due;if(age<=30)values.aging0_30+=balance;else if(age<=60)values.aging31_60+=balance;else if(age<=90)values.aging61_90+=balance;else values.aging90Plus+=balance}}return {...row,balance_due:balance}});
 const decoratedPayments=(payments.data??[]).map((row:any)=>{const allocated=allocatedByPayment.get(row.id)||0,unallocated=Math.max(0,Number(row.amount||0)-allocated),values=bucket(row.currency||"XOF");if(row.status==="received"){if(row.received_at&&new Date(row.received_at).getTime()>=last30)values.received30+=Number(row.amount||0);values.unallocated+=unallocated}return {...row,allocated_amount:allocated,unallocated_amount:unallocated}});
 return NextResponse.json({available:true,settings:settings.data??{id:"default",enabled:false,unallocated_after_days:2,promise_grace_days:1,aging_alert_days:30},clients:clients.data??[],invoices:decoratedInvoices,payments:decoratedPayments,allocations:allocations.data??[],promises:promises.data??[],metrics:{currencies,openPromises:(promises.data??[]).filter((row:any)=>row.status==="open").length,missedPromises:(promises.data??[]).filter((row:any)=>row.status==="missed").length,unallocatedPayments:decoratedPayments.filter((row:any)=>row.status==="received"&&row.unallocated_amount>0).length}});
}

export async function POST(request:Request){
 const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;const body=await bodyOf(request);if(!body)return NextResponse.json({error:"Requête invalide."},{status:400});const action=asText(body.action,40),who=actor(session),now=new Date().toISOString();
 if(action==="sync"){try{const result=await syncReceivablesCollections(supabase);await writeAuditLog(supabase,session,"crm.collections_sync","crm_collections",null,"Synchronisation Receivables & Collections",result);return NextResponse.json(result)}catch(err){return NextResponse.json({error:err instanceof Error?err.message:"Synchronisation impossible."},{status:500})}}
 if(action==="settings"){
  const unallocated=Math.round(Number(body.unallocatedAfterDays)),grace=Math.round(Number(body.promiseGraceDays)),aging=Math.round(Number(body.agingAlertDays));if(!Number.isFinite(unallocated)||unallocated<0||unallocated>90||!Number.isFinite(grace)||grace<0||grace>30||!Number.isFinite(aging)||aging<1||aging>365)return NextResponse.json({error:"Paramètres Collections invalides."},{status:422});
  const saved=await supabase.from("website_crm_collection_settings").upsert({id:"default",enabled:Boolean(body.enabled),unallocated_after_days:unallocated,promise_grace_days:grace,aging_alert_days:aging,updated_by:who,updated_at:now},{onConflict:"id"}).select("*").single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collections_settings_updated","crm_collection_settings","default","Paramètres Collections mis à jour",{enabled:Boolean(body.enabled),unallocated,grace,aging});return NextResponse.json({ok:true,settings:saved.data});
 }
 if(action==="payment_create"){
  const clientId=asText(body.clientId,80),amount=money(body.amount),currency=(asText(body.currency,3)||"XOF").toUpperCase(),method=asText(body.method,30)||"bank_transfer",status=asText(body.status,20)||"received";if(!clientId||amount===null||currency.length!==3||!["bank_transfer","card","mobile_money","paypal","cash","cheque","other"].includes(method)||!["pending","received"].includes(status))return NextResponse.json({error:"Données d’encaissement invalides."},{status:422});
  const client=await supabase.from("website_crm_client_accounts").select("id,account_name").eq("id",clientId).maybeSingle();if(client.error||!client.data)return NextResponse.json({error:"Client introuvable."},{status:404});const receivedAt=status==="received"?(body.receivedAt?new Date(String(body.receivedAt)).toISOString():now):null;
  const created=await supabase.from("website_crm_payments").insert({client_id:clientId,reference:asText(body.reference,80)||paymentReference(),external_reference:nullable(body.externalReference,240),status,method,amount,currency,received_at:receivedAt,payer_name:nullable(body.payerName,240),notes:nullable(body.notes),created_by:who,updated_by:who}).select("*").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_payment_created","crm_payment",created.data.id,`Encaissement ${created.data.reference} · ${client.data.account_name}`,{clientId,amount,currency,method,status});return NextResponse.json({ok:true,payment:created.data},{status:201});
 }
 if(action==="payment_status"){
  const id=asText(body.paymentId,80),status=asText(body.status,20);if(!id||!["pending","received","reversed"].includes(status))return NextResponse.json({error:"Paiement ou statut invalide."},{status:422});const payment=await supabase.from("website_crm_payments").update({status,received_at:status==="received"?now:null,updated_by:who,updated_at:now}).eq("id",id).select("*").single();if(payment.error)return NextResponse.json({error:payment.error.message},{status:500});const linked=await supabase.from("website_crm_payment_allocations").select("invoice_id").eq("payment_id",id);if(linked.error)return NextResponse.json({error:linked.error.message},{status:500});for(const row of linked.data??[]){const recalculated=await recalcInvoice(supabase,row.invoice_id,who);if(recalculated&&"error" in recalculated&&recalculated.error)return NextResponse.json({error:recalculated.error.message},{status:500})}await writeAuditLog(supabase,session,"crm.collection_payment_status","crm_payment",id,`${payment.data.reference} · ${status}`,{status});return NextResponse.json({ok:true,payment:payment.data});
 }
 if(action==="allocation_create"){
  const paymentId=asText(body.paymentId,80),invoiceId=asText(body.invoiceId,80),amount=money(body.amount);if(!paymentId||!invoiceId||amount===null)return NextResponse.json({error:"Paiement, facture et montant obligatoires."},{status:422});const [payment,invoice,existing]=await Promise.all([supabase.from("website_crm_payments").select("id,client_id,reference,status,amount,currency").eq("id",paymentId).maybeSingle(),supabase.from("website_crm_billing_invoices").select("id,client_id,reference,status,total_amount,amount_paid,currency").eq("id",invoiceId).maybeSingle(),supabase.from("website_crm_payment_allocations").select("amount").eq("payment_id",paymentId)]);if(payment.error||!payment.data||invoice.error||!invoice.data)return NextResponse.json({error:"Paiement ou facture introuvable."},{status:404});if(existing.error)return NextResponse.json({error:existing.error.message},{status:500});if(payment.data.status!=="received")return NextResponse.json({error:"Seul un paiement reçu peut être rapproché."},{status:422});if(payment.data.client_id!==invoice.data.client_id||payment.data.currency!==invoice.data.currency)return NextResponse.json({error:"Paiement et facture doivent appartenir au même compte et à la même devise."},{status:422});if(["draft","cancelled","paid"].includes(invoice.data.status))return NextResponse.json({error:"Cette facture ne peut pas recevoir d’allocation."},{status:422});const already=(existing.data??[]).reduce((sum,row)=>sum+Number(row.amount||0),0),paymentRemaining=Math.max(0,Number(payment.data.amount)-already),invoiceRemaining=Math.max(0,Number(invoice.data.total_amount)-Number(invoice.data.amount_paid||0));if(amount>paymentRemaining+0.0001||amount>invoiceRemaining+0.0001)return NextResponse.json({error:"Le montant dépasse le solde disponible du paiement ou de la facture."},{status:422});
  const created=await supabase.from("website_crm_payment_allocations").insert({payment_id:paymentId,invoice_id:invoiceId,amount,created_by:who}).select("*").single();if(created.error)return NextResponse.json({error:created.error.code==="23505"?"Ce paiement est déjà alloué à cette facture. Supprimez l’allocation avant de la recréer.":created.error.message},{status:500});const recalculated=await recalcInvoice(supabase,invoiceId,who);if(recalculated&&"error" in recalculated&&recalculated.error)return NextResponse.json({error:recalculated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_allocation_created","crm_payment_allocation",created.data.id,`${payment.data.reference} → ${invoice.data.reference}`,{paymentId,invoiceId,amount,currency:payment.data.currency});return NextResponse.json({ok:true,allocation:created.data,invoice:recalculated&&"invoice" in recalculated?recalculated.invoice:null},{status:201});
 }
 if(action==="allocation_delete"){
  const id=asText(body.allocationId,80);if(!id)return NextResponse.json({error:"Allocation obligatoire."},{status:422});const row=await supabase.from("website_crm_payment_allocations").select("id,payment_id,invoice_id,amount").eq("id",id).maybeSingle();if(row.error||!row.data)return NextResponse.json({error:"Allocation introuvable."},{status:404});const removed=await supabase.from("website_crm_payment_allocations").delete().eq("id",id);if(removed.error)return NextResponse.json({error:removed.error.message},{status:500});const recalculated=await recalcInvoice(supabase,row.data.invoice_id,who);if(recalculated&&"error" in recalculated&&recalculated.error)return NextResponse.json({error:recalculated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_allocation_removed","crm_payment_allocation",id,"Rapprochement supprimé",row.data);return NextResponse.json({ok:true});
 }
 if(action==="promise_create"){
  const clientId=asText(body.clientId,80),invoiceId=asText(body.invoiceId,80)||null,promisedDate=dateOnly(body.promisedDate),amount=money(body.promisedAmount),currency=(asText(body.currency,3)||"XOF").toUpperCase();if(!clientId||!promisedDate||amount===null||currency.length!==3)return NextResponse.json({error:"Promesse de paiement incomplète."},{status:422});if(invoiceId){const invoice=await supabase.from("website_crm_billing_invoices").select("client_id,currency").eq("id",invoiceId).maybeSingle();if(invoice.error||!invoice.data||invoice.data.client_id!==clientId||invoice.data.currency!==currency)return NextResponse.json({error:"La facture ne correspond pas au compte ou à la devise."},{status:422})}
  const created=await supabase.from("website_crm_collection_promises").insert({client_id:clientId,invoice_id:invoiceId,status:"open",promised_date:promisedDate,promised_amount:amount,currency,owner:nullable(body.owner,240),notes:nullable(body.notes),created_by:who,updated_by:who}).select("*").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_promise_created","crm_collection_promise",created.data.id,`Promesse de paiement · ${promisedDate}`,{clientId,invoiceId,amount,currency});return NextResponse.json({ok:true,promise:created.data},{status:201});
 }
 if(action==="promise_status"){
  const id=asText(body.promiseId,80),status=asText(body.status,20);if(!id||!["open","kept","missed","cancelled"].includes(status))return NextResponse.json({error:"Promesse ou statut invalide."},{status:422});const updated=await supabase.from("website_crm_collection_promises").update({status,kept_at:status==="kept"?now:null,updated_by:who,updated_at:now}).eq("id",id).select("*").single();if(updated.error)return NextResponse.json({error:updated.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_promise_status","crm_collection_promise",id,`Promesse · ${status}`,{status});return NextResponse.json({ok:true,promise:updated.data});
 }
 if(action==="create_task"){
  const clientId=asText(body.clientId,80),title=asText(body.title,240);if(!clientId||!title)return NextResponse.json({error:"Client et tâche obligatoires."},{status:422});const client=await supabase.from("website_crm_client_accounts").select("lead_id,owner,commercial_owner,account_name").eq("id",clientId).maybeSingle();if(client.error||!client.data)return NextResponse.json({error:"Client introuvable."},{status:404});const priority=asText(body.priority,20);const due=body.dueAt?new Date(String(body.dueAt)):new Date(Date.now()+24*3600000);if(Number.isNaN(due.getTime()))return NextResponse.json({error:"Échéance de tâche invalide."},{status:422});const created=await supabase.from("website_crm_tasks").insert({lead_id:client.data.lead_id,title,due_at:due.toISOString(),status:"todo",priority:["normal","high","urgent"].includes(priority)?priority:"normal",assigned_to:client.data.owner||client.data.commercial_owner||who,notes:nullable(body.notes),metadata:{source:"crm-collections",client_id:clientId}}).select("id").single();if(created.error)return NextResponse.json({error:created.error.message},{status:500});await writeAuditLog(supabase,session,"crm.collection_task_created","crm_task",created.data.id,`Tâche Collections · ${client.data.account_name}`,{clientId});return NextResponse.json({ok:true,taskId:created.data.id},{status:201});
 }
 return NextResponse.json({error:"Action non prise en charge."},{status:422});
}
