"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, KeyRound, Loader2, Plus, ShieldCheck, UserRound, XCircle } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Role={id:string;key:string;name:string;description:string|null;permissions:string[]};
type User={id:string;full_name:string;email:string;active:boolean;role_id:string;last_login_at:string|null;created_at:string;role:Role|null};

function date(value:string|null){return value?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Jamais"}

export default function TeamPage(){
 const [roles,setRoles]=useState<Role[]>([]);const [users,setUsers]=useState<User[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
 const [showCreate,setShowCreate]=useState(false);const [fullName,setFullName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [roleKey,setRoleKey]=useState("content");
 const activeCount=useMemo(()=>users.filter(user=>user.active).length,[users]);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setNotice("");const r=await fetch("/api/admin/team",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error??"Impossible de charger l’équipe.");setLoading(false);return;}setRoles(d.roles??[]);setUsers(d.users??[]);setLoading(false)}
 async function createUser(event:FormEvent){event.preventDefault();setSaving(true);setNotice("");const r=await fetch("/api/admin/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName,email,password,roleKey})});const d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error??"Création impossible.");setSaving(false);return;}setUsers(current=>[...current,d.user]);setFullName("");setEmail("");setPassword("");setShowCreate(false);setNotice("Compte créé. La personne peut maintenant se connecter au Control Center.");setSaving(false)}
 async function updateUser(user:User,patch:Record<string,unknown>){setNotice("");const r=await fetch("/api/admin/team",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:user.id,...patch})});const d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error??"Modification impossible.");return;}await load();setNotice("Compte mis à jour.")}
 async function resetPassword(user:User){const next=prompt(`Nouveau mot de passe pour ${user.full_name} (12 caractères minimum)`);if(!next)return;await updateUser(user,{password:next})}

 return <AdminWorkspace active="Équipe & rôles" title="Équipe & rôles" subtitle="Gérez les accès au Control Center avec des rôles séparés pour contenu, commercial, marketing, support et analyse." actions={<button onClick={()=>setShowCreate(v=>!v)} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-4 py-2.5 text-sm text-white"><Plus size={15}/>Ajouter un membre</button>}>
  {notice?<div className="mb-4 rounded-xl border border-[#5b2f22]/10 bg-[#f8eee7] px-4 py-3 text-sm text-[#5b2f22]/70">{notice}</div>:null}
  <div className="mb-4 grid gap-3 md:grid-cols-3"><AdminCard title="Membres actifs"><p className="moony-serif text-4xl">{loading?"—":activeCount}</p><p className="mt-1 text-xs text-[#5b2f22]/45">sur {users.length} comptes</p></AdminCard><AdminCard title="Rôles disponibles"><p className="moony-serif text-4xl">{roles.length||"—"}</p><p className="mt-1 text-xs text-[#5b2f22]/45">droits métiers préconfigurés</p></AdminCard><AdminCard title="Sécurité"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-700" size={26}/><div><p className="text-sm font-semibold">Accès par permissions</p><p className="text-xs text-[#5b2f22]/45">les API sensibles refusent les rôles non autorisés</p></div></div></AdminCard></div>

  {showCreate?<div className="mb-4"><AdminCard title="Nouveau membre"><form onSubmit={createUser} className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold">Nom complet<input required value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#5b2f22]/10 px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-semibold">E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#5b2f22]/10 px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-semibold">Mot de passe temporaire<input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#5b2f22]/10 px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-semibold">Rôle<select value={roleKey} onChange={e=>setRoleKey(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[#5b2f22]/10 px-3 py-3 text-sm font-normal">{roles.map(role=><option key={role.key} value={role.key}>{role.name}</option>)}</select></label><div className="md:col-span-2 xl:col-span-4 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={15}/>:<UserRound size={15}/>}Créer le compte</button></div></form></AdminCard></div>:null}

  <div className="grid gap-4 2xl:grid-cols-[1.35fr_.65fr]">
   <AdminCard title="Membres de l’équipe" action={<span className="text-xs text-[#5b2f22]/45">{loading?"Chargement…":`${users.length} comptes`}</span>}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs text-[#5b2f22]/45"><tr><th className="pb-3">Membre</th><th>Rôle</th><th>Dernière connexion</th><th>Statut</th><th className="text-right">Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-[#5b2f22]/8"><td className="py-4"><strong className="block">{user.full_name}</strong><span className="text-xs text-[#5b2f22]/45">{user.email}</span></td><td><select value={user.role?.key??""} onChange={e=>void updateUser(user,{roleKey:e.target.value})} className="rounded-lg border border-[#5b2f22]/10 bg-white px-2.5 py-2 text-xs">{roles.map(role=><option key={role.key} value={role.key}>{role.name}</option>)}</select></td><td className="text-xs text-[#5b2f22]/55">{date(user.last_login_at)}</td><td>{user.active?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-700"><CheckCircle2 size={12}/>Actif</span>:<span className="inline-flex items-center gap-1 rounded-full bg-zinc-100 px-2.5 py-1 text-xs text-zinc-600"><XCircle size={12}/>Désactivé</span>}</td><td><div className="flex justify-end gap-2"><button onClick={()=>void resetPassword(user)} className="inline-flex items-center gap-1 rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs"><KeyRound size={12}/>Mot de passe</button><button onClick={()=>void updateUser(user,{active:!user.active})} className={`rounded-lg border px-3 py-2 text-xs ${user.active?"border-red-100 text-red-700":"border-emerald-100 text-emerald-700"}`}>{user.active?"Désactiver":"Réactiver"}</button></div></td></tr>)}</tbody></table>{!loading&&!users.length?<p className="py-8 text-center text-sm text-[#5b2f22]/45">Aucun compte d’équipe pour le moment. Le mot de passe fondateur historique reste utilisable pour créer le premier compte.</p>:null}</div></AdminCard>

   <AdminCard title="Rôles & périmètres"><div className="space-y-3">{roles.map(role=><article key={role.key} className="rounded-xl border border-[#5b2f22]/9 bg-[#fffaf6] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{role.name}</strong><span className="rounded-full bg-white px-2 py-1 text-[10px] text-[#5b2f22]/50">{role.permissions.includes("*")?"Tous les droits":`${role.permissions.length} permissions`}</span></div><p className="mt-2 text-xs leading-5 text-[#5b2f22]/50">{role.description}</p></article>)}</div></AdminCard>
  </div>
 </AdminWorkspace>
}
