"use client";

import { FormEvent, useEffect, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type General={siteName:string;email:string;phone:string;whatsapp:string;publicUrl:string;appUrl:string};
type Integrations={calendlyUrl:string;brevoConfigured:boolean;analyticsProvider:string;googlePlayUrl:string;appStoreUrl:string};
const defaults={general:{siteName:"MOONY Africa",email:"contact@moonyafrica.com",phone:"",whatsapp:"",publicUrl:"https://www.moonyafrica.com",appUrl:"https://application.moony-africa.com"} as General,integrations:{calendlyUrl:"",brevoConfigured:false,analyticsProvider:"Interne MOONY",googlePlayUrl:"",appStoreUrl:""} as Integrations,privacy:{consentBanner:true,analyticsMode:"agrégé",retentionDays:365},branding:{partnerBannerTitle:"Ils nous font confiance"}};

export default function SettingsPage(){
 const [general,setGeneral]=useState(defaults.general);const [integrations,setIntegrations]=useState(defaults.integrations);const [privacy,setPrivacy]=useState(defaults.privacy);const [branding,setBranding]=useState(defaults.branding);const [message,setMessage]=useState("");
 useEffect(()=>{void (async()=>{const r=await fetch("/api/admin/settings",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();setGeneral({...defaults.general,...(d.settings?.general??{})});setIntegrations({...defaults.integrations,...(d.settings?.integrations??{})});setPrivacy({...defaults.privacy,...(d.settings?.privacy??{})});setBranding({...defaults.branding,...(d.settings?.branding??{})});})()},[]);
 async function save(e?:FormEvent){e?.preventDefault();setMessage("Enregistrement…");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({general,integrations,privacy,branding})});const d=await r.json();setMessage(r.ok?"Paramètres enregistrés.":d.error??"Erreur");}
 return <AdminWorkspace active="Paramètres" title="Paramètres" subtitle="Configurez les informations du site, les intégrations, les accès et les préférences du Control Center." actions={<button onClick={()=>void save()} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Enregistrer</button>}>
 <form onSubmit={save} className="grid gap-4 xl:grid-cols-2"><AdminCard title="Informations générales"><div className="grid gap-4 sm:grid-cols-2"><label>Nom du site<input value={general.siteName} onChange={e=>setGeneral({...general,siteName:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Email<input type="email" value={general.email} onChange={e=>setGeneral({...general,email:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Téléphone<input value={general.phone} onChange={e=>setGeneral({...general,phone:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>WhatsApp<input value={general.whatsapp} onChange={e=>setGeneral({...general,whatsapp:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>URL publique<input value={general.publicUrl} onChange={e=>setGeneral({...general,publicUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Application<input value={general.appUrl} onChange={e=>setGeneral({...general,appUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label></div></AdminCard>
 <AdminCard title="Intégrations"><div className="space-y-4 text-sm"><label className="block">Lien Calendly<input value={integrations.calendlyUrl} onChange={e=>setIntegrations({...integrations,calendlyUrl:e.target.value})} placeholder="https://calendly.com/…" className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block">Mesure d’audience<select value={integrations.analyticsProvider} onChange={e=>setIntegrations({...integrations,analyticsProvider:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"><option>Interne MOONY</option><option>Plausible</option><option>Google Analytics</option><option>Désactivée</option></select></label><label className="block">Google Play<input value={integrations.googlePlayUrl} onChange={e=>setIntegrations({...integrations,googlePlayUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block">App Store<input value={integrations.appStoreUrl} onChange={e=>setIntegrations({...integrations,appStoreUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><div className="rounded-lg border border-[#5b2f22]/8 bg-white px-4 py-3"><strong>Brevo</strong><p className="mt-1 text-xs text-[#5b2f22]/50">La connexion utilise la variable serveur BREVO_API_KEY. La clé n’est jamais affichée dans le navigateur.</p></div></div></AdminCard>
 <AdminCard title="Marque & affichage"><label className="block text-sm">Titre de la bannière partenaires<input value={branding.partnerBannerTitle} onChange={e=>setBranding({...branding,partnerBannerTitle:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><p className="mt-4 text-xs leading-5 text-[#5b2f22]/50">Les couleurs structurantes de MOONY restent verrouillées par défaut pour préserver la cohérence de la charte graphique.</p></AdminCard>
 <AdminCard title="Confidentialité"><div className="space-y-4 text-sm"><label className="flex items-center justify-between gap-4"><span><strong className="block">Bannière de consentement</strong><span className="text-xs text-[#5b2f22]/45">Prévue pour les outils non essentiels.</span></span><input type="checkbox" checked={privacy.consentBanner} onChange={e=>setPrivacy({...privacy,consentBanner:e.target.checked})}/></label><label className="block">Mode analytics<select value={privacy.analyticsMode} onChange={e=>setPrivacy({...privacy,analyticsMode:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"><option value="agrégé">Agrégé et privacy-first</option><option value="désactivé">Désactivé</option></select></label><label className="block">Durée de conservation (jours)<input type="number" min={30} max={730} value={privacy.retentionDays} onChange={e=>setPrivacy({...privacy,retentionDays:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><p className="text-xs leading-5 text-[#5b2f22]/55">Aucune déduction de genre, d’état de santé ou d’autres caractéristiques sensibles à partir du comportement de navigation.</p></div></AdminCard>
 <div className="xl:col-span-2 flex items-center gap-4"><button className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Enregistrer les paramètres</button><span className="text-xs text-[#5b2f22]/50">{message}</span></div></form>
 </AdminWorkspace>;
}
