"use client";

import { FormEvent, useEffect, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type General={siteName:string;email:string;phone:string;whatsapp:string;publicUrl:string;appUrl:string};
type Integrations={calendlyUrl:string;brevoConfigured:boolean;analyticsProvider:string;googlePlayUrl:string;appStoreUrl:string};
type PricingPlan={key:"monthly"|"quarterly"|"semiannual"|"annual";name:string;price:number;unit:string;featured?:boolean;active?:boolean};
type Pricing={currency:string;teleconsultationCommission:number;plans:PricingPlan[];companyMode:"quote";companyLabel:string};

const defaultPlans:PricingPlan[]=[
 {key:"monthly",name:"Mensuel",price:15000,unit:"/ mois",featured:false,active:true},
 {key:"quarterly",name:"Trimestriel",price:42000,unit:"/ trimestre",featured:true,active:true},
 {key:"semiannual",name:"Semestriel",price:75000,unit:"/ 6 mois",featured:false,active:true},
 {key:"annual",name:"Annuel",price:150000,unit:"/ an",featured:false,active:true},
];

const defaults={
 general:{siteName:"MOONY Africa",email:"contact@moonyafrica.com",phone:"",whatsapp:"",publicUrl:"https://www.moonyafrica.com",appUrl:"https://application.moony-africa.com"} as General,
 integrations:{calendlyUrl:"",brevoConfigured:false,analyticsProvider:"Interne MOONY",googlePlayUrl:"",appStoreUrl:""} as Integrations,
 privacy:{consentBanner:true,analyticsMode:"agrégé",retentionDays:365},
 branding:{partnerBannerTitle:"Ils nous font confiance"},
 pricing:{currency:"FCFA",teleconsultationCommission:3,plans:defaultPlans,companyMode:"quote",companyLabel:"Tarification sur mesure selon la taille de l’entreprise."} as Pricing,
};

export default function SettingsPage(){
 const [general,setGeneral]=useState(defaults.general);const [integrations,setIntegrations]=useState(defaults.integrations);const [privacy,setPrivacy]=useState(defaults.privacy);const [branding,setBranding]=useState(defaults.branding);const [pricing,setPricing]=useState(defaults.pricing);const [message,setMessage]=useState("");
 useEffect(()=>{void (async()=>{const r=await fetch("/api/admin/settings",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();setGeneral({...defaults.general,...(d.settings?.general??{})});setIntegrations({...defaults.integrations,...(d.settings?.integrations??{})});setPrivacy({...defaults.privacy,...(d.settings?.privacy??{})});setBranding({...defaults.branding,...(d.settings?.branding??{})});const savedPricing=d.settings?.pricing??{};setPricing({...defaults.pricing,...savedPricing,plans:Array.isArray(savedPricing.plans)&&savedPricing.plans.length?savedPricing.plans:defaultPlans});})()},[]);
 async function save(e?:FormEvent){e?.preventDefault();setMessage("Enregistrement…");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({general,integrations,privacy,branding,pricing})});const d=await r.json();setMessage(r.ok?"Paramètres enregistrés.":d.error??"Erreur");}
 function updatePlan(index:number,patch:Partial<PricingPlan>){setPricing(current=>({...current,plans:current.plans.map((plan,i)=>i===index?{...plan,...patch}:plan)}))}
 return <AdminWorkspace active="Paramètres" title="Paramètres" subtitle="Configurez le site, les tarifs, les intégrations et les préférences du Control Center." actions={<button onClick={()=>void save()} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Enregistrer</button>}>
 <form onSubmit={save} className="grid gap-4 xl:grid-cols-2">
  <AdminCard title="Informations générales"><div className="grid gap-4 sm:grid-cols-2"><label>Nom du site<input value={general.siteName} onChange={e=>setGeneral({...general,siteName:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Email<input type="email" value={general.email} onChange={e=>setGeneral({...general,email:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Téléphone<input value={general.phone} onChange={e=>setGeneral({...general,phone:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>WhatsApp<input value={general.whatsapp} onChange={e=>setGeneral({...general,whatsapp:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>URL publique<input value={general.publicUrl} onChange={e=>setGeneral({...general,publicUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label><label>Application<input value={general.appUrl} onChange={e=>setGeneral({...general,appUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-3 text-sm"/></label></div></AdminCard>

  <AdminCard title="Intégrations"><div className="space-y-4 text-sm"><label className="block">Lien Calendly<input value={integrations.calendlyUrl} onChange={e=>setIntegrations({...integrations,calendlyUrl:e.target.value})} placeholder="https://calendly.com/…" className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block">Mesure d’audience<select value={integrations.analyticsProvider} onChange={e=>setIntegrations({...integrations,analyticsProvider:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"><option>Interne MOONY</option><option>Plausible</option><option>Google Analytics</option><option>Désactivée</option></select></label><label className="block">Google Play<input value={integrations.googlePlayUrl} onChange={e=>setIntegrations({...integrations,googlePlayUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block">App Store<input value={integrations.appStoreUrl} onChange={e=>setIntegrations({...integrations,appStoreUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><div className="rounded-lg border border-[#5b2f22]/8 bg-white px-4 py-3"><strong>Brevo</strong><p className="mt-1 text-xs text-[#5b2f22]/50">La connexion utilise la variable serveur BREVO_API_KEY. La clé n’est jamais affichée dans le navigateur.</p></div></div></AdminCard>

  <div className="xl:col-span-2"><AdminCard title="Tarifs MOONY Pro" action={<span className="rounded-full bg-[#f7e7dc] px-3 py-1 text-xs text-[#8d3b19]">Visible sur la page Services</span>}>
   <div className="grid gap-4 lg:grid-cols-[1fr_260px]">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{pricing.plans.map((plan,index)=><div key={plan.key} className={`rounded-xl border p-4 ${plan.featured?"border-[#c8754e] bg-[#fbf0e8]":"border-[#5b2f22]/10 bg-white"}`}><div className="flex items-center justify-between gap-2"><strong className="text-sm">{plan.name}</strong><label className="text-[10px] text-[#5b2f22]/55"><input type="checkbox" checked={plan.active!==false} onChange={e=>updatePlan(index,{active:e.target.checked})} className="mr-1"/>Actif</label></div><label className="mt-4 block text-xs">Prix<input type="number" min={0} value={plan.price} onChange={e=>updatePlan(index,{price:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="mt-3 block text-xs">Unité<input value={plan.unit} onChange={e=>updatePlan(index,{unit:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="mt-3 flex items-center gap-2 text-xs"><input type="radio" name="featuredPlan" checked={!!plan.featured} onChange={()=>setPricing(current=>({...current,plans:current.plans.map((item,i)=>({...item,featured:i===index}))}))}/> Mettre en avant</label></div>)}</div>
    <div className="space-y-4"><label className="block text-sm">Devise<input value={pricing.currency} onChange={e=>setPricing({...pricing,currency:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block text-sm">Commission téléconsultation (%)<input type="number" min={0} max={100} step="0.1" value={pricing.teleconsultationCommission} onChange={e=>setPricing({...pricing,teleconsultationCommission:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><label className="block text-sm">Libellé offre entreprise<textarea rows={3} value={pricing.companyLabel} onChange={e=>setPricing({...pricing,companyLabel:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><p className="rounded-lg bg-[#f8eee7] p-3 text-xs leading-5 text-[#5b2f22]/55">Le prix par salariée reste volontairement masqué sur le site public. L’offre entreprise reste sur devis.</p></div>
   </div>
  </AdminCard></div>

  <AdminCard title="Marque & affichage"><label className="block text-sm">Titre de la bannière partenaires<input value={branding.partnerBannerTitle} onChange={e=>setBranding({...branding,partnerBannerTitle:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><p className="mt-4 text-xs leading-5 text-[#5b2f22]/50">Les couleurs structurantes de MOONY restent verrouillées par défaut pour préserver la cohérence de la charte graphique.</p></AdminCard>

  <AdminCard title="Confidentialité"><div className="space-y-4 text-sm"><label className="flex items-center justify-between gap-4"><span><strong className="block">Bannière de consentement</strong><span className="text-xs text-[#5b2f22]/45">Prévue pour les outils non essentiels.</span></span><input type="checkbox" checked={privacy.consentBanner} onChange={e=>setPrivacy({...privacy,consentBanner:e.target.checked})}/></label><label className="block">Mode analytics<select value={privacy.analyticsMode} onChange={e=>setPrivacy({...privacy,analyticsMode:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"><option value="agrégé">Agrégé et privacy-first</option><option value="désactivé">Désactivé</option></select></label><label className="block">Durée de conservation (jours)<input type="number" min={30} max={730} value={privacy.retentionDays} onChange={e=>setPrivacy({...privacy,retentionDays:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-3"/></label><p className="text-xs leading-5 text-[#5b2f22]/55">Aucune déduction de genre, d’état de santé ou d’autres caractéristiques sensibles à partir du comportement de navigation.</p></div></AdminCard>

  <div className="xl:col-span-2 flex items-center gap-4"><button className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Enregistrer les paramètres</button><span className="text-xs text-[#5b2f22]/50">{message}</span></div>
 </form>
 </AdminWorkspace>;
}
