"use client";

import { useEffect, useState } from "react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Section={title:string;body:string};
type CmsPage={id:string;title:string;slug:string;status:string;hero:Record<string,string>;sections:unknown[]};
const defaultSections:Section[]=[{title:"Notre histoire",body:"L’origine de MOONY et notre chemin."},{title:"Notre mission",body:"Ce en quoi nous croyons."},{title:"Portrait des fondatrices",body:"Les femmes derrière MOONY."},{title:"Nos valeurs",body:"Ce qui nous guide au quotidien."},{title:"Notre impact",body:"Nos ambitions et nos résultats."},{title:"Notre équipe",body:"Les visages derrière MOONY."}];

export default function AboutAdmin(){
 const [page,setPage]=useState<CmsPage|null>(null);const [hero,setHero]=useState({eyebrow:"À propos",title:"Une histoire de soin,\nde transmission\net d’horizons.",body:"MOONY est née du désir d’offrir aux femmes un espace de santé plus proche, plus doux et plus enraciné dans leurs réalités.",imageUrl:"/images/home-hero.jpg"});const [sections,setSections]=useState<Section[]>(defaultSections);const [message,setMessage]=useState("");
 useEffect(()=>{void (async()=>{const r=await fetch("/api/admin/pages",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return;}const d=await r.json();const found=(d.pages??[]).find((x:CmsPage)=>x.slug==="/a-propos");if(found){setPage(found);setHero(current=>({...current,...found.hero}));const parsed=(found.sections??[]).filter((x:unknown)=>typeof x==="object"&&x!==null&&"title" in x) as Section[];if(parsed.length)setSections(parsed)}})()},[]);
 async function save(status?:string){if(!page)return;setMessage("Enregistrement…");const r=await fetch("/api/admin/pages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:page.id,hero,sections,status:status??page.status})});const d=await r.json();if(!r.ok){setMessage(d.error??"Erreur");return;}setPage(d.page);setMessage(status==="published"?"Page publiée.":"Modifications enregistrées.")}
 function updateSection(index:number,key:keyof Section,value:string){setSections(current=>current.map((x,i)=>i===index?{...x,[key]:value}:x))}
 function move(index:number,direction:-1|1){const next=[...sections];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setSections(next)}
 return <AdminWorkspace active="À propos" title="À propos" subtitle="Racontez l’histoire de MOONY, présentez l’équipe et organisez les sections de confiance." actions={<><a href="/a-propos" target="_blank" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Voir la page ↗</a><button onClick={()=>void save("published")} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Publier</button></>}>
 <div className="grid gap-4 xl:grid-cols-[1fr_.9fr]"><div className="space-y-4"><AdminCard title="Éditeur de la page À propos"><div className="space-y-4"><label className="block text-sm">Sur-titre<input value={hero.eyebrow} onChange={e=>setHero({...hero,eyebrow:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label><label className="block text-sm">Titre principal<textarea rows={4} value={hero.title} onChange={e=>setHero({...hero,title:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 moony-serif text-2xl"/></label><label className="block text-sm">Introduction<textarea rows={4} value={hero.body} onChange={e=>setHero({...hero,body:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 leading-6"/></label><label className="block text-sm">Image de couverture<input value={hero.imageUrl} onChange={e=>setHero({...hero,imageUrl:e.target.value})} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5"/></label></div></AdminCard><AdminCard title="Sections de la page"><div className="space-y-3">{sections.map((section,index)=><div key={`${section.title}-${index}`} className="rounded-xl border border-[#5b2f22]/8 bg-white p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">Section {index+1}</strong><div className="flex gap-1"><button onClick={()=>move(index,-1)} className="rounded border border-[#5b2f22]/10 px-2 py-1 text-xs">↑</button><button onClick={()=>move(index,1)} className="rounded border border-[#5b2f22]/10 px-2 py-1 text-xs">↓</button><button onClick={()=>setSections(current=>current.filter((_,i)=>i!==index))} className="rounded border border-red-100 px-2 py-1 text-xs text-red-700">×</button></div></div><input value={section.title} onChange={e=>updateSection(index,"title",e.target.value)} className="mt-3 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-sm font-semibold"/><textarea rows={3} value={section.body} onChange={e=>updateSection(index,"body",e.target.value)} className="mt-2 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-sm"/></div>)}</div><button onClick={()=>setSections(current=>[...current,{title:"Nouvelle section",body:""}])} className="mt-4 rounded-lg border border-[#5b2f22]/12 px-4 py-2.5 text-sm">+ Ajouter une section</button></AdminCard><div className="flex items-center gap-4"><button onClick={()=>void save()} className="rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white">Enregistrer</button><span className="text-xs text-[#5b2f22]/50">{message}</span></div></div>
 <AdminCard title="Aperçu de publication"><div className="min-h-[620px] rounded-xl bg-cover bg-center p-8" style={{backgroundImage:`linear-gradient(90deg,rgba(255,248,240,.95),rgba(255,248,240,.25)),url('${hero.imageUrl}')`}}><p className="text-sm">{hero.eyebrow}</p><h3 className="moony-serif mt-4 max-w-md whitespace-pre-line text-5xl leading-[.95]">{hero.title}</h3><p className="mt-5 max-w-md text-sm leading-6">{hero.body}</p><div className="mt-10 space-y-3">{sections.slice(0,4).map(s=><div key={s.title} className="max-w-md rounded-lg bg-white/70 p-3 backdrop-blur-sm"><strong className="moony-serif text-xl">{s.title}</strong><p className="mt-1 text-xs leading-5 text-[#5b2f22]/65">{s.body}</p></div>)}</div></div></AdminCard></div>
 </AdminWorkspace>;
}
