"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CheckCircle2, ClipboardCheck, FileCheck2, FileSignature, RefreshCw, Save, UserRoundCheck } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Lead={id:string;first_name:string;last_name:string;email:string;company:string|null;country:string|null;need:string|null};
type Opportunity={id:string;name:string;stage:string;amount:number;currency:string;owner:string|null;expected_close_date:string|null};
type Proposal={id:string;reference:string;title:string;total_amount:number;currency:string;status:string;accepted_at:string|null};
type Case={id:string;opportunity_id:string;proposal_id:string|null;lead_id:string;status:string;owner:string|null;commercial_owner:string|null;handoff_at:string;kickoff_at:string|null;target_go_live_date:string|null;completed_at:string|null;notes:string|null;created_at:string;updated_at:string;website_crm_opportunities:Opportunity|null;website_crm_proposals:Proposal|null;website_leads:Lead|null};
type Task={id:string;onboarding_id:string;title:string;category:string;status:string;required:boolean;owner:string|null;due_at:string|null;completed_at:string|null;notes:string|null;sort_order:number};
type DocumentRow={id:string;onboarding_id:string;name:string;description:string|null;status:string;required:boolean;due_at:string|null;document_url:string|null;notes:string|null};
type Contract={id:string;onboarding_id:string;proposal_id:string|null;reference:string;version:number;title:string;status:string;body:string|null;effective_date:string|null;signed_at:string|null;signed_by:string|null;signed_by_email:string|null;sent_at:string|null;created_at:string};
type EventRow={id:string;event_type:string;title:string;detail:string|null;actor:string|null;created_at:string};
type WonDeal={id:string;name:string;lead_id:string;owner:string|null;amount:number;currency:string;website_leads:Lead|null};
type Payload={available:boolean;cases:Case[];tasks:Record<string,Task[]>;documents:Record<string,DocumentRow[]>;contracts:Record<string,Contract[]>;events:Record<string,EventRow[]>;wonWithoutOnboarding:WonDeal[];metrics:{active:number;blocked:number;live:number;completed:number}};
const empty:Payload={available:true,cases:[],tasks:{},documents:{},contracts:{},events:{},wonWithoutOnboarding:[],metrics:{active:0,blocked:0,live:0,completed:0}};
const caseLabels:Record<string,string>={handoff:"Passage",contract:"Contrat",documents:"Documents",kickoff:"Kickoff",implementation:"Déploiement",live:"En service",blocked:"Bloqué",completed:"Terminé"};
const taskLabels:Record<string,string>={todo:"À faire",in_progress:"En cours",blocked:"Bloquée",done:"Terminée"};
const docLabels:Record<string,string>={required:"À fournir",requested:"Demandé",received:"Reçu",validated:"Validé",rejected:"À corriger",not_applicable:"Non applicable"};
const contractLabels:Record<string,string>={draft:"Brouillon",ready:"Prêt",sent:"Envoyé",signed:"Signé",cancelled:"Annulé"};
function money(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0))}catch{return`${Math.round(Number(value||0)).toLocaleString("fr-FR")} ${currency}`}}
function date(value:string|null){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(d)}
function clientName(row:Case){const lead=row.website_leads;return lead?.company||`${lead?.first_name||""} ${lead?.last_name||""}`.trim()||lead?.email||"Client"}

export default function OnboardingPage(){
 const [data,setData]=useState<Payload>(empty);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");const [selectedId,setSelectedId]=useState("");const [search,setSearch]=useState("");
 const [caseDraft,setCaseDraft]=useState({status:"handoff",owner:"",kickoffAt:"",targetGoLiveDate:"",notes:""});const [newTask,setNewTask]=useState({title:"",owner:"",dueAt:""});const [newDoc,setNewDoc]=useState({name:"",dueAt:""});const [contractDraft,setContractDraft]=useState({title:"",body:"",status:"draft",effectiveDate:"",signedBy:"",signedByEmail:""});
 async function load(silent=false){if(!silent)setLoading(true);try{const response=await fetch("/api/admin/crm/onboarding",{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Impossible de charger l’onboarding.");return}const next={...empty,...payload} as Payload;setData(next);const requested=typeof window!=="undefined"?new URLSearchParams(location.search).get("case"):null;setSelectedId((current)=>current&&next.cases.some((row)=>row.id===current)?current:requested&&next.cases.some((row)=>row.id===requested)?requested:(next.cases[0]?.id||""))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const selected=data.cases.find((row)=>row.id===selectedId)||null;
 useEffect(()=>{if(!selected)return;setCaseDraft({status:selected.status,owner:selected.owner||"",kickoffAt:selected.kickoff_at?selected.kickoff_at.slice(0,16):"",targetGoLiveDate:selected.target_go_live_date||"",notes:selected.notes||""});const contract=data.contracts[selected.id]?.[0];setContractDraft({title:contract?.title||"",body:contract?.body||"",status:contract?.status||"draft",effectiveDate:contract?.effective_date||"",signedBy:contract?.signed_by||"",signedByEmail:contract?.signed_by_email||""})},[selectedId,selected?.updated_at,data.contracts]);
 const visible=useMemo(()=>data.cases.filter((row)=>[clientName(row),row.website_crm_opportunities?.name,row.owner,row.commercial_owner,row.status].join(" ").toLowerCase().includes(search.toLowerCase())),[data.cases,search]);
 const tasks=selected?data.tasks[selected.id]||[]:[];const documents=selected?data.documents[selected.id]||[]:[];const contracts=selected?data.contracts[selected.id]||[]:[];const events=selected?data.events[selected.id]||[]:[];const latestContract=contracts[0]||null;
 async function patch(body:Record<string,unknown>,message:string){setBusy(String(body.entity||"patch"));try{const response=await fetch("/api/admin/crm/onboarding",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Mise à jour impossible.");return false}setNotice(message);await load(true);return true}finally{setBusy("")}}
 async function post(body:Record<string,unknown>,message:string){setBusy(String(body.action||"post"));try{const response=await fetch("/api/admin/crm/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||"Action impossible.");return false}setNotice(message);await load(true);return true}finally{setBusy("")}}
 async function saveCase(){if(!selected)return;await patch({entity:"case",id:selected.id,...caseDraft},"Dossier d’onboarding enregistré.")}
 async function addTask(){if(!selected||!newTask.title.trim())return;if(await post({action:"task",onboardingId:selected.id,...newTask},"Tâche ajoutée."))setNewTask({title:"",owner:"",dueAt:""})}
 async function addDocument(){if(!selected||!newDoc.name.trim())return;if(await post({action:"document",onboardingId:selected.id,...newDoc},"Document requis ajouté."))setNewDoc({name:"",dueAt:""})}
 async function saveContract(){if(!latestContract)return;await patch({entity:"contract",id:latestContract.id,...contractDraft},"Contrat enregistré.")}
 async function ensure(opportunityId:string){await post({action:"ensure",opportunityId},"Dossier post-signature créé.")}

 return <AdminWorkspace active="Onboarding" title="Contrats & onboarding" subtitle="Transformez une vente signée en dossier opérationnel : handoff, contrat, documents, checklist, kickoff et mise en service." actions={<button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><RefreshCw size={15}/> Actualiser</button>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911062000_crm_contracts_onboarding.sql</strong> pour activer CRM V7.</div>:null}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="admin-card admin-shadow p-5"><BriefcaseBusiness size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{loading?"…":data.metrics.active}</strong><span className="text-[10px] text-[#5b2f22]/45">Onboardings actifs</span></article><article className="admin-card admin-shadow p-5"><ClipboardCheck size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.blocked}</strong><span className="text-[10px] text-[#5b2f22]/45">Bloqués</span></article><article className="admin-card admin-shadow p-5"><UserRoundCheck size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.live}</strong><span className="text-[10px] text-[#5b2f22]/45">En service</span></article><article className="admin-card admin-shadow p-5"><CheckCircle2 size={17} className="text-[#9d4c27]"/><strong className="moony-serif mt-3 block text-2xl font-normal">{data.metrics.completed}</strong><span className="text-[10px] text-[#5b2f22]/45">Terminés</span></article></div>

  {data.wonWithoutOnboarding.length?<section className="admin-card admin-shadow mt-5 p-5"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#9d4c27]">À synchroniser</p><h2 className="moony-serif mt-1 text-2xl">Ventes signées sans dossier</h2><div className="mt-3 flex flex-wrap gap-2">{data.wonWithoutOnboarding.map((deal)=><button key={deal.id} onClick={()=>void ensure(deal.id)} className="rounded-full border border-[#5b2f22]/12 bg-white px-3 py-2 text-[10px]">Créer · {deal.website_leads?.company||deal.name}</button>)}</div></section>:null}

  <div className="mt-5 grid gap-4 2xl:grid-cols-[.62fr_1.38fr]">
   <section className="admin-card admin-shadow overflow-hidden"><div className="border-b border-[#5b2f22]/8 p-4"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Rechercher client, deal, responsable…" className="w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-xs"/></div><div className="max-h-[1100px] divide-y divide-[#5b2f22]/7 overflow-auto">{visible.length?visible.map((row)=><button key={row.id} onClick={()=>setSelectedId(row.id)} className={`w-full p-4 text-left ${selectedId===row.id?"bg-[#f6e5d9]":"hover:bg-[#fffaf6]"}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{clientName(row)}</strong><p className="mt-1 text-[10px] text-[#5b2f22]/45">{row.website_crm_opportunities?.name||"Deal"}</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] text-[#7e3518]">{caseLabels[row.status]||row.status}</span></div><p className="mt-3 text-[9px] text-[#5b2f22]/45">Ops : {row.owner||"à assigner"} · Commercial : {row.commercial_owner||"—"}</p></button>):<p className="p-10 text-center text-xs text-[#5b2f22]/40">Aucun dossier.</p>}</div></section>

   {selected?<div className="space-y-4">
    <AdminCard title="Dossier client" action={<button onClick={()=>void saveCase()} disabled={busy==="case"} className="inline-flex items-center gap-2 rounded-lg bg-[#7e3518] px-4 py-2 text-xs text-white"><Save size={13}/> Enregistrer</button>}><div className="flex flex-wrap items-center gap-2 border-b border-[#5b2f22]/8 pb-4 text-[10px]"><strong>{clientName(selected)}</strong>{selected.website_crm_proposals?<span>{selected.website_crm_proposals.reference}</span>:null}<Link href={`/admin/opportunites?opportunity=${selected.opportunity_id}`} className="rounded-full bg-[#f8eee7] px-3 py-1.5 text-[#7e3518]">Ouvrir le deal</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-[10px] text-[#5b2f22]/50">Étape<select value={caseDraft.status} onChange={(e)=>setCaseDraft((d)=>({...d,status:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-sm">{Object.entries(caseLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[10px] text-[#5b2f22]/50">Responsable opérations<input value={caseDraft.owner} onChange={(e)=>setCaseDraft((d)=>({...d,owner:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Kickoff<input type="datetime-local" value={caseDraft.kickoffAt} onChange={(e)=>setCaseDraft((d)=>({...d,kickoffAt:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Go-live cible<input type="date" value={caseDraft.targetGoLiveDate} onChange={(e)=>setCaseDraft((d)=>({...d,targetGoLiveDate:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50 md:col-span-2 xl:col-span-4">Notes<textarea rows={3} value={caseDraft.notes} onChange={(e)=>setCaseDraft((d)=>({...d,notes:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label></div></AdminCard>

    <div className="grid gap-4 xl:grid-cols-2"><AdminCard title="Checklist onboarding" action={<ClipboardCheck size={16} className="text-[#9d4c27]"/>}><div className="space-y-2">{tasks.map((task)=><div key={task.id} className="rounded-xl border border-[#5b2f22]/8 p-3"><div className="flex items-center gap-3"><select value={task.status} onChange={(e)=>void patch({entity:"task",id:task.id,status:e.target.value},"Tâche mise à jour.")} className="rounded-lg border border-[#5b2f22]/10 bg-white px-2 py-1 text-[9px]">{Object.entries(taskLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="min-w-0 flex-1"><strong className="text-xs">{task.title}</strong><p className="mt-1 text-[9px] text-[#5b2f22]/45">{task.category} · échéance {date(task.due_at)}</p></div></div></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={newTask.title} onChange={(e)=>setNewTask((d)=>({...d,title:e.target.value}))} placeholder="Nouvelle tâche" className="rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs sm:col-span-2"/><button onClick={()=>void addTask()} className="rounded-lg bg-[#7e3518] px-3 py-2 text-xs text-white">Ajouter</button></div></AdminCard>

    <AdminCard title="Documents à fournir" action={<FileCheck2 size={16} className="text-[#9d4c27]"/>}><div className="space-y-2">{documents.map((doc)=><div key={doc.id} className="rounded-xl border border-[#5b2f22]/8 p-3"><div className="flex items-start gap-3"><select value={doc.status} onChange={(e)=>void patch({entity:"document",id:doc.id,status:e.target.value},"Document mis à jour.")} className="rounded-lg border border-[#5b2f22]/10 bg-white px-2 py-1 text-[9px]">{Object.entries(docLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="min-w-0 flex-1"><strong className="text-xs">{doc.name}</strong>{doc.description?<p className="mt-1 text-[9px] leading-4 text-[#5b2f22]/45">{doc.description}</p>:null}{doc.document_url?<a href={doc.document_url} target="_blank" rel="noreferrer" className="mt-1 block text-[9px] text-[#7e3518]">Ouvrir le document lié</a>:null}</div></div></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={newDoc.name} onChange={(e)=>setNewDoc((d)=>({...d,name:e.target.value}))} placeholder="Document / information" className="rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs sm:col-span-2"/><button onClick={()=>void addDocument()} className="rounded-lg bg-[#7e3518] px-3 py-2 text-xs text-white">Ajouter</button></div></AdminCard></div>

    <AdminCard title="Contrat" action={<FileSignature size={16} className="text-[#9d4c27]"/>}>{latestContract?<><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-5 text-amber-800">Le contrat généré est un <strong>brouillon opérationnel</strong>. Il doit être relu et validé juridiquement avant tout envoi ou signature.</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-[10px] text-[#5b2f22]/50 md:col-span-2">Titre<input value={contractDraft.title} onChange={(e)=>setContractDraft((d)=>({...d,title:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Statut<select value={contractDraft.status} onChange={(e)=>setContractDraft((d)=>({...d,status:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-sm">{Object.entries(contractLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[10px] text-[#5b2f22]/50">Date d’effet<input type="date" value={contractDraft.effectiveDate} onChange={(e)=>setContractDraft((d)=>({...d,effectiveDate:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">Signataire<input value={contractDraft.signedBy} onChange={(e)=>setContractDraft((d)=>({...d,signedBy:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50">E-mail signataire<input value={contractDraft.signedByEmail} onChange={(e)=>setContractDraft((d)=>({...d,signedByEmail:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="text-[10px] text-[#5b2f22]/50 md:col-span-2 xl:col-span-4">Contenu<textarea rows={14} value={contractDraft.body} onChange={(e)=>setContractDraft((d)=>({...d,body:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 font-mono text-xs leading-5"/></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-[9px] text-[#5b2f22]/45">{latestContract.reference} · V{latestContract.version} · créé {date(latestContract.created_at)}</p><div className="flex gap-2"><button onClick={()=>void post({action:"contract_version",onboardingId:selected.id},"Nouvelle version de contrat créée.")} className="rounded-lg border border-[#5b2f22]/12 bg-white px-3 py-2 text-xs">Créer une version</button><button onClick={()=>void saveContract()} disabled={busy==="contract"} className="rounded-lg bg-[#7e3518] px-4 py-2 text-xs text-white">Enregistrer le contrat</button></div></div></>:<p className="py-8 text-center text-xs text-[#5b2f22]/40">Aucun contrat généré.</p>}</AdminCard>

    <AdminCard title="Historique du passage client"><div className="space-y-3">{events.map((event)=><div key={event.id} className="border-l-2 border-[#d8bda9] pl-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-xs">{event.title}</strong><span className="text-[9px] text-[#5b2f22]/40">{date(event.created_at)}</span></div>{event.detail?<p className="mt-1 text-[10px] leading-5 text-[#5b2f22]/55">{event.detail}</p>:null}<p className="mt-1 text-[9px] text-[#5b2f22]/35">{event.actor||"MOONY"}</p></div>)}</div></AdminCard>
   </div>:<section className="admin-card admin-shadow grid min-h-[380px] place-items-center text-xs text-[#5b2f22]/40">Sélectionnez un dossier.</section>}
  </div>
 </AdminWorkspace>;
}
