"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { BarChart3,CheckCircle2,Download,FileLock2,RefreshCw,Save,ShieldAlert,TrendingUp,UsersRound } from "lucide-react";
import { AdminCard,AdminWorkspace } from "@/components/admin-workspace";

type RevenueMetric={currency:string;currentMrr:number;currentArr:number;startingMrr:number;newMrr:number;expansionMrr:number;contractionMrr:number;churnMrr:number;nrr:number|null;grr:number|null;invoicedMonth:number;collectedMonth:number;outstanding:number;overdue:number;dso:number|null;topClientShare:number;top5Share:number};
type MoneyBucket={currency:string;amount:number;weighted?:number;count:number;unscored?:number;commit?:number;bestCase?:number;pipeline?:number;renewal?:number;expansion?:number};
type Metrics={capturedAt:string;periodMonth:string;revenue:{available:boolean;baseline:string|null;currencies:RevenueMetric[];trend:any[];accounts:any[]};commercial:{leadsTotal:number;leadsCreatedInPeriod:number;leadStages:Record<string,number>;opportunitiesTotal:number;openOpportunities:number;wonOpportunities:number;lostOpportunities:number;proposalsTotal:number;proposalsAcceptedInPeriod:number;pipelineByCurrency:MoneyBucket[];wonByCurrency:MoneyBucket[]};customers:{total:number;active:number;healthy:number;watch:number;atRisk:number;critical:number;renewals90:number};forecast:{byCurrency:Array<MoneyBucket&{renewal:number;expansion:number}>};voice:{open:number;critical:number;planned:number;closed:number;topThemes:Array<{theme:string;count:number}>};escalations:{available:boolean;open:number;critical:number};dataQuality:{revenue:boolean;commercial:boolean;customerSuccess:boolean;renewalForecast:boolean;voiceOfCustomer:boolean;escalations:boolean;notes:string[]}};
type Report={id:string;period_month:string;title:string;status:"draft"|"final";metrics:Metrics;data_quality:Metrics["dataQuality"];highlights:string|null;risks:string|null;priorities:string|null;decisions:string|null;captured_at:string;captured_by:string|null;finalized_at:string|null;finalized_by:string|null;updated_at:string};
type Payload={available:boolean;currentMonth:string;reports:Report[];live:Metrics|null;liveError?:string};
const empty:Payload={available:true,currentMonth:"",reports:[],live:null};
const stageLabels:Record<string,string>={new:"Nouveau",to_contact:"À contacter",contacted:"Contacté",appointment:"RDV",proposal:"Proposition",negotiation:"Négociation",won:"Gagné",lost:"Perdu"};
function money(value:number,currency:string){try{return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0))}catch{return`${Math.round(Number(value||0)).toLocaleString("fr-FR")} ${currency}`}}
function pct(value:number|null|undefined){return value==null?"—":`${value.toFixed(1)} %`}
function monthLabel(value:string){if(!value)return"—";return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(`${value.slice(0,7)}-15T12:00:00`))}
function date(value:string|null){if(!value)return"—";return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined}).format(new Date(value))}
function byCurrency(rows:MoneyBucket[],currency:string){return rows.find(x=>x.currency===currency)||null}

export default function ExecutiveReportsPage(){
 const [data,setData]=useState<Payload>(empty),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[selectedId,setSelectedId]=useState("");
 const [notes,setNotes]=useState({title:"",highlights:"",risks:"",priorities:"",decisions:""});
 async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch("/api/admin/crm/executive-reports",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return}const p=await r.json().catch(()=>({}));if(!r.ok){setNotice(p.error||"Impossible de charger les rapports exécutifs.");return}const next={...empty,...p} as Payload;setData(next);const requested=new URLSearchParams(location.search).get("report");setSelectedId(current=>current&&next.reports.some(x=>x.id===current)?current:requested&&next.reports.some(x=>x.id===requested)?requested:next.reports[0]?.id||"")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);const selected=data.reports.find(x=>x.id===selectedId)||null;const selectedIndex=selected?data.reports.findIndex(x=>x.id===selected.id):-1;const previous=selectedIndex>=0?data.reports[selectedIndex+1]||null:null;const metrics=selected?.metrics||data.live;
 useEffect(()=>{if(!selected){setNotes({title:`Executive & Investor Report · ${monthLabel(data.currentMonth)}`,highlights:"",risks:"",priorities:"",decisions:""});return}setNotes({title:selected.title,highlights:selected.highlights||"",risks:selected.risks||"",priorities:selected.priorities||"",decisions:selected.decisions||""})},[selectedId,selected?.updated_at,data.currentMonth]);
 async function act(action:string,body:Record<string,unknown>,message:string){setBusy(action);setNotice("");try{const r=await fetch("/api/admin/crm/executive-reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body})});const p=await r.json().catch(()=>({}));if(!r.ok){setNotice(p.error||"Action impossible.");return false}setNotice(message);await load(true);if(p.report?.id)setSelectedId(p.report.id);return true}finally{setBusy("")}}
 async function capture(){await act("capture",{periodMonth:data.currentMonth,title:notes.title||undefined},"Board pack du mois capturé. Il reste modifiable tant qu’il n’est pas finalisé.")}
 async function saveNotes(){if(!selected)return;await act("notes",{id:selected.id,...notes},"Commentaires exécutifs enregistrés.")}
 async function finalize(){if(!selected||selected.status==="final")return;if(!confirm("Finaliser ce board pack ? Les chiffres et commentaires seront ensuite verrouillés."))return;await act("finalize",{id:selected.id},"Board pack finalisé et verrouillé.")}
 function exportCsv(){if(!selected||!metrics)return;const rows=[["Period","Currency","MRR","ARR","NRR","GRR","New MRR","Expansion","Contraction","Churn","Billed","Collected","Outstanding","DSO","Open pipeline","Weighted pipeline","Renewal forecast","Expansion forecast"]];for(const r of metrics.revenue.currencies){const pipe=byCurrency(metrics.commercial.pipelineByCurrency,r.currency),forecast=byCurrency(metrics.forecast.byCurrency,r.currency);rows.push([selected.period_month,r.currency,r.currentMrr,r.currentArr,r.nrr??"",r.grr??"",r.newMrr,r.expansionMrr,r.contractionMrr,r.churnMrr,r.invoicedMonth,r.collectedMonth,r.outstanding,r.dso??"",pipe?.amount??0,pipe?.weighted??0,forecast?.renewal??0,forecast?.expansion??0].map(String))}const blob=new Blob([rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`moony-executive-${selected.period_month}.csv`;a.click();URL.revokeObjectURL(url)}
 const quality=selected?.data_quality||metrics?.dataQuality||null;const metricCards=metrics?[{label:"Clients actifs",value:metrics.customers.active,icon:UsersRound},{label:"À risque / critiques",value:metrics.customers.atRisk+metrics.customers.critical,icon:ShieldAlert},{label:"Feedbacks ouverts",value:metrics.voice.open,icon:BarChart3},{label:"Escalades ouvertes",value:metrics.escalations.open,icon:ShieldAlert},{label:"Nouveaux leads du mois",value:metrics.commercial.leadsCreatedInPeriod,icon:TrendingUp}]:[];
 return <AdminWorkspace active="Executive Reports" title="Executive & Investor Reporting" subtitle="Figez un board pack mensuel auditable : revenu, pipeline, portefeuille clients et voix du client. Les devises restent séparées et les commentaires stratégiques restent humains." actions={<div className="flex flex-wrap gap-2"><Link href="/admin/customer-success/revenue-command" className="rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm">Revenue Command</Link><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-[#5b2f22]/12 bg-white px-4 py-2.5 text-sm"><RefreshCw size={14}/> Actualiser</button><button disabled={!data.available||busy==="capture"} onClick={()=>void capture()} className="rounded-lg bg-[#7e3518] px-4 py-2.5 text-sm text-white disabled:opacity-40">{busy==="capture"?"Capture…":selected?.period_month===data.currentMonth&&selected.status==="draft"?"Recapturer le mois":"Capturer le mois"}</button></div>}>
  {notice?<div className="mb-5 rounded-xl border border-[#d8bda9] bg-[#fff8f2] px-4 py-3 text-xs text-[#6f351f]">{notice}</div>:null}
  {!data.available?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Appliquez <strong>20260911154500_crm_executive_investor_reporting.sql</strong> après V8.11 pour activer CRM V8.12.</div>:null}
  {data.liveError?<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Prévisualisation live partielle : {data.liveError}</div>:null}
  <div className="grid gap-4 2xl:grid-cols-[280px_1fr]">
   <aside className="admin-card admin-shadow overflow-hidden"><div className="border-b border-[#5b2f22]/8 p-4"><span className="text-[9px] uppercase tracking-[.16em] text-[#9d4c27]">Historique immuable</span><h2 className="moony-serif mt-1 text-2xl">Board packs</h2></div><div className="divide-y divide-[#5b2f22]/7">{data.reports.map(r=><button key={r.id} onClick={()=>setSelectedId(r.id)} className={`w-full p-4 text-left ${selectedId===r.id?"bg-[#f6e5d9]":"hover:bg-[#fffaf6]"}`}><div className="flex items-center justify-between gap-2"><strong className="text-xs capitalize">{monthLabel(r.period_month)}</strong><span className={`rounded-full px-2 py-1 text-[9px] ${r.status==="final"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-800"}`}>{r.status==="final"?"Final":"Brouillon"}</span></div><p className="mt-2 text-[9px] text-[#5b2f22]/42">Capture {date(r.captured_at)}</p></button>)}{!data.reports.length?<p className="p-6 text-center text-xs text-[#5b2f22]/40">Aucun board pack capturé. Les chiffres live restent une prévisualisation, pas un historique.</p>:null}</div></aside>
   <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#2d1812] p-5 text-[#fffaf4]"><div><span className="text-[9px] uppercase tracking-[.18em] text-[#e9b78f]">{selected?selected.status==="final"?"Board pack finalisé":"Board pack brouillon":"Prévisualisation live"}</span><h2 className="moony-serif mt-1 text-3xl font-normal capitalize">{selected?.title||`Executive & Investor Report · ${monthLabel(data.currentMonth)}`}</h2><p className="mt-2 text-[10px] text-[#fffaf4]/55">{selected?`Chiffres capturés le ${date(selected.captured_at)}`:"Les données live ne deviennent historiques qu’après une capture explicite."}</p></div>{selected?<div className="flex gap-2">{selected.status==="final"?<span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/15 px-3 py-2 text-xs text-emerald-200"><FileLock2 size={14}/> Verrouillé</span>:<button onClick={()=>void finalize()} disabled={busy==="finalize"} className="inline-flex items-center gap-2 rounded-lg bg-[#fffaf4] px-4 py-2 text-xs text-[#2d1812]"><CheckCircle2 size={14}/> Finaliser</button>}<button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-2 text-xs"><Download size={14}/> CSV</button></div>:null}</div>
    {quality&&!quality.revenue?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">Revenue Command est indisponible : ce rapport peut être conservé en brouillon, mais pas finalisé comme board pack financier.</div>:null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metricCards.map(({label,value,icon:Icon})=><article key={label} className="admin-card admin-shadow p-4"><Icon size={16} className="text-[#9d4c27]"/><strong className="moony-serif mt-2 block text-3xl font-normal">{loading?"…":value}</strong><span className="text-[9px] text-[#5b2f22]/45">{label}</span></article>)}</div>
    {metrics?.revenue.currencies.map(r=>{const pipe=byCurrency(metrics.commercial.pipelineByCurrency,r.currency),forecast=byCurrency(metrics.forecast.byCurrency,r.currency),prev=previous?.metrics?.revenue?.currencies?.find(x=>x.currency===r.currency),mrrDelta=prev?r.currentMrr-prev.currentMrr:null;return <AdminCard key={r.currency} title={`Revenue & Investor KPIs · ${r.currency}`} action={<span className="text-[10px] text-[#5b2f22]/45">Aucun total multi-devises</span>}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["MRR",money(r.currentMrr,r.currency),mrrDelta==null?"":`${mrrDelta>=0?"+":""}${money(mrrDelta,r.currency)} vs précédent`],["ARR",money(r.currentArr,r.currency),"MRR × 12"],["NRR",pct(r.nrr),"hors New MRR"],["GRR",pct(r.grr),"max théorique 100 %"],["Pipeline ouvert",money(pipe?.amount||0,r.currency),`${pipe?.count||0} opportunité(s)`],["Pipeline pondéré",money(pipe?.weighted||0,r.currency),"probabilités CRM explicites"]].map(([l,v,s])=><div key={String(l)} className="rounded-xl bg-[#fff8f2] p-3"><span className="text-[9px] text-[#5b2f22]/40">{l}</span><strong className="mt-1 block text-sm">{v}</strong><small className="mt-1 block text-[8px] text-[#5b2f22]/35">{s}</small></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><div><h3 className="text-xs font-semibold">Revenue bridge</h3><div className="mt-2 space-y-2 text-[10px]">{[["MRR départ",r.startingMrr],["+ New",r.newMrr],["+ Expansion",r.expansionMrr],["− Contraction",r.contractionMrr],["− Churn",r.churnMrr],["MRR actuel",r.currentMrr]].map(([l,v])=><div key={String(l)} className="flex justify-between border-b border-[#5b2f22]/7 pb-1"><span>{l}</span><strong>{money(Number(v),r.currency)}</strong></div>)}</div></div><div><h3 className="text-xs font-semibold">Cash & receivables</h3><div className="mt-2 space-y-2 text-[10px]">{[["Facturé mois",money(r.invoicedMonth,r.currency)],["Encaissé mois",money(r.collectedMonth,r.currency)],["À recevoir",money(r.outstanding,r.currency)],["En retard",money(r.overdue,r.currency)],["DSO",r.dso==null?"—":`${r.dso.toFixed(1)} j`]].map(([l,v])=><div key={String(l)} className="flex justify-between border-b border-[#5b2f22]/7 pb-1"><span>{l}</span><strong>{v}</strong></div>)}</div></div><div><h3 className="text-xs font-semibold">Renewal / Expansion forecast</h3><div className="mt-2 space-y-2 text-[10px]">{[["Renouvellement",money(forecast?.renewal||0,r.currency)],["Expansion",money(forecast?.expansion||0,r.currency)],["Commit",money(forecast?.commit||0,r.currency)],["Best case",money(forecast?.bestCase||0,r.currency)],["Sans probabilité",String(forecast?.unscored||0)]].map(([l,v])=><div key={String(l)} className="flex justify-between border-b border-[#5b2f22]/7 pb-1"><span>{l}</span><strong>{v}</strong></div>)}</div></div></div></AdminCard>})}
    {metrics?<div className="grid gap-4 xl:grid-cols-2"><AdminCard title="Commercial funnel"><div className="space-y-2">{Object.entries(stageLabels).map(([stage,label])=>{const value=metrics.commercial.leadStages[stage]||0,total=Math.max(1,metrics.commercial.leadsTotal);return <div key={stage}><div className="flex justify-between text-[10px]"><span>{label}</span><strong>{value}</strong></div><div className="mt-1 h-1.5 rounded-full bg-[#eadfd6]"><div className="h-full rounded-full bg-[#9d4c27]" style={{width:`${Math.min(100,value/total*100)}%`}}/></div></div>})}</div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><div className="rounded-lg bg-[#fff8f2] p-3">Opportunités ouvertes<strong className="mt-1 block text-lg">{metrics.commercial.openOpportunities}</strong></div><div className="rounded-lg bg-[#fff8f2] p-3">Propositions acceptées ce mois<strong className="mt-1 block text-lg">{metrics.commercial.proposalsAcceptedInPeriod}</strong></div></div></AdminCard><AdminCard title="Customer portfolio & Voice"><div className="grid grid-cols-2 gap-2 text-[10px] sm:grid-cols-3">{[["Sains",metrics.customers.healthy],["À surveiller",metrics.customers.watch],["À risque",metrics.customers.atRisk],["Critiques",metrics.customers.critical],["Renewals ≤ 90 j",metrics.customers.renewals90],["Feedbacks critiques",metrics.voice.critical]].map(([l,v])=><div key={String(l)} className="rounded-lg bg-[#fff8f2] p-3"><span>{l}</span><strong className="mt-1 block text-lg">{v}</strong></div>)}</div>{metrics.voice.topThemes.length?<div className="mt-4"><h3 className="text-xs font-semibold">Thèmes VoC explicitement tagués</h3><div className="mt-2 flex flex-wrap gap-2">{metrics.voice.topThemes.map(x=><span key={x.theme} className="rounded-full bg-[#f3e4d3] px-3 py-1.5 text-[10px]">{x.theme} · {x.count}</span>)}</div></div>:null}</AdminCard></div>:null}
    {selected?<AdminCard title="Narratif de direction" action={selected.status==="final"?<span className="text-[10px] text-[#5b2f22]/45">Verrouillé avec le rapport</span>:<button onClick={()=>void saveNotes()} disabled={busy==="notes"} className="inline-flex items-center gap-2 rounded-lg bg-[#2d1812] px-4 py-2 text-xs text-white"><Save size={13}/> Enregistrer</button>}><div className="grid gap-3 lg:grid-cols-2"><label className="text-[10px] text-[#5b2f22]/45">Titre<input disabled={selected.status==="final"} value={notes.title} onChange={e=>setNotes(x=>({...x,title:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm text-[#2d1812] disabled:bg-stone-50"/></label><div/><label className="text-[10px] text-[#5b2f22]/45">Faits marquants<textarea disabled={selected.status==="final"} rows={5} value={notes.highlights} onChange={e=>setNotes(x=>({...x,highlights:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm text-[#2d1812] disabled:bg-stone-50"/></label><label className="text-[10px] text-[#5b2f22]/45">Risques<textarea disabled={selected.status==="final"} rows={5} value={notes.risks} onChange={e=>setNotes(x=>({...x,risks:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm text-[#2d1812] disabled:bg-stone-50"/></label><label className="text-[10px] text-[#5b2f22]/45">Priorités du prochain mois<textarea disabled={selected.status==="final"} rows={5} value={notes.priorities} onChange={e=>setNotes(x=>({...x,priorities:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm text-[#2d1812] disabled:bg-stone-50"/></label><label className="text-[10px] text-[#5b2f22]/45">Décisions / arbitrages<textarea disabled={selected.status==="final"} rows={5} value={notes.decisions} onChange={e=>setNotes(x=>({...x,decisions:e.target.value}))} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm text-[#2d1812] disabled:bg-stone-50"/></label></div></AdminCard>:null}
    {quality?<AdminCard title="Qualité & provenance"><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{Object.entries({"Revenue":quality.revenue,"Commercial":quality.commercial,"Customer Success":quality.customerSuccess,"Renewal Desk":quality.renewalForecast,"VoC":quality.voiceOfCustomer,"Escalades":quality.escalations}).map(([l,ok])=><div key={l} className={`rounded-lg p-3 text-[10px] ${ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}><strong>{ok?"Disponible":"Manquant"}</strong><span className="mt-1 block">{l}</span></div>)}</div>{quality.notes?.length?<div className="mt-3 rounded-xl bg-[#fff8f2] p-3 text-[10px] leading-5 text-[#5b2f22]/55">{quality.notes.join(" · ")}</div>:null}</AdminCard>:null}
   </div>
  </div>
 </AdminWorkspace>;
}
