"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, Clipboard, FileImage, FileText, Search, Trash2, Upload } from "lucide-react";
import { AdminCard, AdminWorkspace } from "@/components/admin-workspace";

type Media={id:string;created_at:string;file_name:string;public_url:string;mime_type:string|null;file_size:number|null;alt_text:string|null;folder:string};
function size(value:number|null){if(!value)return"—";if(value<1024*1024)return`${Math.round(value/1024)} Ko`;return`${(value/1024/1024).toFixed(1)} Mo`}

export default function MediaPage(){
 const [media,setMedia]=useState<Media[]>([]);const [query,setQuery]=useState("");const [folder,setFolder]=useState("all");const [loading,setLoading]=useState(true);const [uploading,setUploading]=useState(false);const [notice,setNotice]=useState("");const [selected,setSelected]=useState<Media|null>(null);const [alt,setAlt]=useState("");const [editFolder,setEditFolder]=useState("general");
 async function load(){setLoading(true);const params=new URLSearchParams();if(query.trim())params.set("q",query.trim());if(folder!=="all")params.set("folder",folder);const response=await fetch(`/api/admin/media?${params.toString()}`,{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const data=await response.json();if(response.ok)setMedia(data.media??[]);else setNotice(data.error??"Impossible de charger les médias.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 const folders=useMemo(()=>["all",...Array.from(new Set(media.map(item=>item.folder)))],[media]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setUploading(true);setNotice("Envoi du fichier…");const response=await fetch("/api/admin/media",{method:"POST",body:data});const result=await response.json();if(response.ok){setNotice("Média ajouté à la bibliothèque.");form.reset();await load()}else setNotice(result.error??"Import impossible.");setUploading(false)}
 function open(item:Media){setSelected(item);setAlt(item.alt_text??"");setEditFolder(item.folder)}
 async function saveMeta(){if(!selected)return;const response=await fetch("/api/admin/media",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,altText:alt,folder:editFolder})});const data=await response.json();if(response.ok){setNotice("Informations du média enregistrées.");setSelected(data.media);await load()}else setNotice(data.error??"Modification impossible.")}
 async function remove(item:Media){if(!confirm(`Supprimer « ${item.file_name} » de la bibliothèque ?`))return;const response=await fetch(`/api/admin/media?id=${item.id}`,{method:"DELETE"});const data=await response.json();if(response.ok){setNotice("Média supprimé.");if(selected?.id===item.id)setSelected(null);await load()}else setNotice(data.error??"Suppression impossible.")}
 async function copy(url:string){await navigator.clipboard.writeText(url);setNotice("URL copiée. Vous pouvez la coller dans Site & Design ou un bloc CMS.")}
 return <AdminWorkspace active="Médias" title="Bibliothèque de médias" subtitle="Importez et organisez les images, visuels, logos et PDF utilisés par le site MOONY." actions={<label htmlFor="media-upload" className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#7e3518] px-5 py-2.5 text-sm text-white"><Upload size={15}/>Importer</label>}>
  <div className="grid gap-4 xl:grid-cols-[1fr_350px]">
   <div className="space-y-4">
    <AdminCard title="Importer un média"><form onSubmit={upload} className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input id="media-upload" name="file" type="file" required accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/svg+xml,application/pdf" className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-xs"/><input name="folder" placeholder="Dossier, ex. homepage" defaultValue="general" className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2.5 text-xs"/><button disabled={uploading} className="rounded-lg border border-[#5b2f22]/12 bg-[#fffaf6] px-4 py-2.5 text-xs font-semibold disabled:opacity-50">{uploading?"Import…":"Ajouter"}</button></form><p className="mt-2 text-[10px] text-[#5b2f22]/42">Images ou PDF · 15 Mo maximum · les fichiers publics obtiennent une URL stable utilisable dans le CMS.</p></AdminCard>
    <AdminCard title="Vos médias" action={<div className="flex gap-2"><div className="flex items-center gap-2 rounded-lg border border-[#5b2f22]/10 bg-white px-3"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load()}} placeholder="Rechercher…" className="w-40 bg-transparent py-2 text-xs outline-none"/></div><select value={folder} onChange={e=>{setFolder(e.target.value);setTimeout(()=>void load(),0)}} className="rounded-lg border border-[#5b2f22]/10 bg-white px-3 py-2 text-xs">{folders.map(value=><option key={value} value={value}>{value==="all"?"Tous les dossiers":value}</option>)}</select><button onClick={()=>void load()} className="rounded-lg border border-[#5b2f22]/10 px-3 py-2 text-xs">Filtrer</button></div>}>
     {loading?<div className="py-14 text-center text-sm text-[#5b2f22]/45">Chargement de la bibliothèque…</div>:media.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{media.map(item=><article key={item.id} className={`overflow-hidden rounded-xl border bg-white transition ${selected?.id===item.id?"border-[#b65e39] shadow-md":"border-[#5b2f22]/8 hover:border-[#b65e39]/35"}`}><button onClick={()=>open(item)} className="block w-full text-left">{item.mime_type?.startsWith("image/")?<div className="h-44 bg-[#f1e5dc]"><img src={item.public_url} alt={item.alt_text||""} className="h-full w-full object-cover"/></div>:<div className="grid h-44 place-items-center bg-[#f4e9df]"><FileText size={38} className="text-[#9b5a3c]"/></div>}<div className="p-3"><strong className="block truncate text-xs">{item.file_name}</strong><div className="mt-2 flex items-center justify-between text-[10px] text-[#5b2f22]/42"><span>{item.folder}</span><span>{size(item.file_size)}</span></div></div></button><div className="flex border-t border-[#5b2f22]/7"><button onClick={()=>void copy(item.public_url)} className="flex flex-1 items-center justify-center gap-1 py-2 text-[10px] hover:bg-[#faf0e8]"><Clipboard size={11}/>Copier URL</button><button onClick={()=>void remove(item)} className="border-l border-[#5b2f22]/7 px-3 text-red-500 hover:bg-red-50" aria-label="Supprimer"><Trash2 size={12}/></button></div></article>)}</div>:<div className="grid place-items-center py-16 text-center"><FileImage size={35} className="text-[#5b2f22]/22"/><p className="mt-3 text-sm text-[#5b2f22]/45">Aucun média dans cette sélection.</p></div>}
    </AdminCard>
   </div>
   <AdminCard title="Détails du média">{selected?<div className="space-y-4">{selected.mime_type?.startsWith("image/")?<img src={selected.public_url} alt={alt} className="max-h-64 w-full rounded-xl object-cover"/>:null}<div><p className="text-xs font-semibold">{selected.file_name}</p><p className="mt-1 break-all text-[10px] text-[#5b2f22]/42">{selected.public_url}</p></div><label className="block text-xs">Texte alternatif<textarea rows={3} value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Décrivez l’image pour l’accessibilité et le SEO." className="mt-1 w-full resize-none rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><label className="block text-xs">Dossier<input value={editFolder} onChange={e=>setEditFolder(e.target.value)} className="mt-1 w-full rounded-lg border border-[#5b2f22]/10 px-3 py-2.5 text-sm"/></label><button onClick={()=>void saveMeta()} className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#7e3518] px-4 py-3 text-sm text-white"><Check size={14}/>Enregistrer</button><button onClick={()=>void copy(selected.public_url)} className="flex w-full items-center justify-center gap-2 rounded-lg border border-[#5b2f22]/12 px-4 py-3 text-sm"><Clipboard size={14}/>Copier l’URL</button></div>:<p className="py-12 text-center text-xs leading-6 text-[#5b2f22]/45">Sélectionnez un média pour modifier son texte alternatif, son dossier ou copier son URL.</p>}</AdminCard>
  </div>
  {notice?<div className="fixed bottom-5 right-5 z-50 max-w-sm rounded-xl bg-[#3d2119] px-4 py-3 text-sm text-white shadow-xl">{notice}</div>:null}
 </AdminWorkspace>
}
