import { NextResponse } from "next/server";
import { requireAdmin, writeAuditLog } from "@/lib/admin-api";
import { getRevenueCommandData } from "@/lib/crm-revenue-command";
import { CRM_CURRENCIES, getFxBundle } from "@/lib/crm-fx";

type Row={currency:string;mrr:number;arr:number;billed:number;collected:number;outstanding:number;overdue:number;pipeline:number;weightedPipeline:number;won:number;activeProposals:number};
function bucket(map:Map<string,Row>,currency:unknown){const code=String(currency||"XOF").toUpperCase();let row=map.get(code);if(!row){row={currency:code,mrr:0,arr:0,billed:0,collected:0,outstanding:0,overdue:0,pipeline:0,weightedPipeline:0,won:0,activeProposals:0};map.set(code,row)}return row}
function number(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
async function summary(supabase:any){const map=new Map<string,Row>();let revenueAvailable=false,commercialAvailable=false;try{const revenue=await getRevenueCommandData(supabase);revenueAvailable=Boolean(revenue.available);for(const item of revenue.currencies||[]){const row=bucket(map,item.currency);row.mrr+=number(item.currentMrr);row.arr+=number(item.currentArr);row.billed+=number(item.invoicedMonth);row.collected+=number(item.collectedMonth);row.outstanding+=number(item.outstanding);row.overdue+=number(item.overdue)}}catch{}
 const [opportunities,proposals]=await Promise.all([supabase.from("website_crm_opportunities").select("stage,amount,currency,probability").limit(10000),supabase.from("website_crm_proposals").select("status,total_amount,currency").limit(10000)]);commercialAvailable=!opportunities.error&&!proposals.error;if(!opportunities.error)for(const item of opportunities.data||[]){const row=bucket(map,item.currency),amount=Math.max(0,number(item.amount));if(item.stage==="won")row.won+=amount;else if(item.stage!=="lost"){row.pipeline+=amount;row.weightedPipeline+=amount*Math.max(0,Math.min(1,number(item.probability)))}}if(!proposals.error)for(const item of proposals.data||[]){if(!["draft","sent","viewed"].includes(String(item.status)))continue;bucket(map,item.currency).activeProposals+=Math.max(0,number(item.total_amount))}for(const code of CRM_CURRENCIES)if(!map.has(code))map.set(code,{currency:code,mrr:0,arr:0,billed:0,collected:0,outstanding:0,overdue:0,pipeline:0,weightedPipeline:0,won:0,activeProposals:0});return{rows:[...map.values()].filter(row=>Object.entries(row).some(([key,value])=>key!=="currency"&&Number(value)!==0)).sort((a,b)=>a.currency.localeCompare(b.currency)),revenueAvailable,commercialAvailable}}
export async function GET(request:Request){const {error,supabase}=requireAdmin(request,"crm.read");if(error||!supabase)return error;const [fx,financial]=await Promise.all([getFxBundle(supabase),summary(supabase)]);return NextResponse.json({fx,summary:financial,supportedCurrencies:CRM_CURRENCIES})}
export async function POST(request:Request){const {error,supabase,session}=requireAdmin(request,"crm.write");if(error||!supabase||!session)return error;let body:Record<string,unknown>={};try{body=await request.json()}catch{}if(body.action!=="refresh")return NextResponse.json({error:"Action FX inconnue."},{status:400});const actor=session.name||session.email||"MOONY Admin";const fx=await getFxBundle(supabase,{forceRefresh:true,actor});if(!fx.available)return NextResponse.json({error:fx.error||"Actualisation FX impossible.",fx},{status:502});await writeAuditLog(supabase,session,"crm.fx_refreshed","crm_fx",null,"Taux de change CRM actualisés",{source:fx.source,fetchedAt:fx.fetchedAt,baseCurrency:fx.baseCurrency,rateDates:fx.rateDates});return NextResponse.json({fx})}
